### ISSUE TITLE
Default Templates

### ISSUE THREAD

**Issue by LeoM49** [Sigil-Ebook/Sigil#325] opened 2017-12-06 09:17 UTC
Hi, I am am new here. So sorry for the question. I saw a YouTube tudorial about sigil and there it was said, that a default template for sigil is available, whith prepared chapters, css file etc. Where can I get this???
Thanks for your help.

**Comment by kevinhendricks** [comment] 2017-12-06 12:03
Closing as this is not a bug. As explained in the README on this site, this is for bug reports. Please use our User Support forums on www.mobileread.com for user questions and help related to Sigil.

**Closed by kevinhendricks** 2017-12-06 12:03 UTC
