### ISSUE TITLE
There's no book view in ver. 0.9.16

### ISSUE THREAD

**Issue by tuesdaypd** [Sigil-Ebook/Sigil#445] opened 2019-07-29 02:25 UTC
There's no book view in ver. 0.9.16.
Therefore F2 key or double clicking tap doesn't work. TT

**Comment by kevinhendricks** [comment] 2019-07-29 02:33
As has been announced many times, the long deprecated BookView has been removed from Sigil and will not be put back.  To help users that still want something like BookView we have created a new standalone xhtml editor called PageEdit along with a new icon to launch it.

Please see our MobileRead users forums. For more discussion.

Closing as this is not a bug.

**Closed by kevinhendricks** 2019-07-29 02:33 UTC

**Comment by tuesdaypd** [comment] 2019-07-29 02:43
> As has been announced many times, the long deprecated BookView has been removed from Sigil and will not be put back. To help users that still want something like BookView we have created a new standalone xhtml editor called PageEdit along with a new icon to launch it.
> 
> Please see our MobileRead users forums. For more discussion.
> 
> Closing as this is not a bug.

Thanks for your reply!! :)
