### ISSUE TITLE
[Bug]:  ok in sigil preview but not on ReadEra

### ISSUE THREAD

**Issue by saisot2006** [Sigil-Ebook/Sigil#698] opened 2022-09-09 03:23 UTC
### Bug Description

Hi, I edited my epub with sigil . I insert 1 picture sothat it show full page. It looks ok in sigil preview but it shows some code on my android app ReadEra beside the picture:

@page {padding: 0pt; margin:0pt} body { text-align: center; padding:0pt; margin: 0pt; }

### Platform (OS)

Windows (Default)

### OS Version / Specifics

10

### What version of Sigil are you using?

1.9.10

**Comment by BeckyDTP** [comment] 2022-09-09 06:55
If your styles are not correctly placed in the `<head>` section you can get this effect.
At 99.9%, it is not a bug in Sigil, but a wrongly prepared EPUB file. The preview in Sigil is based on the Chrome engine, and it "forgives" many mistakes.
Please provide the code of the XHTML file that causes the problem and you will get a more accurate answer.

**Comment by kevinhendricks** [comment] 2022-09-09 14:10
As BeckDTP says, the issue is with your mark-up not Sigil.  Sigil can not guarantee the mark-up you create is without errors, nor can it detect bugs or shortcomings in e-readers.  It is a good idea to use the epubcheck plugin for Sigil to help validate your xhml mark-up.  There is a similar validator plugin for css code.

Additional help is available from Sigil users forum on www.mobileread.com.  It is free to join.

Closing this since it is not a bug or issue with Sigil.

**Closed by kevinhendricks** 2022-09-09 14:10 UTC
Labels: invalid
