### ISSUE TITLE
re-open problem.

### ISSUE THREAD

**Issue by gituser9527** [Sigil-Ebook/Sigil#201] opened 2016-03-27 05:48 UTC
i just testes the same issue in sigil version 0.9.3 (Sigil-0.9.3-Mac-Package.dmg), and it occurs too.
almost any other softwares, after clicking "x", they can re-appear the main window, please notice this.
so i insist it's still a problem, big or small, which'd be solved.
the window-frame is surely 'hiden' background to the memory, not 'closed'or'minimized', but even it's clicked'x' button, it still should be  re-opened by clicking the icon on DOCK or Launchpad.
but neither operation is available.
EVERY SOFTWARE CAN BE RE-OPENED by CLICKING the ICON on DOCK even after they are CLOSED by CLICKING "x" button!
Please check whether it's the problem with my computer or the soft(can you re-open any other soft by clicking the icon on the dock after clicking 'x'? what about the sigil 0.9.5.0?)
wish you a good day.

**Comment by kevinhendricks** [comment] 2016-03-27 08:30
Again, this is not a bug, this is by design. 

First, Stop using launchpad.

Fire up Sigil.  Close last main window by using X.  Notice that using X  does NOT exit the application! Sigil is still running.  See its menu bar at the top.  Use its New or File menu to open a new Window of Sigil. Or usue Quit To actually stop Sigil.  This is how Sigil has always worked on a Mac and how it continue to work.

This is similar to how closing the last window in Office or the last browser window in Safari works.  Or the last mail viewer in Mail works. Those applications are still running. You have to quit those applications to get them to actually exit.

**Closed by kevinhendricks** 2016-03-27 08:30 UTC

**Comment by gituser9527** [comment] 2016-03-27 13:08
Yeah now i know that this issue is nothing about bugs, it's only about function designs and user experiences.
For a normal applications on the osx platform, there is only one way to quit, but there are multiple ways of different levels to 'hide' it. Of course it's not a formal operation to "QUIT" the app by clicking 'x' button, but if the button was placed there on the left-top corner of the main-frame/window, then it must has a correct response. Further more, i suppose that we have the consensus that there are 3 kinds of operations to let the window disappear, which are respectively equivalent to the following hot-key shortcuts:
1. clicking 'x' = COMMAND+W
2. clicking '-' = COMMAND + M(or even COMMAND+H to hide all)
3. select 'quit' form menus = command+ Q
So, after each of the second or  third operation, we can still re-open the app to the front， but HOW CAN WE RE-OPEN it after the first operation?
so, this is the question.
Maybe it's surely not a bug, but it's still a very unfirendly or asymmetry functionality. In another word, it's unperfect. Let's talk about some similar user  scenes and different designs: 
1. firefox:
after clicking 'x', all the tabs are closed;we can re-open it by click any icons of the firefox either in dock or lauchpad, and find the historical tabs from 'history' ; this time , it's a little different from 'cmd+w(closing current tab)';
2. itunes:
playing music; click 'x', the player continues; this time, it's equivalent to 'command+m'; re-open it any time in any ways;
3. osx network utility:
clicking 'x' = quit, it closed completely. re-open it anytime in any ways;
4. sigil:
clicking 'x', what has it done? how could the user re-open it? only 1 way: select 'quit' from dock-right-click-menu...
so you see, it's surely not a bug, it's asymmetry functionality.
I am not reporting a bug, i am trying to give a recommendation to make the software more and more perfect, while i like this software so much and i have used it for years.
wish you a good day and appreciate your hard working.

**Comment by kevinhendricks** [comment] 2016-03-27 14:06
It is NOT hidden.  You can simply right click on the Sigil icon in the dock to close it.  Or normal click on the Sigil icon in the dock to bring the Sigil menubar to the front, where as I have now explained repeatedly, you can then select File->New to generate a new empty epub or File->Open to open an existing one, or File-> Quit to exit the application.

Again, Sigil on Mac has always worked this way.  I will not be changing it because of launchpad quirks.

**Comment by gituser9527** [comment] 2016-03-27 14:41
now i am not quite sure if there is any misunderstands between us? what you said is all i knew, BUT,
as you said, "Or normal click on the Sigil icon in the dock to bring the Sigil menubar to the front", the problem is "this normal click is NOT SUCCESSFUL after clicking 'x' ", because if the 'x' was clicked, the sigil was still IN THE MEMORY but don't-know-why can't be re-called-to-front, unless manually QUIT it by right clicking on the icon of DOCK and then click it again!
so whether you consider this a bug or not, or whether you consider this a quirks-avoid functional design or not,  there should be an alternative choise as my negligible recommendation to SIGIL:
1. replace the action of 'x'  by  'quit(command+q)' in order to closed it completely to avoid this issue.
2. or even the 'x' button could be unused or deactiviated or hidden.

won't  a completist be confused if there's a useless button  in a software-user-interface ? haha~...
^_^

**Comment by kevinhendricks** [comment] 2016-03-27 15:02
Then that is a bug in your system.  I develop Sigil on MacOSX so every release is developed, tested and built on Mac OS X and nothing in the code changes has changed any of this.  Perhaps you have some system menubar utility that prevents it from coming up?  

Clicking on any icon of a running program (an icon with the dot at the bottom) in the dock, always brings that program's version of the menubar to the system menubar in the top left corner of the screen.

If this does not work on your Mac, try rebooting into safe mode and trying again to see if some other program has installed something that interferes with that operation.

**Comment by gituser9527** [comment] 2016-03-27 15:30
so, yeah,  this is just the right answer at last: i only wanted to ensure whether it's the problem of SIGIL of this version or of my computer/os.
In fact i prefer it my computer's problem.thank you so much for responsing so repeatedly and patiently.
i'll try later by the steps you told me, and i'll submit the results here whetherever successful or not.

**Comment by kevinhendricks** [comment] 2016-03-28 13:21
I assume you understand your vehemence about it being a bug, your continued posting and even duplicating an issue to reopen it simply take away valuable volunteer developer time.  Next time try simply asking a question on Sigil's  www.mobileread.com support forums.  That is what they are there for. Any number of people could have explained things there and not take up what little time we as volunteers have to actually work on and improve Sigil.  Do not create duplicate new issues simply because you disagree.

**Comment by gituser9527** [comment] 2016-03-28 13:53
I am feeling very ashamed for having posted duplicated issues here, while my face blushes. So please do pardon me, and I won't do this any more.
The second lesson I learned is, before creating any issues, make sure whether it is an issue of the software. And, I really didn't occur to using the SUPPORT forum to find answers, how stupid I am!
Thank you so much for letting me know this.
And very sorry for bothering you and wasting your time to read this valueless '(so-called) issue' and response me again and again. 
Appreciating everyong's hard works on softwares.
