### ISSUE TITLE
New Icon Design for future 1.0 Release

### ISSUE THREAD

**Issue by shorshe** [Sigil-Ebook/Sigil#217] opened 2016-05-18 18:33 UTC
What would you think about an Icon refresh for a future 1.0 release?
My rough Idea is attached. 

Anyone else?

![sigil_icon](https://cloud.githubusercontent.com/assets/867891/15370513/ad9a826c-1d37-11e6-9c89-1eb0b08bf163.png)

[Sigil.icns.zip](https://github.com/Sigil-Ebook/Sigil/files/271142/Sigil.icns.zip)

**Comment by kevinhendricks** [comment] 2016-05-18 18:38
Closing this as not a bug.  Instead this is something better suited for discussion on the Sigil user's forum.  So please post this on MobileRead in the Sigil main user's forum to ask for input from actual Sigil users.

http://www.mobileread.com/forums/forumdisplay.php?f=203

I have no preference one way or the other but past discussion has shown that there are strong opinions by many.  If there is a consensus, I would be happy to use it for future Sigil releases

**Closed by kevinhendricks** 2016-05-18 18:38 UTC
