### ISSUE TITLE
custom fonts always appear italic in preview / book view

### ISSUE THREAD

**Issue by taikuli** [Sigil-Ebook/Sigil#144] opened 2015-10-25 19:30 UTC
If CSS is

```css
@font-face {
	font-family:"OCRA";
	font-style:normal;
	font-weight:normal;
	src : url("../Fonts/OCRAStd.otf");
}
```
any text using OCRA as font-family will be rendered as italic in v 0.8.901.
This happens for all fonts (tried three different up to now).

**Comment by dougmassay** [comment] 2015-10-25 19:40
Are you certain there's not something else in play here? I have several books with embedded fonts--none of which render as italic (unless requested to do so) using v0.8.901.

What O.S. are you using?

**Comment by taikuli** [comment] 2015-10-25 20:01
Yes, I'm quite certain. :-)
See yourself...
Hm. ePub is not a supported filetype, so I can only give you a screenshot. :-(
![screenshot](https://cloud.githubusercontent.com/assets/15313608/10717520/2e2caa92-7b5b-11e5-944d-245b6962263a.png)
I'm using Windows 10 (Build 10565).
This is the CSS
```CSS
@font-face {
    font-family:"OCRA";
    font-style:normal;
    font-weight:normal;
    src: url("../Fonts/OCRAStd.otf");
}

p {
	font-family: "OCRA", serif;
}
```
And this is the HTML
```HTML
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <link href="../Styles/Style0001.css" rel="stylesheet" type="text/css"/>
</head>

<body>
  <p>
  The quick brown fox jumps over the lazy dog.
</p>
</body>
</html>
```
And the rest is the default from Sigil 0.8.901.

**Comment by dougmassay** [comment] 2015-10-25 20:18
Just tried your sample code with the OCRAStd.otf font and everything worked as expected with 0.8.901 on Windows 7. 

You mentioned you tried other fonts. What were they? Also ... what are your BookView/Preview font settings (Edit->Preferences->Appearance)?

**Comment by taikuli** [comment] 2015-10-25 20:28
Other fonts were: Chaparral Pro and Adobe Garamond Pro
![font-settings](https://cloud.githubusercontent.com/assets/15313608/10717649/b3e92f40-7b5e-11e5-927a-4cb23897f22c.png)
Nope. On Windows 7, I see the same italics... :-(
Btw: I just ran the x64 installer on this Win7 machine - there was no Sigil installed before on that machine.

**Comment by dougmassay** [comment] 2015-10-25 20:34
You misunderstood me. I meant I tried your example _myself_ on Windows 7 and I can't reproduce your issue. The OCRAStd font displays as it should. No italics.

So as I said originally, there's obviously something else in play here. We just have to figure out what.

**Comment by taikuli** [comment] 2015-10-25 20:39
There was no misunderstanding. I just wanted to see what happens on my Windows 7 box.
So it's most probably not related to Windows 7 or Windows 10. :-)

**Comment by taikuli** [comment] 2015-10-25 21:56
I tried to rename the ePub to docx, but now github says I need write permissions for this repository to attach documents. If there is anything I can help with, just let me know.

**Comment by kevinhendricks** [comment] 2015-10-25 23:31
Hi,
Just tried this on Mac OSX (had to go and download a OCRAStd. font).  No italics, looks fine.  So this is something specific to your set-up.

Have you tried opening that font with a font editor to verify the exact name of the font family.  Also checking the font itself to make sure it is not corrupt.   On some websites they said the font family was "OCR A Std" not exactly what you wrote.  Not sure if that matters or not.

**Comment by kevinhendricks** [comment] 2015-10-26 02:39
Checked this in my Windows 7 Virtual machine and again no italics present.

Sorry, but neither of us can recreate what you are seeing.  It appears to be something specific to your setup.

**Comment by kevinhendricks** [comment] 2015-10-26 03:30
You do have OCRAStd.otf in side the Fonts folder, right?  If there are other fonts in that same folder, please remove them for this test in case they are corrupt.   Please also verify the spelling of the file name.  

According to a Google search of: Windows fonts always italics

These always italic problems on Windows are quite common are typically caused by corrupt or missing fonts.  On Windows, when a font is corrupt or missing, the system replaces them with an italic version for some reason.  Also, problems can be caused by conflicting fonts, and sometimes even Windows registry issues.  Hope something here helps.

**Comment by taikuli** [comment] 2015-10-26 17:01
I double checked the font file and noticed that IE complained about missing permissions. I tried another version of OCRA that worked in IE and now this one also works as expected in Sigil. So I assume the problem is related to a missing permission in the font file itself. Obviously other browsers or ePub readers need fewer permissions.

**Comment by kevinhendricks** [comment] 2015-10-26 17:16
Closing as invalid.

**Closed by kevinhendricks** 2015-10-26 17:16 UTC
