### ISSUE TITLE
Cover has large white borders

### ISSUE THREAD

**Issue by dggilli** [Sigil-Ebook/Sigil#314] opened 2017-09-04 22:17 UTC
There seems to be an issue with the cover.  No matter what size I make my cover it appears in readers with a white border on the sides and the bottom of the cover is cropped.  Once the epub is opened the cover pick if fine.  I removed the cover and submitted my book just to see what it would look like and found that the dimensions of my epub looked slightly wider then all the others.  Could this be why my cover has borders?  I don't see this issue mentioned so maybe I'm doing something wrong?  If so please help.
Other than that, I love this app.  Attached are pics of how the cover appears in ereaders.

![example 1](https://user-images.githubusercontent.com/31635025/30039313-b1de3bca-9194-11e7-93f6-f12ea7ce878f.jpg)
![example 2](https://user-images.githubusercontent.com/31635025/30039314-b1de8738-9194-11e7-931f-1849a46339dc.jpg)

**Comment by kevinhendricks** [comment] 2017-09-06 01:04
This is not really a bug report as different e-readers have differing cover requirements.  Please ask questions related to how best create and size a cover image on our user support forum:

http://www.mobileread.com

More specifically the Digil user support forum can be found at this link:
https://www.mobileread.com/forums/forumdisplay.php?f=203

There are many users there happy to provide tips and guidance.

Closing this as not a bug report.

**Closed by kevinhendricks** 2017-09-06 01:04 UTC

**Comment by dggilli** [comment] 2017-09-06 18:14
Thank you for responding.  I wasn't sure what kind of issue it was.  I looked for a forum and couldn't find one so I went to the source.  Sorry.  


-------- Original Message --------
Subject: Re: [Sigil-Ebook/Sigil] Cover has large white borders (#314)

**Comment by kevinhendricks** [comment] 2017-09-06 21:46
FYI, Links to the forum exist in the README.md and therefore can always be found on the main page of our github site.
