### ISSUE TITLE
Ordinal 341 was not found in the dll "C: Program Files \ Sigil \ Qt5Network.dll"

### ISSUE THREAD

**Issue by niroGH** [Sigil-Ebook/Sigil#322] opened 2017-10-28 10:39 UTC
Hi,
I have built Sigil on my PC: windows 10 64-bit.
If I install Sigil via sigil-installer on another PCs on some PCs its works fine
but on some other PCs I get this error:
_die ordnungszahl 341 wurde in der dll "C:Program Files\Sigil\Qt5Network.dll" nicht gefunden_
translated:
_the ordinal 341 was not found in the dll "C: Program Files \ Sigil \ Qt5Network.dll"_

I already searched in google but nothing was helpful.
Can anyone help me please?

Thank you

**Comment by kevinhendricks** [comment] 2017-10-28 13:10
If you search for the generic error message without the specific ordinal number, they generally relate to missing symbols due to either missing dlls or multiple incompatible versions of the same dll.  Latest versions of Windows 10 has started droping some dlls necessary for some backwards compatibility including things like directplay and a few others.

My guess is the working Windows 10 versions have all of the dlls needed, and that more recently installed or updated Windows 10 installations are actually missing things that were needed or were present when Qt was built.

Does running official built Sigil installers end up with the same problems.  If not, the problem is probably in your own build process.  You could try doing the build on one of the Windows boxes that your current version fails on to try to determine the missing symbol and dll.

DiapDealer is really the Windows expert and hopefully he may have a better idea of what is going on.

**Comment by dougmassay** [comment] 2017-10-28 16:34
It's not something I've come across before. There's certainly been no reports of anything like it with the official Windows release of Sigil. What version of Qt are you building Sigil against? Did you build Qt yourself, or use the precompiled version of Qt5.6.2 I made available?

If you compiled Qt yourself, it could be the old SSL issue rearing its head again. Where incompatible versions of openSSL on the system PATH were trying to be loaded by Qt. That's what led me to disable SSL in the versions of Qt I distribute with Sigil in the first place.

**Comment by niroGH** [comment] 2017-10-28 18:40
@kevinhendricks 
No, running official built Sigil installers not ends up with the same problems. I try to build it on windows where the error has appeared. 

@dougmassay 
I use the precompiled version of Qt5.6.2.

Thank you

**Comment by dougmassay** [comment] 2017-10-30 11:51
A message about missing ordinals can also apparently be caused by a missing c++ redistributable. Does the distributable for the vs2015 runtime show up in Add/Remove programs on machines the error occurs on? Do you have the proper vs2015 redistributable in the proper folder of the source code (and named correctly) so that it gets included with Sigil's installer?

**Comment by kevinhendricks** [comment] 2017-10-31 14:27
He could have also compiled it using an earlier VS and that would then create the issue as well, wouldn't it.

**Comment by dougmassay** [comment] 2017-10-31 14:40
Yes. That's possible. Regardless, I think we can safely close this. We have no reports of anything similar happening with the official installer, or with others compiling on Windows 10 (with official source and using the standard instructions). We can always revisit if it turns out to be systemic when building Sigil on Windows 10.

**Closed** 2017-10-31 15:43 UTC
