### ISSUE TITLE
Sigil freezes when launching

### ISSUE THREAD

**Issue by jeffovercash** [Sigil-Ebook/Sigil#467] opened 2019-11-15 20:17 UTC
Sigil 9.18 is freezing with preview window undocked and on the secondary monitor.

Steps
1. Launch sigil
2. Undock the preview window
3. Move it to a secondary monitor
4. Close Sigil (writing a new sigil.ini that has the preview window on the other monitor.
5. Launch sigil again (freezes)  The preview window shows, but the main window never shows.

I've attached a bad ini (renamed .txt to be able to attach)  file that does this consistently for me.

[sigil_bad.txt](https://github.com/Sigil-Ebook/Sigil/files/3853016/sigil_bad.txt)

**Comment by dougmassay** [comment] 2019-11-15 20:28
I don't have a capable graphics card, or a second graphics card, or even a second monitor to test multiple monitor configurations. But I do know that there's quite a few people on MobileRead who run Preview undocked on a second monitor.

**Comment by kevinhendricks** [comment] 2019-11-15 20:35
These are Qt bugs.  Not sure if we can even do anything about it.  Perhaps record the fact that Preview was on another monitor somehow, record its geometry and that it was undocked, force it to reattach itself in main Window on close.  And of course reverse all of this on Sigil open somehow.

Or just wait for Qt to fix its bugs.

**Comment by kevinhendricks** [comment] 2019-11-15 20:36
Also your bad ini file shows Sigil main window maximized which causes a whole slew of long standing Qt bugs.  

Can you recreate it without Sigil main window being maximized on close?

**Comment by kevinhendricks** [comment] 2019-11-15 20:38
And to top it off it says Find & Replace was also open, which hits another set of longstanding Qt bugs.

**Comment by jeffovercash** [comment] 2019-11-15 20:40
Closing not maximized had no change in this behavior.

**Comment by dougmassay** [comment] 2019-11-15 20:44
I tell everyone to "fake maximize" Sigil to avoid most of the Qt geometry issues on Windows. Meaning just manually resize Sigil to fill the screen. It avoids having to even deal with all of the hoop-jumping Qt recommends doing for restoring QDockWidgets' geometries in a maximized MainWindow.

**Comment by jeffovercash** [comment] 2019-11-15 20:45
Without the find and replace, it gets further, the initial blank epub is there, but then it freezes.  More of the tool buttons are restored in the preview window (before no tool buttons were being restored).

**Comment by dougmassay** [comment] 2019-11-15 20:46
I assume the secondary monitor has a different resolution than the primary?

**Comment by jeffovercash** [comment] 2019-11-15 20:49
both monitors are 1920x1080

**Comment by dougmassay** [comment] 2019-11-15 20:51
Hmm. Same graphics card or two separate?

**Comment by jeffovercash** [comment] 2019-11-15 20:53
I've taken a good ini and the one that will freeze and taken everything but the toolbar's setting from the bad and put it into the good and nothing else seems to cause this from the bad.  Taking a clean ini and just replacing the toolbars from the bad toolbars line will go back into freezing up on launch.

**Comment by jeffovercash** [comment] 2019-11-15 20:56
Same graphics card - Radeon RX480.  Drivers on it hadn't been updated in a few months.  Sigil has been on this machine since the day it was built about 15 months ago, but since the preview rework I had been just leaving it docked, last time I was working in it a week or two ago I had undocked it while looking at something and left it that way on monitor 2.

**Comment by kevinhendricks** [comment] 2019-11-15 20:56
Hmm so the toolbars is part of it.   Can you take a working ini file with the same toolbars open, close Sigil to save it, and post a good ini file so we can try to narrow down what toolbar entries are causing a problem.

**Comment by jeffovercash** [comment] 2019-11-15 21:09
Yes, but I have to head out for a bit, so will when I return home later.

**Comment by dougmassay** [comment] 2019-11-16 00:41
I stopped after work and bought the cheapest card I could find that could handle multiple displays. If I can find time to install it this weekend (and can get my small treadmill flatscreen unhooked from its wall-mount without breaking it), I might be able to do some testing. They'll be two different resolutions, so maybe I'll be able to experiment with #454 as well.

**Comment by kevinhendricks** [comment] 2019-11-16 04:20
The partial appearance when no Find and Replace is interesting.  One Qt bug recommended a call to QApplication->processEvents(); be added between the geometry restore and the saved state restore.

So if you can recreate this in some way, we can add that and see if that helps.

Also there was a reported mouse position problem when two monitors are used that was fixed in Qt 5.12.5 so we could test to see if that helps.

**Comment by dougmassay** [comment] 2019-11-16 18:34
Well unfortunately, my first experiments with Sigil on multiple displays results in everything working the way it's supposed to. I can't reproduce the problem in this issue, nor can I reproduce the effect in #454 (even with Qt5.12.3).

I've got every toolbar visible and every dockwidget open and Preview pops up on the secondary monitor and the Main Window opens on the primary one.

I tested with Sigil 0.9.18 and with the latest github master.

Using a GeForce GTX 1050 Ti (1600x900 on my Primary-DVI and 1920x1080 on my secondary-HDMI)

Not sure where to go from here.

**Comment by kevinhendricks** [comment] 2019-12-04 22:35
Since no updates, I am closing this as works for me.

**Comment by jeffovercash** [comment] 2019-12-04 23:32
It is still there in 0.9.991.  It was introduced in 0.9.15,  0.9.14 works fine with the same ini file that freezes 0.9.15 and up.  I understand if you can't reproduce not much you can do.

**Comment by kevinhendricks** [comment] 2019-12-04 23:50
Yes, every build after Sigil 0.9.14 uses qtwebengine and not qtwebkit.  So the bug is inside Qt.  And corrupt ini files do break things.  So without the differences between a good ini file and the bad ini file for the same epub and setup, there really is nothing we can do.   The people who run into this tupically have corrupted ini files that were leftover from when we tried to use utf-8 encodings for the ini files but internal support for that documented feature in Qt neglected to mention it was horribly broken.

So if you start with a fresh ini file and can ever recreate this in Sigil 0.9.18 and later, please reopen this report with both good and bad ini files for comparison purposes.

**Comment by jeffovercash** [comment] 2019-12-05 00:06
Started with no ini, launched 0.9.991 (nothing special about 0.9.991, happens back to 0.9.15.  Closed sigil.  Saved off that ini.  Launched again.  undocked the preview window and moved it to the secondary monitor.  Close app.  relaunched and it locks up.

I had mentioned earlier that it was a fresh ini file that reproduced it, so was never a corrupted ini file as I had removed mine at an earlier time when I was trying to figure out what was causing it (the preview on the secondary monitor).

[sigil_ini.zip](https://github.com/Sigil-Ebook/Sigil/files/3924481/sigil_ini.zip)

**Comment by kevinhendricks** [comment] 2019-12-05 04:14
The only real difference is the toolbars section, which makes sense as that is where DockWidget geometry is placed. 

That said,  I attached a second monitor and tried repeating the steps you listed above but no issues and no lockup.  So whatever the problem is, it is related to your specific setup and has issues with Qt QtWebEngine.

Perhaps there is some issue with Qt and your graphics driver? 

Many changes to how DockWidget states are restored have been made since Sigil-0.9.991 since its release.  So I recommend you wait until Sigil 1.0 is released with its new Qt version and some QDockwidget related fixes and see if the issue still happens.

You might also want to try updating your graphics card drivers on your machine if you not already tried that.

**Comment by jeffovercash** [comment] 2019-12-05 05:37
I have updated and tried the newest from AMD from 2 days ago.  Also went back to Sept's Drivers too.  No joy.  Thanks for looking into this.  My preferred way of working is the main window on my main screen and the second monitor shows me how things are looking.  For now I'll stay at 9.14.

I do appreciate the effort to look into this, I know things are not easy without a reproducible on your ned test case.

**Comment by dejudicibus** [comment] 2022-07-22 18:40
I have the same problem with the latest version of Sigil. It looks like Sigil does not like two monitors.

**Comment by dougmassay** [comment] 2022-07-22 18:43
Sigil on 2  monitors works fine for the vast majority of users. We'll need more particulars if we're going to be able to help.

**Comment by kevinhendricks** [comment] 2022-07-22 21:08
More info is needed.  I regularly use Sigil with two monitors with macOS (built-in plus much larger external monitor) with no issues.

So what version of Sigil, what platform, etc?

**Comment by dejudicibus** [comment] 2022-07-23 14:42
OK, I have two monitors:
- a PHILIPS 273V5LHA connected directly to my DELL G5 15 by HDMI to a NVIDIA GeForce RTX 2070
- a PHILIPS 240V5Q connected to a DisplayPort Pluggable UD-3900 by HDMI; the Station is connected to DELL by USB 3.1
The smaller monitor is reasonably served by the Intel UHD Graphics integrated card, the larger by the GeForce card. 
So, two monitors served by different GPUs.

**Comment by kevinhendricks** [comment] 2022-07-23 15:06
Windows?  Linux?  Versions?

**Comment by kevinhendricks** [comment] 2022-07-23 15:07
Exact sequence of steps to recreate the issue?

**Comment by dejudicibus** [comment] 2022-07-23 15:11
Windows 10 Pro ENG latest version, up to date
When I launch Sigil it opens in the secondary monitor, the one served by Intel graphics. It does not respond. Moving it to the primary monitor does not fix the issue.

**Comment by dougmassay** [comment] 2022-07-23 15:22
Sigil should not open on a secondary monitor by default. A prexisting ini file must be telling it to do so.

**Comment by kevinhendricks** [comment] 2022-07-23 16:31
Try renaming the sigil.ini file to save its contents while forcing a new version to be created.

**Comment by dougmassay** [comment] 2022-07-23 16:41
That's definitely the best place to start. Very well could be some corrupted geometry bytearray data in the existing ini.

**Comment by dejudicibus** [comment] 2022-07-23 17:54
> 

Ok I’ll try. Where the INI file is? In the installation folder? Or in AppData?

**Comment by dougmassay** [comment] 2022-07-23 18:05
%LOCALAPPDATA%\sigil-ebook

**Comment by kevinhendricks** [comment] 2022-07-26 15:14
Did renaming sigil.ini fix the issue?

**Comment by dejudicibus** [comment] 2022-07-26 16:31
> Did renaming sigil.ini fix the issue?

Yes. I renamed it to sigil.ini.old, opened Sigil again and now it appears in the main monitor with no problems. 
An ini file was recreated. I gave a look at the new ini file and it is completely different from the old one. Included all shortcuts!

**Comment by dougmassay** [comment] 2022-07-26 16:35
I've never seen a Sigil.ini file that didn't include all keyboard shortcuts. That's so any customizations don't get wiped out by future Sigil installations.

**Comment by dejudicibus** [comment] 2022-07-26 17:44
Yeah, but the shortcuts on the old ini file were different from those in the new one. Anyway, it is not a major problem since I use menus. Thank you for support.

**Closed** 2022-07-26 18:35 UTC
