### ISSUE TITLE
[Bug]: "Reformat HTML" doesn't process MathML tags correctly

### ISSUE THREAD

**Issue by firstrose** [Sigil-Ebook/Sigil#723] opened 2023-08-24 07:21 UTC
### Bug Description

![BNrYF2Hhgl](https://github.com/Sigil-Ebook/Sigil/assets/1551595/a05eb66e-13fb-457a-b1ef-6d00286cb7c0)

MathML tags are not formatted with indentation.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

10.0.19045.3324

### What version of Sigil are you using?

2.0.1

**Comment by kevinhendricks** [comment] 2023-08-24 11:52
Reformat html does not ever change whitespace in a file unless absolutely required.

Are you talking about PrettyPrint?

**Comment by dougmassay** [comment] 2023-08-24 12:18
The choices under Reformat are 1) Mend and 2) Mend and Prettify.

I'm fairly certain we ignore the contents of math tags whenever Prettifying. Probably Mending, too, to be honest.

**Comment by kevinhendricks** [comment] 2023-08-24 12:27
Hmm .... gumbo supports and recognizes mathml tags, and Prettify uses gumbo so it should handle mathml theoretically.  But it might not pretty it up the way it does other code.

I will run a few tests to see.

**Comment by kevinhendricks** [comment] 2023-08-24 15:19
Okay, tested this and Prettify changes no mathml.  

The problem is a mathml tag could be either inline or a block tag so you can not know if it is okay to  insert whitespace or not.

It would really help if you could provide as complete and example as possible of a "before" and "after" for mathml "properly indented" so to speak.

I will look up which if any mathml tags are block level only and so are safe to add whitespace to and which are inline only and should not have any whitespace changed.

But a visual example and test case would certainly help.

**Comment by firstrose** [comment] 2023-08-25 01:28
> Okay, tested this and Prettify changes no mathml.
> 
> The problem is a mathml tag could be either inline or a block tag so you can not know if it is okay to insert whitespace or not.
> 
> It would really help if you could provide as complete as example as possible of a "before" and "after" for mathml "properly indented" so to speak.
> 

OK

It's the problem. I haven't thought about this.
MathML use css "display" to detmine whether it's inline.
`<math display="block">`
I don't know whether Prettify/gumbo support this.

**Comment by kevinhendricks** [comment] 2023-08-29 15:12
Thank you.

For the record I found the following rules about whitespace for mathml in the spec.

```
In MathML, as in XML, "whitespace" means simple spaces, tabs, newlines, or carriage returns, i.e., characters with hexadecimal Unicode codes U+0020, U+0009, U+000A, or U+000D, respectively; see also the discussion of whitespace in Section 2.3 of [XML].

MathML ignores whitespace occurring outside token elements. Non-whitespace characters are not allowed there. Whitespace occurring within the content of token elements , except for <cs>, is normalized as follows. All whitespace at the beginning and end of the content is removed, and whitespace internal to content of the element is collapsed canonically, i.e., each sequence of 1 or more whitespace characters is replaced with one space character (U+0020, sometimes called a blank character).
...
For example, <mo> ( </mo> is equivalent to <mo>(</mo>, and

<mtext>
  Theorem
  1:
</mtext>
is equivalent to <mtext>Theorem 1:</mtext> or <mtext>Theorem&#x20;1:</mtext>.

Authors wishing to encode white space characters at the start or end of the content of a token, or in sequences other than a single space, without having them ignored, must use &nbsp; (U+00A0) or other non-marking characters that are not trimmed. For example, compare the above use of an mtext element with

For whitespace occurring outside the content of the token elements mi, mn, mo, ms, mtext, ci, cn, cs, csymbol and annotation, an mspace element should be used, as opposed to an mtext element containing only whitespace entities.
```

Given the above: all non-token mathml tags can be treated just like "block level" tags in that a return can be added immediately after and then indented.

Do you agree with that interpretation?

**Comment by firstrose** [comment] 2023-08-31 09:07
Fundmentally I agree with you.

But there is one point left to consider.

The spec allows tags being indented, while it's not forbidden to strip "whitespace" and make tags "inline".

MathML can be rendered as a block, or inline. For a bulk of "inline rendered" tags, should them be formatted as "inline"?

For example.

![yeq6vnKl8g](https://github.com/Sigil-Ebook/Sigil/assets/1551595/aae599c6-6bdd-4ff0-8e40-179c172f06ad)

this unformatted code rendered as 

![Klf40NpW6Y](https://github.com/Sigil-Ebook/Sigil/assets/1551595/477ffb3d-d06d-457d-bf84-2b0557379328)

Of course it should be indented after formatting.

While

![GYtRhBu0Du](https://github.com/Sigil-Ebook/Sigil/assets/1551595/7925641f-ad1d-4085-98da-56141f607f08)

gives

![PZ9eVbQ47E](https://github.com/Sigil-Ebook/Sigil/assets/1551595/6455ee55-e8d6-461f-8011-cd4a4893017c)

Should the tags be formatted as "inline", like this?

`<span><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>a</mi><mo>=</mo><mi>b</mi></math> is an equ</span>`

Of course, you decide.

**Comment by kevinhendricks** [comment] 2023-09-01 21:05
The real question in both cases with and without display="block" how it appears if the whitespace spec rules are used by pretty printing.  As long as the result/look on screen stays the same in both cases, we should be good to go.

I will run a few tests.

**Comment by kevinhendricks** [comment] 2023-09-01 21:30
Using this test code:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
  <title></title>
</head>

<body>

<!-- display is block --> 
<p>look <math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mi>a</mi><mo>=</mo><mi>b</mi></math> is an equ.</p>
 
<p>&#160;</p>

<!-- display is block and prettified by spec whitespace rules --> 
<p>look 
    <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
        <mi>a</mi><mo>=</mo><mi>b</mi>
    </math>
 is an equ.</p>

<p>----&#160;----</p>

<!-- no display block -->
<p>look <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>a</mi><mo>=</mo><mi>b</mi></math> is an equ.</p>

<p>&#160;</p>

<!-- no display block but prettified by spec whitespace rules -->
<p>look 
    <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mi>a</mi><mo>=</mo><mi>b</mi>
    </math>
 is an equ.</p>
 
</body>
</html>
```
<img width="303" alt="preview_results" src="https://github.com/Sigil-Ebook/Sigil/assets/8493752/b34c7f26-410c-489a-a863-4839a70cb96b">

**Comment by kevinhendricks** [comment] 2023-09-01 21:33
So pretty printing the mathml code following the spec has no impact on the produced image.  Only the display="block" does and the fact it is there or not does not impact how to prettify the code (if you follow the mathml whitespace rules).

Do you agree?

**Comment by kevinhendricks** [comment] 2023-09-02 15:35
Based on the above, just added support for prettifying mathml code in Sigil.
Closing this as fixed in master.

**Closed by kevinhendricks** 2023-09-02 15:35 UTC
Labels: bug, info
