### ISSUE TITLE
Please Add accelerator keys to the spellcheck dialogue 

### ISSUE THREAD

**Issue by nonentity1001** [Sigil-Ebook/Sigil#164] opened 2015-11-29 21:53 UTC
Could the Filter test box at the top of the Spellcheck list, and the Show All Words, Case-Insensitive Sort and Refresh button at the bottom of the Spellcheck list, have some accelerator keys assigned thereto.

Also a Copy option in the 'error word' context (right click) menu would be handy, I know ctrl/c works, but on occasions an item in the context menu would be more convenient.  In Windows, context menus can be driven from the keyboard with one finger.

![clipboard01](https://cloud.githubusercontent.com/assets/10053529/11460387/b1d2dd30-973f-11e5-953c-b7f9be17a11a.jpg)

For me at least, avoiding use of the mouse is a disability issue - not a convenience or aesthetic preference.

**Comment by kevinhendricks** [comment] 2015-12-06 18:24
@nonentity1001 
I have tried to implement this.  The issue is that the Filter box grabs keyboard focus almost always, so the user has to hit the down arrow to get the Filter box to let go of its focus. 

So assuming the Filter box has keyboard focus, to toggle the Show All Words  or Case-Insensitive Sort checkboxes you would need to do the following:
Down arrow, s
Down arrow, c

Note, the Filter box grabs keyboard focus after each and every checkbox change, because of its design.

Any time you are in the main box, and hit "f" - the Filter box will grab focus.
Any time you are in the main box, and hit "r" - a refresh is done which again causes the Filter box to grab focus.

Not really ideal but the best I can do without redesigning the entire thing to stop the Filter box from regaining focus of the keyboard.

Can you love with that?

**Comment by kevinhendricks** [comment] 2015-12-06 18:43
@nonentity1001 
I think I have better control now and have done hopefully what you want.
These changes should appear in the next release.
So I am closing this, if after the next release, I messed something up, please reopen the issue

**Closed by kevinhendricks** 2015-12-06 18:43 UTC

**Comment by nonentity1001** [comment] 2015-12-10 11:54
Kevin - I've lived without anything 'for ever', so I'll be more than pleased with any improvements 

Thanks a lot - sorry I took so long to respond, asleep at the wheel :)
