### ISSUE TITLE
Assigning shortcuts doesn't detect the proper keys

### ISSUE THREAD

**Issue by terabyte-gc** [Sigil-Ebook/Sigil#474] opened 2019-12-19 22:34 UTC
I was trying to assign the shortcut **`CTRL+ALT+A`** to the button to add blank HTML files. Pressing the 3 mentioned keys on my keyboard results in this shortcut being registered instead though: **`CTRL+ALT+Á`** (note  the accent on the A).

I am using a keyboard with NA/US layout and I have "American Extended" as chosen option in Windows for the language input.

For now I worked around it by using **`CTRL+SHIFT+A`** instead.

**Comment by terabyte-gc** [comment] 2019-12-19 22:34
This is with version 1.0.0 btw.

**Comment by kevinhendricks** [comment] 2019-12-19 23:34
I can not replicate this at all.  Are you trying to assign the same shortcut twice?  What platform?  What shortcut / keyboard managers and third party key assignment software are you using?

**Comment by dougmassay** [comment] 2019-12-19 23:34
I'm not sure what the NA/US keyboard layout is, but Qt has always had issues distinguishing between Ctrl+Alt and AltGr on Windows. Does your keyboard actually have an AltGr key?

**Comment by dougmassay** [comment] 2019-12-19 23:38
EDIT: Nevermind. Clearly North American/US layout. My bad. I'll see if I duplicate it.

**Comment by dougmassay** [comment] 2019-12-20 00:05
The "US" keyboard on Windows 10 behaves normally, but "US International" adds the accented A when using the same keystrokes. It probably confuses Qt. Qt is easily confused.

**Comment by terabyte-gc** [comment] 2019-12-20 00:06
> I can not replicate this at all. Are you trying to assign the same shortcut twice? What platform? What shortcut / keyboard managers and third party key assignment software are you using?

Windows 10 (1803). As for shortcut manager, I simply went into "Edit > Preferences > Keyboard Shortcuts":
![sigil_0 9 18_shortcut_bug](https://user-images.githubusercontent.com/8201711/71219174-7334dc80-22c4-11ea-8ca6-52e160742c0e.png)

The currently assigned shortcut, as I mentioned above, is `CTRL+SHIFT+A`. If I try to press `CTRL+ALT+A` the issue happens. In regards to your Alt/AltGr key, the issue happens with both left or right CTRL/ALT.

===

(I've taken this screenshot on 0.9.18 btw. I've downgraded because of the other image replacement issue I opened.)

**Comment by terabyte-gc** [comment] 2019-12-20 00:07
> The "US" keyboard on Windows 10 behaves normally, but "US International" adds the accented A when using the same keystrokes. It probably confuses Qt. Qt is easily confused.

Ops, we posted at the same time. So it's QT's fault...

As a workaround maybe you could allow to manually write up/edit the shortcut or something?

**Comment by dougmassay** [comment] 2019-12-20 00:27
Qt's history is littered with bugs related to US International keyboard breakages. It breaks, they "fix" it, it breaks again.

You can always manually edit the Sigil.ini file and add the Ctrl+Shift+A keysequence for MainWindow.NewHTMLFile while we look into it. You'll need to do it when Sigil isn't open.

**Comment by dougmassay** [comment] 2019-12-20 00:51
The puzzling part for me is that after manually adding the Ctrl+Alt+A key sequence in Sigil ini prefs file, MainWindow seems to recognize the keystrokes as matching the Ctrl+Alt+A sequence (and creates the new blank file). Which begs the question: why does the Keyboard Shortcut Manager widget interpret the same keystrokes as something else?

**Comment by terabyte-gc** [comment] 2019-12-20 00:55
> The puzzling part for me is that after manually adding the Ctrl+Alt+A key sequence in Sigil ini prefs file, MainWindow seems to recognize the keystrokes as matching the Ctrl+Alt+A sequence (and creates the new blank file). Which begs the question: why does the Keyboard Shortcut Manager widget interpret the same keystrokes as something else?

That's a million dollar question. As for editing Sigil.ini as a workaround, I'll do that then. Thanks.

**Comment by kevinhendricks** [comment] 2019-12-21 03:28
I think this is happening because the Qt keymapper Windows code will map a  left Ctrl  and a right Menu or Alt to be an AltGr key.

So would you please try once once again but this time use the right Ctrl key when forming the shortcut and let us know if that has an impact.  

So using Qt's Window keymapper code a key sequence of  a left Ctrl + right Alt + A  will be interpreted as the key sequence AltGr + A which is the Aacute key that I think you said you were seeing.

This is all just a guess from eyeballing the Windows keymapper code in Qt, but it seems to fit what you reported.  It only does this for US International keyboard layouts which need an AltGr functionality.

**Comment by terabyte-gc** [comment] 2019-12-21 03:53
> I think this is happening because the Qt keymapper Windows code will map a left Ctrl and a right Menu (or right Alt) to be an AltGr key.
> 
> So would you please try once once again but this time use the right Ctrl key when forming the shortcut and let us know if that has an impact.
> 
> So based on Qt's Window keymapper code, a key sequence of a left Ctrl + right Alt + A will be interpreted as the key sequence AltGr + A which is the Aacute key that I think you said you were seeing.
> 
> This is all just a guess from eyeballing the Windows keymapper code in Qt, but it seems to fit what you reported. It only does this for US International keyboard layouts which need an AltGr functionality.

I already mentioned it in my reply above, I tried all left/right combinations. No change:
> In regards to your Alt/AltGr key, the issue happens with both left or right CTRL/ALT.

**Comment by BeckyDTP** [comment] 2019-12-21 09:29
Just for clarification:
Because I'm from Poland, most users use the Polish keyboard layout.
_Polish (programmers)_ keyboard layout obviously uses AltGr (like as _US International_).
To get the letter "ą" press AltGr+a, to letter "ę" press AltGr+e etc.

In Windows, AltGr has *always* been the equivalent of LEFT Ctrl + LEFT Alt (anyway, pressing these two buttons simultaneously is simply easier with your left hand).
Therefore, in many programs (including the default Sigil), users from Poland must remove shortcuts that block the use of Polish diacritics.

In Sigil it is the keyboard shortcut "Open the Clip Editor" (Ctrl+Alt+C), which is equivalent to AltGr+C=ć.

This "issue" is not really an "issue". This is the normal behavior of Sigil and hundreds (!) Of other programs.

This is *sometimes* to be bypassed (I've seen different ways in the last 20 years), but my programming knowledge is too low to describe the problem. IMHO has no reasonable solution. If you want I can search the web for solutions, but if Qt doesn't allow you to use some keyboard hooks, which is probably not a good idea.

In the "Keyboard Shortcuts" window, if I press LEFTCtrl+LEFTAlt+A I will also get **Ctrl+Alt+Ą** and it was *always*. Polish (and not only) users who have been using AltGr for years have learned that they cannot assign any of the program functions (not just Sigil!) to shortcuts that they use to enter diacritics or other characters from the keyboard.

For years, I wrote to programmers asking them to change the shortcut if it was hardcoded. In the case of Sigil, users have the option of configuring keyboard shortcuts, so the problem practically does not exist.

**Comment by kevinhendricks** [comment] 2019-12-21 12:56
@BeckyDTP 
Specifically when assigning shortcuts in Sigil's Preferences in Keyboard Shortcuts, can you use the Right Ctrl and Alt (or Menu) buttons and C and will it generate a different Shortcut than the normal (both Left Ctrl and Alt and C)?

The OP says they tried all combinations with the same result.  Does that same issue happen with your Polish keyboard as well?

**Comment by dougmassay** [comment] 2019-12-21 14:00
In my testing with the US International Keyboard layout on Windows 10 - English (United States) system language, it makes no difference which alt or which ctrl is used. All combinations of CTRL+ALT+A produces CTRL+ALT+Á in the shortcut manager.

One interesting thing to note is that with the English International Keyboard Layout, R_ALT+ A _also_ assumes the CTRL modifier was pressed. Meaning it produces CTRL+ALT+Á (even though a CTRL key was never depressed.

It is my belief that with the US International keyboard in Windows 10, Qt is assigning the right ALT  button as the AltGr key. Which was always my understanding of what most international layouts did with physical US Layout keyboards (it's closest to where the real AltGr key is on physical international keyboards).

The question then becomes whether or not this is new Qt behavior. And the answer is no. Sigil 0.9.18 (with Qt5.12.3) produces the exact same results with the US International keyboard layout as Sigil 1.0.0 (with Qt5.12.6) does. I've done no testing on Windows 7 or 8.

**Comment by dougmassay** [comment] 2019-12-21 14:11
@kevinhendricks : any way to output the key sequence being registered in MainWindow when a shortcut is being activated? I'm curious why typing CTRL+ALT+A activates the correct shortcut when it was manually set up in the Sigil.ini file.

My thinking is that maybe Qt is perfectly capable of mapping the correct native keystrokes to the right shortcut (regardless of any diacritic marks). Maybe it's a failure of Sigil's SettingsStore to be able to store the utf-8 A acute. I guess what I'm suggesting is; could we eliminate this problem by modifying KeyboardShortcutsWidget toString call to remove diacritics?

**Comment by kevinhendricks** [comment] 2019-12-21 14:57
Yes, this is all controlled by the Windows specific mapping code in Qt.  It determines both the  event->key() and event->text().    What we are seeing is not a bug in Sigil but instead an issue with Qt's mapping of key press events to keys.

Since we have access to the nativeScan code and nativeVirtualKey, and nativeModifier, we could:

1. if Windows
2. see if event->key() or event->text() currently returns a diacritic (assuming we have a list of diacritics that should not be used)
3. either refuse to create the shortcut or alternatively convert the shortcut to be the equivalent key without the Diacritic (if we have a way to map diacritic to closest non-diacritic alternative).

So that would be doable.  To get started, we would need a way to detect diacritics from unicode character values from the event->text() value, and then determine their non-diacritic equivalent.

We should at least look into doing this as a way to prevent diacritics from being used as shortcuts.

Either way, this is not a Sigil bug, it is a Qt bug in generating a diacritic event->text() under some keyboard layouts on Windows.

**Comment by dougmassay** [comment] 2019-12-21 15:01
Perhaps an easier explanation of my theory on this:

Why should we care that different keyboard layouts might map different characters to the same keystrokes when setting shortcuts in Sigil? We're mapping shortcuts to keystrokes, not to actual characters, right?

I think you were posting while I was writing this.

**Comment by dougmassay** [comment] 2019-12-21 15:06
The normalized() function should get us in the ballpark, right? Or even perhaps using the nativeVirtualKey value converted to ascii?

**Comment by kevinhendricks** [comment] 2019-12-21 16:04
Okay, I pushed changes to use PortableText when converting a key sequence to a string as you suggested.

Hopefully this will prove helpful.

**Comment by dougmassay** [comment] 2019-12-21 16:23
Didn't seem to make any difference. But for what it's worth: calibre behaves the exact same way Sigil does with the ENG International keyboard set on Windows 10. It registers and sets CTRL+ALT+Á, which promptly doesn't trigger the desired action it was mapped to. Not sure we should even worry about it at this point. *shrug*

**Comment by dougmassay** [comment] 2019-12-21 16:33
Especially if they don't actually HAVE an international keyboard.

**Comment by kevinhendricks** [comment] 2019-12-21 16:50
Agreed.  This is a Qt Windows specific bug that only impacts some keyboard layouts.  And us trying to work around it in any way is just a recipe for creating more bugs that are going to hit people with international keyboards. 

For shortcut purposes, on Windows the native virtual key plus modifiers is probably what should be returned here but since it is being mapped to a Diacritic and not returned as a base key plus modifiers, there is really nothing we can do about it without knowing the true keyboard and its mapping that was used. 

So I am closing this as not a bug in Sigil.  If the OP feels strongly enough about it they can file a bug directly with Qt when using the US International Keyboard under Windows.

**Closed by kevinhendricks** 2019-12-21 16:50 UTC

**Comment by BeckyDTP** [comment] 2019-12-21 16:53
I write back a little late, but I have to dress the Christmas tree.

Of course left Ctrl = right Ctrl, I only mentioned the ease of pressing the key combination (Ctrl + Alt + A) with the left hand.

As I wrote – there is no simple solution and users from AltGr should get used to it. This is certainly not problem in Sigil.

**Comment by BeckyDTP** [comment] 2020-10-20 18:18
Problem **partially** can be solved by run sigil with parameters:
`Sigil.exe -platform windows:altgr`

This does not fix the problem with assigning shortcuts, but _AltGr+something_, e.g. when editing the code, inserts the correct diacritics, and does not call the Sigil functions that are assigned to the _Ctrl+Alt+something_ keyboard shortcuts.
Maybe it's even worth adding to the documentation?

As for the shortcuts problem, it is possible that in Qt 5.12[.10] it was fixed by this patch:
https://codereview.qt-project.org/c/qt/qtwebengine/+/306722
Unfortunately, I have no way to check it.
(Let me remind you that this problem only affects international keyboards on Windows.)
