### ISSUE TITLE
Splitting of files with anchors including file name do not correctly reassign targets

### ISSUE THREAD

**Issue by gennaios** [Sigil-Ebook/Sigil#450] opened 2019-08-10 23:45 UTC
Hello,

I haven’t tried reproducing this but I have encountered it multiple times. Let’s say a file has anchors referencing itself and the anchors include the file name, e.g., this_file.xhtml#anchor1. When such files are split, the anchors are not correctly parsed. From what I remember, they refer either to the original file name or the first of the splits. I can try to create a reproducible case if needed. Unsure if it happens all the time in such circumstances but it has happened to me fairly often.

**Comment by dougmassay** [comment] 2019-08-10 23:56
That typically only happens if the warning message that splitting files with fragment urls with missing targets might cause problems is ignored. The warning message was specifically added because there are certain conditions that can't be properly accommodated by Sigil's splitting routines. Namely: if there is no element with an id of "anchor1" in "this_file.xhtml" the warning will pop. If the warnin g is ignored, paths will not be correctly updated.

**Comment by gennaios** [comment] 2019-08-11 00:12
I am using the newest version of Sigil and have kept up with versions. It’s been happening perhaps most of the time in the last year, perhaps not as long, perhaps longer.

I get no warning or error message, and all anchors exist. For example, a file may have dozens of footnotes at the end, all of them correct, and anchors are not rewritten after the split. Now, for any file I do split, I check first for such anchors and edit them to `… href=“#…”`, removing the file name, and all behaves as intended.

**Comment by dougmassay** [comment] 2019-08-11 00:20
We'd love to have a reproduceable sample where existing valid/working urls aren't being properly updated when splitting (without being warned of the possibility beforehand). This is the first such report since the the warning message was added. If something is falling through the cracks, we'd love to fix it. But we have to be able reproduce it first.

**Comment by kevinhendricks** [comment] 2019-08-11 02:23
To be clear, is this what you are describing?

you have a single xhtml  say with filename "file1.xhtml" and it has an internal link to a target "#here" in that same file but the href for the anchor is currently written as "file1.xhtml#here" instead of just "#here".

Then when you split this file between the href anchor and the link target, the href does not get properly updated.  

Is that what you are saying?

**Comment by kevinhendricks** [comment] 2019-08-11 02:34
Also from reading the href <a> html spec, when a href is internal to that file, only a fragment identifier is used, not the name of the file (since it is in the same file).

 hrefs like that are technically not correct, but may still work.  So it is a good idea to search for the name of the file inside the file correcting any improperly written local hrefs, before attempting any split.

If this is what is going on we should be able to include tests for this in our warning for splitting.

**Comment by gennaios** [comment] 2019-08-11 03:07
Hello Kevin,

Yes that is correct, anchors internal to the file are named with the file name as you cited. It’s happened perhaps at least 4 or 5 times, always commercial ePubs, often academic titles. Some publishers perhaps have a habit of writing their epubs as such, with all internal files being as such. Thus it would be nice and ideal to automatically correct and handle such cases.

Not in front of a computer but I will try to create a reproducible case unless you think such would happen as such since such a case isn’t currently handled.

**Comment by kevinhendricks** [comment] 2019-08-11 15:47
Just to be clear,  using the name of the current file for an internal link local to that file is NOT correct according to the spec.  So please file a bug report with whatever software you have that creates internal links like that.

We will work on either improving our warning message to point them out so the user can fix them, or habdling them as a special case in the split code.

**Comment by kevinhendricks** [comment] 2019-08-11 16:09
I tried the following test file "Section0001.xhtml"  in an epub and used Sigil split at markers to split the file but it perfectly split and updated the link properly.

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
<title></title>
</head>
<body>
<p>&#160;</p>
<p><a href="Section0001.xhtml#here">a link</a></p>
<p>this is a line of text</p>
<p>this is a line of text</p>
<p>this is a line of text</p>
<p>this is a line of text</p>
<p>this is a line of text</p>
<p>this is a line of text</p>
<hr class="sigil_split_marker"/>
<p>this is a line of text</p>
<p>this is a line of text</p>
<p>this is a line of text</p>
<p>this is a line of text</p>
<p>this is a line of text</p>
<p>this is a line of text</p>
<p id="here">target of link</p>
</body>
</html>
```

So please either edit this test case to make the error happen or create a test case epub that shows the issue so that we can investigate.

As it stands, I can not recreate the issue you are seeing.

**Comment by dougmassay** [comment] 2019-08-11 16:22
I tried the same thing. I even created a back-link from the target id to the origin (with another fragment) and both links were correctly adjusted after the split. I tried with both the "split at cursor" and "split at markers" method.

So if there's something falling through the cracks of our split procedures, it's not this exact scenario. There has to be something else in play.

So far, the only way I can get messed up links on a split is by ignoring the warning message about the target of an href not existing and going ahead with the split.

**Comment by kevinhendricks** [comment] 2019-08-11 16:38
I wonder if the case of the filename could be an issue in play?  Anchor hrefs are fully case sensitive but the filename on a case insensitive platform may then appear different from how it was written in the href.   What platform are you using?

**Comment by gennaios** [comment] 2019-08-11 18:21
I also tried a simple test case with one split marker and wasn’t able to reproduce it.

I am using macOS. When it happens, it’s when before I add an ePub to my reader, I check for abnormally large files and split them to keep them around 200k or so for performance. My method is to insert multiple split markers. I do have a commercial ePub where it is reproducible. If that is ok, if there’s a way to send it to you without a public link, I’ll pass it on. Or later in the week I can experiment more.

**Comment by dougmassay** [comment] 2019-08-11 18:36
If the epub's not huge, you should be able to attach it to a comment here (drag and drop). Just post it with the exact steps to reproduce the issue. We'll delete the attachment once we have it.

**Comment by kevinhendricks** [comment] 2019-08-11 18:38
If you use Mobileread (www.mobileread.com) you can pm (personal mail) either "KevinH" or "DiapDealer" with a link and we can grab it.  Otherwise there are plugins like the Borkify plugin that can be used to replace all text in an epub but leave the basic tags.  Once borified, you can rename it and zip it up and attach it here.  If you do decide to use borkify, please make sure it borkifies the entire book so no copyright is being impinged.

**Comment by gennaios** [comment] 2019-08-11 18:49
Here is the ePub:

https://www.dropbox.com/s/1o2cmh0oxc9t8pa/test.epub?dl=0

I don’t have much of a chance to be in front of a computer today. Didn’t have a chance to Borkify. Split markers are already inserted so the only step is to split at markers. I also didn’t have a chance to look much at the ePub except to verify that links and splitting are as mentioned and it does pass epubcheck before the split.

**Comment by kevinhendricks** [comment] 2019-08-11 19:02
I grabbed it and can send it to my co-developer, so please feel free to remove the file from your dropbox.

**Comment by dougmassay** [comment] 2019-08-11 19:08
Can we get a specific link that is broken as a result of splitting at marks? There's a lot of links there to try and verify. Also, I'm not seeing any hrefs of the type that were originally discussed: "filename.xhtml#frag" all hrefs seem fully relative to the epub's structure rather than simply the name of the current file.

**Comment by dougmassay** [comment] 2019-08-11 19:38
Never mind. Using Reports, I can see quite a few examples of targets not existing after the split where before, all targets existed.

**Comment by kevinhendricks** [comment] 2019-08-11 19:39
I have tracked one down.  Here is the relevant info:

In part0008.xhtml

At Line 999

<p>Brahmā himself divides it into four groups,
<a id="n0346" href="../Text/part0008.xhtml#actrade-9780190279172-chapter-1-note-192">
<sup>*</sup></a> and then each creature goes its own way, its conduct 
dictated by its own karma.</p>

At Line 1313
<p class="note2" id="actrade-9780190279172-chapter-1-note-192">
<a href="../Text/part0008.xhtml#n0346">*</a> These four groups 
are the four social classes.</p>

All split markers occur *before* line 999.
It splits at lines: 179, 290, 474, 699, 978

So it ends up with the following parts:

part0008      up to line 179
part0008_0001 from line 179 to 290
part0008_0002 from line 290 to 474
part0008_0003 from line 474 to 699
part0008_0004 from line 699 to 978
part0008_0005 from line 978 - end

After splitting the following link was broken (the first broken one I found in the Reports Links)

part0008_0005.xhtml line 30 id n0346 * part0008.xhtml actrade-9780190279172-chapter-1-note-192

That link target does not exist as it should have been updated to part0008_0005.xhtml but because a filename was inserted it never gets updated.

So the target file part0008.xhtml exists but needed to be updated to part0008_0005.xhtml but
that did not happen.

**Comment by kevinhendricks** [comment] 2019-08-11 19:43
So I think we need to check if internal links use a filename in the href, and if so warn the user to remove them before attempting a split since they are not correct according to the spec.  Otherwise there was no way of telling which of the part0008.xhtml pieces it came from.

**Comment by kevinhendricks** [comment] 2019-08-11 19:49
The problem is gumbo/mend does not know the name of its own file as the file contents are passed in, not a path to the file.  So we would have to pass along information on all files in the epub to mend() for it to know what to do.

I think we just check and warn people that their links are messed up.

**Comment by kevinhendricks** [comment] 2019-08-11 19:53
Of fix them in the split code before starting the split?  Would that work?

**Comment by dougmassay** [comment] 2019-08-11 19:54
I'm still not quite following. We've already shown that sigil is capable of updating hrefs that have the current filename in them, so why is it breaking here?

There's just too many links here with inordinately long fragment/id names. Can we possibly reduce this to a simple test case scenario that I can more easily get my head around?

**Comment by kevinhendricks** [comment] 2019-08-11 19:59
I will try adjusting our simple test case above to see if I can create something simpler.

**Comment by kevinhendricks** [comment] 2019-08-11 20:04
Just e-mailed it to you.

**Comment by kevinhendricks** [comment] 2019-08-11 20:11
[test_split2.epub.zip](https://github.com/Sigil-Ebook/Sigil/files/3490396/test_split2.epub.zip)

**Comment by kevinhendricks** [comment] 2019-08-11 20:11
An even simpler test case I added above.

**Comment by kevinhendricks** [comment] 2019-08-11 20:12
Note, that removing the filename from the internal link href's is enough for our updating routines to work properly.

**Comment by kevinhendricks** [comment] 2019-08-11 20:22
I think it is breaking because the source to the link is not in the original file and instead in a split off section.  But that is just a guess.

**Comment by dougmassay** [comment] 2019-08-11 20:33
So it's WHERE the split occurs that's the real factor, here? I ask because splitting _between_ the link and the target results in the href being updated correctly in your test_split2 epub.

So it's not enough that the filename is a part of the href. The filename has to be a part an href that's going to be _moved_ to a file that's created by the split operation for there to be an issue.

**Comment by dougmassay** [comment] 2019-08-11 20:39
If that's the case, it's going to be hard to nail down when exactly to warn a user. If we go with anytime the current filename is included in an href, then we could be warning the user about a split that won't cause any issues.

**Comment by kevinhendricks** [comment] 2019-08-11 20:41
But not one that is technically correct.

That said, we only look at the anchor id and it exists in the same file as the link to it and then decide not to update anything.  At this point we need to fix these links too.

I think we may be able to handle these cases in SourceUpdates AnchorUpdates.

I am going to add some debug statements in anchor updates

**Comment by dougmassay** [comment] 2019-08-11 20:49
But they would be technically correct after the split.  :)

But I get what you're saying. My only fear is that this technically improper linking is probably more prevalent in commercial code than we think. I like the notion of maybe being able to address it with SourceUpdates AnchorUpdates if possible.

**Comment by kevinhendricks** [comment] 2019-08-11 20:56
Okay so we fix it there.

Here is the debug output for our test2_split.epub from the AnchorUpdates.cpp source file:

Debug: in UpdateAnchorsInOneFile
Debug: in UpdateAnchorsInOneFile
Debug: ID_locations QHash(("here", "Section0001_0001.xhtml"))
Debug: ID_locations QHash(("here", "Section0001_0001.xhtml"))
Debug: fragment_id "here"
Debug: file_id "Section0001_0001.xhtml"
Debug: resource_filename "Section0001_0001.xhtml"

So since the file_id equals the resource_filename in that routine, it decides to leave that href alone (which would work just fine if the damn href did not have a Section00001.xhtml#here.

So we need to add a second test to make sure that if file_id equals resource_filename but do not equal the href part BEFORE the fragment, we still update this link by removing the part before the fragment.

What do you think?

**Comment by kevinhendricks** [comment] 2019-08-11 21:13
Okay, I pushed the qdebug additions along with a potential fix.  It seems to work but I am very worried that it may have unexpected issues.

So we should probably really test this and see if it fixes all cases without breaking anything.

And only then remove the debug output.

**Comment by gennaios** [comment] 2019-08-11 21:37
Thank you very much. If you think there are potential issues, I wonder if another approach may be more robust. Since base hrefs are out of spec, is there any harm to check for such links and correct them upon open and save, such that even without splitting, links are auto-corrected?

Indeed as Doug mentioned, I think this may be fairly prevalent in commercial EPUBs, at least among some publishers that seem to do this with all their code.

**Comment by kevinhendricks** [comment] 2019-08-11 21:48
Let's test the potential fix we already have.  If that works with no issues, we should be good to go as the href's themselves seem to work just fine even though not to "spec".  I tried the non-spec href's on all browsers I have and they all worked just fine.  So Sigil should handle them too.

That said, a plugin could do the "repair" quite easily too.

**Comment by dougmassay** [comment] 2019-08-11 21:55
I can get some test versions out to some of my testers and tell them to give it a hard workout on splitting/merging.

@gennaios I'll give you the option to test the potential fix if you like. You can download a Windows installer with the proposed fix from: https://ci.appveyor.com/project/Sigil-Ebook/sigil/builds/26622421/artifacts . Perfectly understandable if you don't want to be a guinea-pig, though.

**Comment by dougmassay** [comment] 2019-08-11 21:57
Oops. Never mind. I forgot you already mentioned you were on a Mac.

**Comment by gennaios** [comment] 2019-08-11 22:05
I don’t mind testing it out. I think I should be able to grab the one changed file and patch my install of the current version.

**Comment by gennaios** [comment] 2019-08-11 22:58
I had thought it might have been a Python file I could quickly replace but had forgotten that it was C++ and requires rebuilding. I have the tools though not all the pre-requisites already setup. If it’s not too much trouble, a test build would be appreciated. Though perhaps you have enough testers so either way.

**Comment by kevinhendricks** [comment] 2019-08-11 23:01
We do have an appveyor build for macOS that is unsigned and is in tar.xz format.  DiapDealer is that doable?

**Comment by dougmassay** [comment] 2019-08-11 23:05
Yes. The link is to my personal gdrive, but as long as there's not 100's of people downloading it a day, there's no problem. And even then it's just a matter of waiting until the daily download limit resets. I'll edit this comment with the download link to the correct archive in a moment.

**Comment by gennaios** [comment] 2019-08-11 23:09
Great. Thank you. I’ll try it out over the next few days.

**Comment by gennaios** [comment] 2019-08-13 01:08
Looking through ~150 EPUBs, found 10 that have links as such, EPUB 2 and 3. No issues with splits, but it seems in every case of EPUB2, after re-merging, and sometimes merging with a different file, the NCX isn't updated and lists the no longer existing split files. Unsure if it's related or something else.

If you're unable to reproduce, I'll see if I can look at it more closely later in the week though I might not have the chance.

Other minor issue is that for EPUB3, if there's an .NCX for backwards compatibility, it isn't auto-updated though perhaps that is as intended.

Some publishers I've found that tend to have such links: Columbia, Hackett, O'Reilly, Oxford, Routledge, and Wiley.

**Comment by kevinhendricks** [comment] 2019-08-13 18:15
Updating the ncx after a merge has never been implemented in Sigil.  I will add that to out todo list.  In those instances the user can (re-) generate the toc to correct the ncx.

Yes under epub3, the ncx is never updated.  Since the ncx is optional, the user can generate an ncx from their nav before a final save using a epub3 specific menu item.

So it appears from your test results, the change we made to handle non-spec internal links does not have any bad side effects.

Please note, some browsers treat links with filenames (even the current one) as a need to "load" the page including either cache or network access.  For internal links without a filename, a simple scrollto id is used.  This is true in both Webkit and WebEngine.

So from a performance perspective, not adding a filename for an internal link is a big win.

**Comment by kevinhendricks** [comment] 2019-08-13 18:15
So closing this as now fixed in master.

**Closed by kevinhendricks** 2019-08-13 18:15 UTC

**Comment by gennaios** [comment] 2019-08-13 19:38
> Updating the ncx after a merge has never been implemented in Sigil. I will add that to out todo list. In those instances the user can (re-) generate the toc to correct the ncx.

Glad it is on the todo list. It is not always possible to regenerate the NCX (from H1–H6 headers). Perhaps more frequent than this issue, in commercial code, I often find either: 1. headers were generated from whatever app they used (InDesign?) and the header entities themselves are normal paragraphs, thus one would need to convert all such paragraphs to headers. 2. headers can be relied upon to be logically correct, meaning H1's can be H2's in code mixed in with other H2s or some other weird combination.

In longer EPUBs with .NCXs with dozens or sometimes 200+ entries, it would be nice to someday correctly handle any edits such as merges. Though I don't recall often merging commercial EPUBs, mainly only my own.

Indeed, performance I imagined would be better when internal links lack a filename. I might look into making a plugin sometime to correct such things.

Thank you again for the help. Indeed it seems to work great w/o issues.

**Comment by kevinhendricks** [comment] 2019-08-14 18:50
FWIW,
Just finished implementing updating of the ncx after a merge.  After simple testing, it appears to work.  This change will appear in our next release.

**Comment by gennaios** [comment] 2019-08-14 21:49
Terrific. That helps very much. Thank you.
