### ISSUE TITLE
Book View and Code View

### ISSUE THREAD

**Issue by worlock100** [Sigil-Ebook/Sigil#455] opened 2019-09-07 02:10 UTC
My previous version was "Sigil-0.9.14-Windows-x64-Setup.exe" now i upgraded to "Sigil-0.9.18-Windows-x64-Setup.exe". I realized that I no longer have the options "Book View" and "Code View", I use them.

**Comment by kevinhendricks** [comment] 2019-09-07 02:24
Closing this issue as not a bug.  BookView was removed from Sigil.  Use the Views menu in Sigil to enable enable the Preview Window so that you can edit the html in CodeView and see the results immediately in the Preview Window.   Simple WYSIWYG editing has been moved to our new PageEdit app which can be launched from Sigil.

Please read the Sigil Release Notes, Sigil Wiki, and our Mobileread Sigil User forum for the discussion.

**Closed by kevinhendricks** 2019-09-07 02:24 UTC

**Comment by N0N0** [comment] 2023-11-16 17:34
Sorry to say but I also made an update from 0.9.13 to 2.0.2 and I had to revert it back to 0.9.13.

Preview Mode was awfull slow, global search over all HTML-Files did not work, only within one file, regardless of the search setttings.

**Comment by dougmassay** [comment] 2023-11-16 17:44
Please don't bump ancient, resolved issues just to offer "me too" opinions.

**Comment by kevinhendricks** [comment] 2023-11-16 19:34
And that means you got the search settings wrong as these were changed with the move to pcre2 and do nit understand how to do searches as that has changed.
