### ISSUE TITLE
It is not possible to scroll the Settings dialog

### ISSUE THREAD

**Issue by jony0008** [Sigil-Ebook/Sigil#483] opened 2019-12-28 18:07 UTC
It is not possible to scroll down to OK in the Settings dialog when the screen is smaller than the dialog.
![Skärmbild från 2019-12-28 19-04-24](https://user-images.githubusercontent.com/23194385/71547827-460fba80-29a5-11ea-9d99-23889e8c9fbf.png)

**Comment by kevinhendricks** [comment] 2019-12-28 18:55
What screen?  What platform are you using? What version of Sigil?  This dialog was designed to fit on 800x 600 screens.

**Comment by jony0008** [comment] 2019-12-28 20:13
@kevinhendricks The Preferences window in the picture. I am using Debian Sid with Sigil 1.0.0. My screen is 1366x768.

**Comment by dougmassay** [comment] 2019-12-28 20:39
The settings dialog should be resizable regardless. Resize it and it will retain its size

**Comment by jony0008** [comment] 2019-12-28 20:46
Not possible to do that in Gnome 3, when I try to make the dialog full screen it will just center it, I still can't click OK.

**Comment by kevinhendricks** [comment] 2019-12-28 20:53
Which Qt version?    Please look for and find your sigil.ini file and try renaming it to something else.  The previously saved Preferences dialog saved geometry should revert.  Does that impact what you are seeing?

**Comment by jony0008** [comment] 2019-12-28 21:04
Qt version 5.12.5. I renamed the sigil.ini file but that didn't help.

**Comment by kevinhendricks** [comment] 2019-12-28 21:33
That is strange.  I will look into it.

**Comment by dougmassay** [comment] 2019-12-28 21:42
All preference pages or only the plugins page?

**Comment by jony0008** [comment] 2019-12-28 21:46
The pages that don't fit on the screen. That is all preference pages.

**Comment by dougmassay** [comment] 2019-12-28 21:51
I'm not asking whether you can scroll on any of the preferences pages. Scrollbars are disabled for all of them by design. I'm asking if the Plugins preference page is the only one where the OK button is unavailable (since that's the one you've chosen for your screenshot), or if the OK button is available on others.

**Comment by jony0008** [comment] 2019-12-28 21:53
I would have to be able to scroll down on all preference pages to see the OK button.

**Comment by dougmassay** [comment] 2019-12-28 22:08
Thank you. This is the case even the very first time you open the preferences dialog after renaming the Sigil.ini file (before changing to any other preference page)?

**Comment by jony0008** [comment] 2019-12-28 22:10
Yes. No problem.

**Comment by dougmassay** [comment] 2019-12-28 22:22
Are you using qt5ct with the system qt5ct theme plugin by any chance? Any dpi-scaling being applied? I'm basically trying to figure out why a dialog designed to fit on an 800x600 screen won't fit within the resolution you say your display is set at.

**Comment by kevinhendricks** [comment] 2019-12-29 00:15
FWIW, I took a few measurements of the smallest Preferences Dialog I could create (by manually resizing) and it was much larger than the size specified in the .ui file.

I do think we probably either need to make the individual Preference dialogs scrollable or reorganize them to take up much smaller vertical space.  The biggest height users are the Appearance, General, and Plugin settings.

**Comment by kevinhendricks** [comment] 2019-12-29 15:46
Another option would be to split the too large preferences dialogs into smaller more focused dialogs and try to restore the original 800 x 600 size limit.  

We may need to do that anyway, as I think we will need a separate Appearances dialog for light mode and a second for dark mode so that users can override the main settings and we do not need to compromise on colors that only look good under both light and dark.

**Comment by kevinhendricks** [comment] 2020-01-01 17:53
Okay, I have tweaked all of the individual Preference apnes using Designer.app to be under 600 (width) x 588 (height).

Once the Preference QListWidget is added in all Preference Dialogs should now be under 800 x 700  so they should fit on very low res screens again.

Closing this as fixed in master.  Please reopen if you still have difficulties after the next release.

**Closed by kevinhendricks** 2020-01-01 17:53 UTC
