### ISSUE TITLE
toc.ncx not updated by Generate Table Of Contents

### ISSUE THREAD

**Issue by derrickoswald** [Sigil-Ebook/Sigil#380] opened 2018-09-11 20:48 UTC
Sigil 0.9.10
Qt 5.5.1
Linux 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce:
Open the attached epub.
Open the toc.ncx. It has the default navPoint.
Use the command Tools - Table Of Contents - Generate Table Of Contents
Click OK.
The status response indicates:

> Table Of Contents generated.

However, the noc.tcx file is not updated.

### Expected outcome:
The noc.tcx file would be rewritten with the new heading text.
From the documentation:
[test.zip](https://github.com/Sigil-Ebook/Sigil/files/2372637/test.zip)

> An EPUB Table of Contents is stored in the toc.ncx file listed in the Book Browser.

> Generating the TOC automatically will overwrite any existing TOC in the toc.ncx file.

**Comment by dougmassay** [comment] 2018-09-11 20:55
If it's an EPUB3, then that's the expected behavior. The ncx is not a required element if epub3. If you'd like to keep the ncx updated for backward compatibility, then use the epub3 tools (from tools menu) to generate the ncx from the nav document.

**Comment by dougmassay** [comment] 2018-09-11 21:28
In EPUB3 the NAV document IS the Table Of Contents in EPUB2, it is the toc.ncx that is the Table of Contents. Hence all of Sigil's ToC editing/generating features (with the exception of the "Create HTML Table of Contents" tool) affect the required Table of Contents document for the spec of the current EPUB version you're working on.

Closing this issue since your attachment is indeed an EPUB3 and Sigil's ToC editing/generating features are updating the required NAV document as intended. If you want the optional NCX updated as well, manually run Tools->Epub3 Tools->Generate NCX from NAV.

**Closed by dougmassay** 2018-09-11 21:28 UTC
