### ISSUE TITLE
Ctrl+b

### ISSUE THREAD

**Issue by SmilePlz** [Sigil-Ebook/Sigil#368] opened 2018-07-05 16:29 UTC
Hi I'm using version 0.9.9
in the mode "book view" when I press Ctrl + B inserts \<span style = "font-weight: bold;"\> \</ span\>.
in the mode "code view" when I press Ctrl + B inserts \<b\> \</ b\>.
in version 0.9.5 all is well. how to fix it?

**Comment by kevinhendricks** [comment] 2018-07-05 16:42
BookView is really live editing a html page dom node tree and Qt Webkit was inserting a deprecated tag for one of the styles in BookView.  The only way to make Qt actually correct/proper xhtml that would pass epubcheck, was to convert it to use inline styles for all styling.

In CodeView, we, not Qt, control the edit process and use the correct tags.  Both modes now implement valid but different approaches.

If you care at all about what code is used, we strongly recommend NEVER editing in BookView mode.  BookView will be removed from a future release of Sigil for just these types of problems.

Closing this as this is working as designed and not a bug.  Please direct future requests like this to our Sigil user forums on www.mobileread.com

**Closed** 2018-07-05 16:42 UTC
