### ISSUE TITLE
Visible Find/Replace prevents saving correct panel sizes

### ISSUE THREAD

**Issue by Moilleadoir** [Sigil-Ebook/Sigil#370] opened 2018-07-09 06:47 UTC
I’ve had this problem for a long time, but thought it might be something specific about my Ubuntu 16.04 install. After a recent experiment with Solus and after creating a new Ubuntu 18.04 install, I noticed that the side panels were keeping their chosen sizes.

But after I copied over the `sigil.ini` from 16.04, the side panels were too narrow again. I tried reverting to the `sigil.ini` created on installation and then gradually adding sections from the old one. This narrowed it down to the `[find_replace]` section and at first I thought it might be something about the `find_strings` key, but ultimately the line that made the difference was `visible=true`.

It looks like when the Find/Replace is visible, it is given a set width on startup which reduces the size of the side panels. If I hide Find/Replace before exiting Sigil, on restarting the side panels are the expected size and showing Find/Replace doesn’t change them. If Find/Replace is visible on exit, the panels are reduced on restart.

**Comment by dougmassay** [comment] 2018-07-09 12:22
I can't duplicate this on Windows. I can't expand the right/left widgets wider than the Find/Replace widget's minimum width. The right or the left pane contracts to accommodate F&R's minimum. So when I close Sigil with F&R open, it always keeps the same sizes (for all widget panes) upon restart.

I'll test on Linux when I get home to see if I can reproduce, but in the meantime, is there anything special about how you have the left/right panes configured? Which widgets do you have open in the left/right panes? Are any of them stacked or tabbed with other widgets? A screenshot of Sigil as it is before you close it (which will result in the left/right panes being reduced on restart) would be helpful.

**Comment by Moilleadoir** [comment] 2018-07-10 05:42
I’ve now tested this on Ubuntu 16.04.4 (Unity desktop), 18.04 (Budgie desktop) and Solus (Budgie desktop) by 
1. renaming `sigil.ini` (so defaults to Book Browser left and Table of Contents right)
2. starting, widening the Book Browser slightly and closing Sigil
3. starting, checking it’s saved then Ctrl+F and close
4. starting again to both left and right panes squished

In fact, much the same happens even if I do no resizing in step 2. The sizes of the left and right panes are still reduced if Find/Replace is visible.

I usually have more panes open in a more complicated configuration, but given it happens with the default setup…

I also have a second monitor, but in one of these setups it’s not enabled and I get the same results.

**Ubuntu 18.04, sigil.ini deleted, Book Browser resized**
![sigil 18 04 deleted ini](https://user-images.githubusercontent.com/1229543/42491237-636ac088-8457-11e8-8eff-b7bedf24a27f.png)

**After Find/Replace made visible and restart**
![sigil 18 04 deleted ini visible find](https://user-images.githubusercontent.com/1229543/42491347-c68b4520-8457-11e8-9863-693e428900aa.png)

**Comment by dougmassay** [comment] 2018-07-10 12:13
Thanks. I'll try to do some experimenting soon. Are you using Sigil from your standard repos? If so, what version is it? The reason I ask is that I've never encountered the issue on my Arch Linux development machine. But then I build Sigil myself from scratch. I just want to determine if it's actually an issue with Sigil, or if it's an issue with the repo packages of Sigil. I'll probably have to get an Ubuntu VM together to do any real testing of the Sigil repo package (if I can't reproduce the issue on Arch).

**Comment by dougmassay** [comment] 2018-07-11 00:44
I was able to reproduce this issue in both packaged versions of Sigil and custom-built versions. It was fairly hit or miss, though (no problem on Arch as I mentioned).  I'll look into it, but just know that if I don't figure it out quickly, the issue will probably still exist in Sigil's next version. I'll keep this issue open to remind me. Thanks for bringing it to my attention.

**Comment by Moilleadoir** [comment] 2018-07-11 08:01
Thanks Doug. Obviously not a killer bug, but at least I’ve figured out a workaround.

**Comment by kevinhendricks** [comment] 2019-12-28 00:37
This should now be fixed (by adding to a workaround for the Qt bug in Sigil 1.0.0.
Closing this issue.

**Closed by kevinhendricks** 2019-12-28 00:37 UTC
