### ISSUE TITLE
Request: Ctrl-F -> Esc should set focus to editing window

### ISSUE THREAD

**Issue by ordtrogen** [Sigil-Ebook/Sigil#205] opened 2016-03-29 14:51 UTC
Use case:

I want to search for a word or phrase in order to edit text in that neighborhood. I press Ctrl-F to enter the search term and press Enter one or more times to get to the place I'm looking for. When found, I want to leave search mode and begin editing. 

I expect pressing "Escape" to achieve this, but pressing escape sets focus to the book browser window and I have to use the mouse to bring focus to the editing window. 

I want Escape from Search to set focus to the search hit in the editing window.

**Comment by kevinhendricks** [comment] 2016-03-29 16:25
No,
Use your set keyboard shortcut to open find window and type what you want to find.  Hit the key sequence for Find Next to move to the next place your word is found.  Hit Esc to exit Find window and then Tab to move to exactly where your cursor was left.

Again, closing this as this is not a bug and the feature already exists.

**Closed by kevinhendricks** 2016-03-29 16:25 UTC
