### ISSUE TITLE
Building Python 3.4.3 framework on OS X (10.11) with your instructions results in "Ignoring ensurepip failure: pip 6.0.8 requires SSL/TLS"

### ISSUE THREAD

**Issue by shorshe** [Sigil-Ebook/Sigil#223] opened 2016-06-04 09:20 UTC
Hi,

I tried your building instructions. Starting with Python. Everything seems to work, except building "pip".
"sudo make frameworkinstall" will run smoothly but exit with:

`Ignoring ensurepip failure: pip 6.0.8 requires SSL/TLS`

I tried this several times each times following your instructions in "Building_A_Relocatable_Python_Framework_on_MacOSX.txt" very precisely.

I have openssl installed via brew. I suspect incompatibilities. 

My System:

OSX 10.11.5 (Xcode and command-line tools installed)

**Comment by shorshe** [comment] 2016-06-04 09:25
ah, worked it out myself. Wrong Openssl was in my path.

**Comment by kevinhendricks** [comment] 2016-06-04 10:41
closed as not a bug

**Closed by kevinhendricks** 2016-06-04 10:41 UTC
