### ISSUE TITLE
Disable File & Folder name change + CSS flattening

### ISSUE THREAD

**Issue by RandyLemaire** [Sigil-Ebook/Sigil#363] opened 2018-06-07 14:59 UTC
Hi, would it be possible to add an option to disable Sigil's aggressive file and folder renaming (package.opf > content.opf etc.)? We also use nested folders in CSS for themes, which Sigil unfortunately flattens and renames:
![screen](https://user-images.githubusercontent.com/40032892/41108097-f7d37e8e-6a73-11e8-9754-36f839208b11.png)

I've switched to Calibre & it keeps the ePub 3 structure perfectly intact. But I really miss Sigil :-)

Best,
Randy

**Comment by dougmassay** [comment] 2018-06-07 15:06
Allowing users to define/keep their own internal epub folder structure is something we've had every intention of getting around to some day. Unfortunately, we're probably nowhere near being able to say when that day might be. To say it will be a massive undertaking would be an understatement.

**Comment by kevinhendricks** [comment] 2018-06-07 17:54
Closing this issue as it is really a duplicate of both Issues #148 and #263 (both related to forcing epubs into standard folder structures).

And yes, it is one of our long term goals for Sigil and when we get more developer resources we will create a branch for working on this project.

Thank you for your  bug/feature report.

**Closed by kevinhendricks** 2018-06-07 17:54 UTC

**Comment by RandyLemaire** [comment] 2018-06-08 07:11
OK clear, thanks for your explanations & sorry for the duplicate issue!
