### ISSUE TITLE
is error message (line 113) in source code (base.ts) correct? 

### ISSUE THREAD

**Issue by MyDK** [Sigil-Ebook/Sigil#441] opened 2019-07-12 11:39 UTC
error message line 113 in base.ts: says you can remove the OPF file? but is that not an error in source code? I mean, the OPF file is mandatory in EPUB?? :)
![image](https://user-images.githubusercontent.com/30153047/61125258-ac615900-a4a9-11e9-9e7a-2c282dbbde9c.png)

**Comment by dougmassay** [comment] 2019-07-12 12:00
Yes, it's a typo in the error message, but it's been there as far back as I've looked (v0.8.6) so I don't think it's really that critical. We'll get it taken care of.

**Comment by dougmassay** [comment] 2019-07-12 12:02
Closing this one as it is a duplicate of:

https://github.com/Sigil-Ebook/Sigil/issues/439

**Closed by dougmassay** 2019-07-12 12:02 UTC

**Comment by dougmassay** [comment] 2019-07-12 13:10
My mistake. This was newly introduced. I was searching the code on "can be removed" and saw it as far back as Sigil 0.8.6 (and probably further). My apologies.
