### ISSUE TITLE
Batch spellcheck broken

### ISSUE THREAD

**Issue by Carmina16** [Sigil-Ebook/Sigil#609] opened 2021-04-13 05:37 UTC
In 1.4 and later, the batch spellcheck is broken: the word list is empty, and if `All Words` checkbox is selected, all words in document appear with `Misspelled` column is set to `No`.
The inline spellcheck still works, though.

**Comment by BeckyDTP** [comment] 2021-04-13 06:53
Checking to spell in the "Spellcheck" dialog requires the existence/installation of a dictionary for the appropriate language.

Any declared languages are valid and can be checked in the "Language" column. If you don't have a dictionary for a language in the "Language" column, these words are treated just as you describe.

Please note that a language can be declared at different levels: the entire document (in an OPF file, `<dc:language>xx</dc:language>` or a single file, paragraph, or even individual words.

![opf-language](https://user-images.githubusercontent.com/22416021/114508882-2c939000-9c35-11eb-8d3e-074af0c92b0c.png)

![langs-in-xhtml](https://user-images.githubusercontent.com/22416021/114509011-5482f380-9c35-11eb-8c1b-37e667eab505.png)

**Comment by Carmina16** [comment] 2021-04-13 08:05
The language column contains the language selected for the spellcheck, but all document words are accepted. The editor spell check works as expected.

**Comment by BeckyDTP** [comment] 2021-04-13 08:26
These are two independent elements.
If the spelling checker in Code View works, then an EXISTING dictionary has been selected manually (in Preferences).
![dicts](https://user-images.githubusercontent.com/22416021/114520378-ac275c00-9c41-11eb-8940-8c7a7c308fbf.png)

In the "Spellcheck" window, the dictionaries selected in Preferences are not taken into account, but the actually declared languages. 

Just write your language in the "Language" column and check your hunspell_dictionaries folders for the proper files for that language (xx.aff + xx.dic or xx_NN.aff + xx_NN.dic).

**Comment by Carmina16** [comment] 2021-04-13 08:49
It seems that checker does not fall to `ll.aff` when checking `ll-CC` language. It's a bug.

**Comment by BeckyDTP** [comment] 2021-04-13 08:58
Why would it work this way?
You always needed a pair of DIC + AFF files with the same (full) name.

**Comment by Carmina16** [comment] 2021-04-13 11:05
Because all parts of a language tag except the language itself are optional.

**Comment by dougmassay** [comment] 2021-04-13 11:12
They're not optional here. This is not a bug. This is intentional behavior. Make sure your aff and dic files share the same name (with the exception of the extension) if you want Sigil's spellcheck to work with custom dictionaries. 

Closing this issue as the behavior is by design. Feel free to reopen if renaming the files as explained does not solve the problem.

**Closed by dougmassay** 2021-04-13 11:12 UTC
