### ISSUE TITLE
Formatting keeps changing after renaming files

### ISSUE THREAD

**Issue by soulbrothera** [Sigil-Ebook/Sigil#664] opened 2022-01-01 04:03 UTC
Additional `<p>` tags and `<br/>` tags keep appearing in my code every time I rename a .xhtml file on the left. There may be more tags that are impacted. Although, it doesn't happen to some of my classes (I checked the CSS in my file).

**Comment by dougmassay** [comment] 2022-01-01 04:41
We're going to need to see a specific, reproduceable example. Typically, the only time tags are changed in this type of situation is when invalid xhtml is encountered.

**Comment by kevinhendricks** [comment] 2022-01-01 05:07
Plus info on Sigil version and platform.

Before and after screen captures would help as well.

**Comment by kevinhendricks** [comment] 2022-01-01 14:42
Based on my testing in Sigil 1.0 and later, no xhtml is changed unless:
- it is illegal xhtml
- it is not well formed and can not be parsed at all
- it is just one huge line with no linebreaks which makes it uneditable in any line based editor.

The xhtml must be parseable to update any links to the file that was renamed.  The gumbo parser handles this for you.

**Comment by kevinhendricks** [comment] 2022-01-02 17:51
Please do not forget to supply the asked for additional information, otherwise we will be closing this as works as designed (not a bug).

Thanks

**Comment by kevinhendricks** [comment] 2022-01-04 14:32
As far as my testing shows, this works as designed as parsing each xhtml file and fixing any broken xhtml is required in order to even search for and if found update any links to the renamed file.  Closing this.  I will reopen this once the asked for additional information is provided assuming it shows some non-designed behaviour.

**Closed by kevinhendricks** 2022-01-04 14:32 UTC
