### ISSUE TITLE
Error in Image handling

### ISSUE THREAD

**Issue by Mick2nd** [Sigil-Ebook/Sigil#479] opened 2019-12-24 13:21 UTC
I use Sigil 1.0.0. I tried to import a set of (working) HTM files together with images.
I get plenty of messages "Image already loaded, overwrite?" although the files are in a flat list, when I add them.
Additionally image file names are renamed to other existing files in HTM src attribute, so finally the pages have false content, displaying the wrong images.

**Comment by kevinhendricks** [comment] 2019-12-24 13:30
Then your files have identical names.  If you want to use the exact same file names, they must sit in different directories.  An set of raw html pages to be imported do not have a set directory structure.  As clearly stated in the Release notes, have you enabled the Sigil Preferences Appearance settings to show full book paths if you are going to use an alternative ebook structure?

**Comment by Mick2nd** [comment] 2019-12-24 14:43
I solved my doubled image problem in the meantime. First imported GIF files, then HTM.
But:
**src="banner.gif"** in the index.htm original file -> **src="../Images/smbanner.gif"** in Sigil
That's in my opinion a bug! It changes the filename without reason.

**Comment by dougmassay** [comment] 2019-12-24 14:55
Not a bug. There's a reason.

**Comment by kevinhendricks** [comment] 2019-12-24 14:58
Nothing in Sigil changes a filename by prepending an "sm" to it.  
The file naming routine will only append a numeric range suffix, so this is not Sigil.

Again, for help with using Sigil, please use our MobileRead User's forum to get help not Sigil's issues.

Closing this as not a bug.  Please get your help through the user's forums.

**Closed by kevinhendricks** 2019-12-24 14:58 UTC
