### ISSUE TITLE
[Bug]: Character size not adjusted 

### ISSUE THREAD

**Issue by docjc** [Sigil-Ebook/Sigil#700] opened 2022-10-19 09:05 UTC
### Bug Description

Meta data editor (only here tested)
There is a small problem if the view is enlarged to 125 %: the presented text is enlerged accordingly to the 125% but is you want to edit something the character size is very small, after edition it is enlarged again (see normal.png/editing.png to be found under "Sprache = language")

![editing](https://user-images.githubusercontent.com/108517885/196645609-dad407d5-febe-4e28-b1e9-b7a58facd5a9.png)
![Normal](https://user-images.githubusercontent.com/108517885/196645614-d67ea717-0065-4543-ac70-6288f94f5407.png)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

11 insider release 22621.675

### What version of Sigil are you using?

1.9.20

### Any backtraces or crash reports

```shell
nonehttps://user-images.githubusercontent.com/108517885/196645614-d67ea717-0065-4543-ac70-6288f94f5407.png
```

**Comment by docjc** [comment] 2022-10-19 13:08
Sorry for not explaining correctly, yes, I enlarged via windows, settings, system, screen (monitor??), scaling to set the scaling factor to 125% 

 

Von: Doug Massay ***@***.***> 
Gesendet: Mittwoch, 19. Oktober 2022 14:11
An: Sigil-Ebook/Sigil ***@***.***>
Cc: docjc ***@***.***>; Author ***@***.***>
Betreff: Re: [Sigil-Ebook/Sigil] [Bug]: Character size not adjusted (Issue #700)

 

I'm not certain what you mean by "View is enlarged to 125%" Is the view enlargement a Windows function/feature, or are you talking about something within Sigil?

**Comment by kevinhendricks** [comment] 2022-10-19 13:26
Does it only happen with the Language metadata tag (ie. a field whose value is selected from a pulldown menu) as opposed to a normal field where you manually type the value?  Notice the menu pulldown arrow that exists while it is being edted.

If so, it is probably just the little bit of vertical height lost to it being a menu item in a pulldown menu that for es the text to be slightly smaller due to it being restricted by the table row height.

**Comment by docjc** [comment] 2022-10-19 13:49
no it happens in each field of the meta data tag. It seems to me that it goes back to the "non enlarged" version. As soon I leave this filed, it goes back to the "enlarged " version

**Comment by dougmassay** [comment] 2022-10-19 14:04
I'm not seeing the same behavior on my Windows laptop (Win10) and I always have my Display Settings' scale factor set to 125%. The font sizes are the same pre-, during, and post-editing. There's got to be something else in play.

I'm assuming that you've logged out and back again after changing the scale factor?

**Comment by kevinhendricks** [comment] 2022-10-19 15:55
Leaving the field, exits editor mode.  So editing is when the you are seeing the difference if that helps.

**Comment by dougmassay** [comment] 2022-10-19 18:32
I just can't duplicate the problem with Sigil 1.9.20 on Windows 10. I've changed fonts, I've messed with the Sigil's HighDPI setting, changed the scale factor from 125% to 150%, but all the characters show up as the same size whether I'm in the process of editing, done editing, or have moved on to another field. I've verified I'm not influencing Sigil/Qt with any environment variables -- I'm out of ideas. I don't have access to Windows 11.

**Comment by dougmassay** [comment] 2022-10-19 18:34
Judging by the screenshots, I'd say that Sigil's UI font-family has definitely been changed from the default. So perhaps we need to find out out what font is being used.

**Comment by dougmassay** [comment] 2022-10-19 18:39
The column headers and buttons are different fonts/sizes as well in those screenshots. The Metadata dialogs buttons and column header fonts are always identical to the TreeView's  fonts on my machines whenever I change Sigil's fonts. I'm not sure why they're different on the OP's. 

Perhaps there's custom user qss involved here?

**Comment by kevinhendricks** [comment] 2022-10-19 19:59
I can not reproduce this on macOS at any screen resolution either.  The problem appears to be specific to something on the OP's specific machine or settings.

**Comment by docjc** [comment] 2022-10-20 08:11
Sorry for answering late but I had a little hardware problem yesterday and therefore I have to setup W11 and everything else completely new (not finished yet). So I can’t reproduce the problem again at the moment. On the other hand on my laptop Sigil works fine. So probably there was a problem on my hard/software. So you can close the ticket. Sorry for bothering you.

 

Von: Kevin Hendricks ***@***.***> 
Gesendet: Mittwoch, 19. Oktober 2022 22:00
An: Sigil-Ebook/Sigil ***@***.***>
Cc: docjc ***@***.***>; Author ***@***.***>
Betreff: Re: [Sigil-Ebook/Sigil] [Bug]: Character size not adjusted (Issue #700)

 

I can not reproduce this on macOS at any screen resolution either. The problem appears to be specific to something on the OP's specific machine or settings.

**Comment by kevinhendricks** [comment] 2022-10-20 12:32
Closing

**Closed by kevinhendricks** 2022-10-20 12:32 UTC
Labels: invalid
