### ISSUE TITLE
[Bug]: Manual build fails

### ISSUE THREAD

**Issue by vdijken** [Sigil-Ebook/Sigil#773] opened 2024-09-04 18:12 UTC
### Bug Description

Following the procedure under Linux Mint as described here the build fails. Everything is up-to-date and the advised package are installed, I try the latest version from source:

### Platform (OS)

Linux

### OS Version / Specifics

inux  5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### What version of Sigil are you using?

none I try to get one

### Any backtraces or crash reports

```shell
$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DUSE_SYSTEM_LIBS=1   ../Sigil
-- Trying to use System Libraries...
-- CMake version in use: 3.29.0
-- Using older findpython cmake module
-- Using System ZLIB
-- Using System MiniZip
-- Using System Hunspell
-- Using System PCRE2
CMake Error at src/qt6sigil.cmake:31 (find_package):
  Could not find a configuration file for package "Qt6" that is compatible
  with requested version "6.4".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake, version: 6.2.4
    /lib/x86_64-linux-gnu/cmake/Qt6/Qt6Config.cmake, version: 6.2.4

Call Stack (most recent call first):
  src/CMakeLists.txt:659 (include)
```

**Comment by kevinhendricks** [comment] 2024-09-04 18:47
The newest Sigil requires Qt6.4.0 or later.

**Comment by kevinhendricks** [comment] 2024-09-04 18:51
You need to see if a newer version of Qt is available in your repo.  If not, consider using the python module aqtinstall to get a local qt version.  The latest is Qt 6.7.2.

You can get more help with building Sigil on Linux in our Sigil user forum on www.mobileread.com (see the link in our ReadMe)

As this is not a bug I am closing it.  Our Sigil user forum is the best place to get help.

**Closed by kevinhendricks** 2024-09-04 18:51 UTC
Labels: invalid

**Comment by dougmassay** [comment] 2024-09-04 19:09
The build docs do clearly mention Qt6.4 starting with Sigil 2.3.0:

https://github.com/Sigil-Ebook/Sigil/blob/master/docs/Building_on_Linux.md#getting-qt6

**Comment by kevinhendricks** [comment] 2024-09-04 19:14
And see our responses to your previous bug report to this same thing here:
https://github.com/Sigil-Ebook/Sigil/issues/768
