### ISSUE TITLE
Manifest error message

### ISSUE THREAD

**Issue by lauras** [Sigil-Ebook/Sigil#448] opened 2019-08-10 17:13 UTC
Upon opening ePub 3 files (I have not test on ePub 2), I'm getting a warning that all the files are missing from the manifest. See screenshot attached.

![Screenshot of Sigil (2019-08-10, 10-35-32 AM)](https://user-images.githubusercontent.com/181019/62824685-0152c680-bb5f-11e9-8e60-e03712c16035.png)

No files are missing in the ePubs. The ePubs validate fully. I tried Update Manifest Properties and restarting, but no change.

Sigil Mac 0.9.17
Qt 5.12.3
OS X 10.14.5

(Caveat: I usually work on another machine. This is on my laptop, which I haven't used Sigil on in perhaps a year.)

**Comment by kevinhendricks** [comment] 2019-08-10 18:10
Place a copy of your epub3 on your Desktop into  a folder called "testing" and rename it to "test.epub" and then run the following commands in Terminal.app:

cd Desktop
cd testing
unzip -t test.epub

That will show the complete file structure of the epub as it tests it for errors.

Then actually unzip it by running the following command in Terminal.app

unzip test.epub

Now  look in the testing folder and find the opf file.

Please copy and paste the list of files generated by the unzip -t command and a copy of the opf file here so that we can what actually is listed in the manifest and compare it to what is actually in the epub.

**Comment by kevinhendricks** [comment] 2019-08-10 18:25
BTW,  I have now tested our complete set of epub3s against the latest Sigil 0.9.17 package released this morning.

It does not exhibit any of the symptoms you are reporting in my macOS machine on a very wide range of epub3s.

So the issue is either specific to that epub or to your particular setup.

Could the problem be the use of case insensitive path names in the manifest? 

Or are you running this install from your DownLoad folder?   If you try to run Sigil without manually dragging it outside the DownLoads folder,  Gatekeeper will attempt to run it in a sandbox inside tmp that will make Sigil fail in all kinds of funny ways.

Have you set up symlinks to various folders or to your tmp location?

Sorry, I can't be more help here to track down if this is a real bug or not, until you report back with the extra information I requested.

With the exact epub structure and manifest from before you loaded it in Sigil, we should be able to figure out what is going on and get it fixed.

**Comment by kevinhendricks** [comment] 2019-08-10 18:37
FWIW, there was a bug in the Sigil-0.9.16 release that generated spurious warnings when the opf file was located outside the OEBPS (ie at the same level as the META-INF and mimetype).  This spurious warning bug was fixed in this mornings release of Sigil-0.9.17.  Could you by chance be running the earlier release?  You can check the Sigil version in the About menu.

**Comment by lauras** [comment] 2019-08-10 22:47
If nobody can replicate this, I will assume this is specific to this machine. I will follow up once I have tested on the machine I've been using day to day.

**Comment by kevinhendricks** [comment] 2019-08-10 23:17
It would help if you could verify if this is version 0.9.16 or today's release of 0.9.17 as what you described could be a known bug that was fixed in today's release.

**Comment by lauras** [comment] 2019-08-10 23:24
0.9.17, as stated in the OP.

**Comment by kevinhendricks** [comment] 2019-08-10 23:28
Hmm,  that is strange.  When you get a chance, please try testing the epub as described earlier and reporting back the structure list of the epub and the contents  opf file from the original epub so that we can see what might be causing this issue when it is imported into Sigil.

**Comment by lauras** [comment] 2019-08-10 23:32
This affects every epub I tried, which makes me think something is amiss on my machine. I will test on my main machine tomorrow.

**Comment by dougmassay** [comment] 2019-08-10 23:38
Keep in mind that even if it is something specific to that system, we'd still like to figure out what it might be. We might be able do something to fix it, and more importantly ... prevent it from happening on other systems.

**Comment by kevinhendricks** [comment] 2019-08-14 18:53
Any update on your issue and what might of caused it?  If not, I will be closing this issue at the end of this week as "works for me".

**Comment by lauras** [comment] 2019-08-14 19:47
Finally back at my desk. (Sorry, personal matter came up.)

On my iMac, I am unable to reproduce the error. The same files open without any manifest warning.

One thing different between machines, aside from the fact that my laptop is 7 years old, is that I upgraded Sigil from what must have been a version from a year or more ago. On my iMac, which displays no warnings or errors, I upgraded from Version 0.9.13. I honestly do not know what version I upgraded from on the laptop.

I'm not sure what other info might be helpful.

**Comment by kevinhendricks** [comment] 2019-08-14 21:09
The piece of code that checks for missing files tries to build a canonical path based on the location of the opf file coupled with the manifest url.  It then compares that to each file inside the zip archive (an epub is a sip).

So if the exact same epub gives a warning on one machine but does not on another, means one of four things:

1. When Sigil was downloaded and installed last you did not manually drag it from your Downloads folder to your Desktop before mounting the dmg file and copying Sigil.app.
When this happens macOS's gatekeeper runs the app in a sandbox actually moved away from the applications location.  This would cause all kinds of manifest warnings.

The solution is to of course redownload and reinstall but this time move the dmg out of your Downloads folder onto your Desktop manually, then install Sigil from it.

2. Recent versions of Sigil need at least macOS 10.12 or later, otherwise it will not work correctly.

3. You or an administrator have changed or added symlinks or aliases that are used to point to /Applications folder or /tmp folder that are different paths or that use ../ or ./ in some way so that an absolute path is somehow different from a canonical path.

4. One machine is using a case insensitive file system and the other is using a case sensitive one and the manifest path is being interpreted in different ways or the zip archive internal filepath is being interpreted in a different way.


Point 1 is fixable.  Point 2 might require an OS update.  Point 3 will require some digging using the unix "ls -al" command to see which path to the temp folder or your applications folder or your home folder may be symlinks using relative path segments.  
Point 4 would require digging as well.

Or alternatively we could create a debug build for you to install on the impacted machine that will print out the paths generated from the manifest and the paths generated when unpacking the epub and we can try to use that to determine what is different about them.

Just let us know if you want to go that way.

Kevin

**Comment by lauras** [comment] 2019-08-14 22:06
Point 1 is a first for me. I've never heard of this, never seen any app developer recommend this. Sigil was installed by opening the .dmg from where it was downloaded on both machines.

So I tried it your way, and re-downloaded it and dragged it to the desktop before opening.

Same error. No change.

I unzipped the file following the steps you provided above. The opf is within the OEBPS folder. It lists all the files in relative paths, so for example the chapters are within the Text subfolder.

The error message seems to expect "OEBPS/" to be included in the file paths.

2/ Both Macs are running the latest Mojave.

3/ I never did this. No aliases in my bash profiles.

4/ This is not the case.

Again, after the warning message, the ePub itself works fine, and epubs I save on the machine giving the warning open without warnings or problems on the other machine.

I suppose I could try deleting all my Sigil preferences and reinstalling the app. Would that help? I don't use this machine much, but I rely on it when traveling, so it's in my interest to make sure I have no hidden bugs in Sigil.

And I want to help the project, if I can.

**Comment by kevinhendricks** [comment] 2019-08-14 22:17
Hi Laura,

Point 1 is a little known way of preventing executables from running successfully in the Download folder that Apple has been doing for some time.  It relies on Gatekeeper and meta flags.

On first launch of something freshly downloaded to your download folder you can see the sandbox being generated in tmp if you look for it.  At least it happens on my 10.13.6 machine.  They may have changed it in Mojave.

Hmm, then they only way to track this down is to create a debug build that will print out the manifest based paths and the zip based paths and see where they differ.  With that knowledge we may be able to figure out why.

I will create a debug build tonight and post a link.   All of the debug output will be directed to a file specified by an environment variable.

I will include some Terminal.app directions on unpacking it and setting the environment variable and generating the debug output which you can post here and we can try to figure out why this works on one machine and not the other.

I am about to get some dinner, so look for a debug build sometime later this evening.

Thanks for helping us track this down.

Kevin

**Comment by kevinhendricks** [comment] 2019-08-15 00:09
Here is the info for using the debug build:

After downloading, move the Sigil*.tar.xzfile to your Desktop
Then open Terminal.app and run the following:

cd
cd Desktop
tar -xvf Sigil*.tar.xz
export SIGIL_DEBUG_LOGFILE=${HOME}/Desktop/epub_open_debug.txt
open ./Sigil.app


This will change directory to your home directory, and then into your Desktop where the downloaded debug tar.xz file is
The tar command will unpack the tar.xz file to create a Sigil.app on your Desktop
The next line will set an environment variable that tells Sigil to write its debug output to your Desktop to a file called epub_open_debug.txt
The next line will launch the just unpacked Sigil.app

Then please use the menus to select and load an problematic epub.
As soon as the load is complete you can quit out of Sigil.

The  please zip up the resulting epub_open_debug.txt file and attach it to this issue.

We can look at it to see why the warnings were generated and hopefully figure out how to fix this for everyone.

The link to the debug build of Sigil from our Travis CI for macOS is here:

https://drive.google.com/uc?id=1hWAU-L7cGEPKEef30RK5EViHgUOzQzOz&export=download

Please let us know once you have downloaded the debug build so that we can remove this link as we have a daily limit on downloads.

Thanks,

Kevin

**Comment by lauras** [comment] 2019-08-15 13:30
I expect I can get started on this in the next few days. A bit swamped atm, but I'll get to it.

**Comment by kevinhendricks** [comment] 2019-08-15 14:14
Understood.  The entire process including the download should take less than 10 minutes in total.
Again, please let us know when you have downloaded the debug build so we can remove the public link.

**Comment by mhicks53** [comment] 2019-08-18 19:12
Attaching debug file. I have not tried opening files with Sigil on my Desktop yet to see if I get an empty file. I will try PageEdit functionality.
--MH
[debug.zip](https://github.com/Sigil-Ebook/Sigil/files/3513453/debug.zip)

**Comment by kevinhendricks** [comment] 2019-08-20 16:37
I am going to close this issue, as I was able to get the debug output from mhicks53 who has the same issue on macOS 10.14. 

The debug/testing output showed that symlinks are being used as /var points to /private/var and /tmp points to /private/tmp which is standard on macOS (all recent versions).  The issue is that a macOS bug has long existed that even though we ask for a canonical path (with all symlinks resolved) it did not resolve those symlinks.

That bug no longer exists in some macOS systems in macOS 10.14.x.  But not all, perhaps those with a clean install?

Either way, this actual bug fix in macOS messes up Sigil's way of testing if files are properly manifested.

We have fixed this to workaround this macOS change in Sigil master, so that test should work properly in all macOS systems.

**Closed by kevinhendricks** 2019-08-20 16:37 UTC
