### ISSUE TITLE
python error: module 'html5lib.treebuilders' has no attribute '_base'

### ISSUE THREAD

**Issue by dhqdqk** [Sigil-Ebook/Sigil#316] opened 2017-09-23 07:31 UTC
sigil  cannot run. ( KDEneon X64 based on ubuntu16.04lts)
```
Traceback (most recent call last):

  File "/usr/share/sigil/python3lib/xmlprocessor.py", line 5, in <module>
    from sigil_bs4 import BeautifulSoup

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/__init__.py", line 48, in <module>
    from .builder import builder_registry, ParserRejectedMarkup

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/__init__.py", line 328, in <module>
    from . import _html5lib

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_html5lib.py", line 86, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):

AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
```
check  the dir /html5lib/treebuilders :
```
:/usr/local/lib/python3.5/dist-packages/html5lib/treebuilders$>ls
_base.py  base.py  dom.py  etree_lxml.py  etree.py  __init__.py  __pycache__
```
 the module file "base.py" exists in html5lib, but the "_base.py" not exists.
it does not work that copying  base.py to _base.py。

**Comment by kevinhendricks** [comment] 2017-09-23 11:45
Is this your own build?  If so on what distribution?  Your "ls" command does in fact show _base.py in your listing of files.  It comes just before base.py, which directly contradicts what you are saying.

**Comment by dhqdqk** [comment] 2017-09-23 18:44
1. all python packages in my os is installed by default or pip/pip3.
2. the sigil is installed by order "sudo apt install sigil" from ubuntu's archive.
3. In the dir "/usr/local/lib/python3.5/dist-packages/html5lib/treebuilders":
     file "base.py"  exists by default;
    file "_base.py" does not exist by default; it  is copied from "base.py"; this method takes no effect.

**Comment by dhqdqk** [comment] 2017-09-23 18:52
I have solved the problem：
1. /usr/share/sigil/plugin_launchers/python/sigil_bs4/builder$>sudo emacs _html5lib.py 
2. replace the string "_base" by "base" in "_html5lib.py "
now the sigil works.

**Comment by dougmassay** [comment] 2017-09-23 19:01
It's an issue with the newest version of html5lib. The latest version of upstream bs4 accommodates it. We may have to look into incorporating upstream bs4 changes in our sigil_bs4.

https://bugs.launchpad.net/beautifulsoup/+bug/1603299

Possibly a simple try/except clause in our sigil_bs4 to work with all html5lib versions.

A temporary workaround for Linux users who installed html5lib with pip3 would be to force downgrade html5lib to an earlier version with pip3

We'll run into the same problem if we upgrade html5lib to the latest version in our Windows/Mac bundled Python.

**Comment by dougmassay** [comment] 2017-09-23 19:27
Actually, our version of sigil_bs4 accommodates this already. I'd suspect upstream Ubuntu of changing something, but they'd be more prone to replace sigil_bs4 entirely than leave it in and break it. Are you certain you didn't try to replace sigil_bs4?

**Comment by dougmassay** [comment] 2017-09-23 19:53
I've confirmed that your error message does not align with the code/files in sigil_bs4/ that is being delivered with the Sigil binary package from the standard Ubuntu 16.04 software repositories.

Closing this issue as it appears to be a self-inflicted problem.

**Comment by dougmassay** [comment] 2017-09-23 20:08
Apologies. The _html5lib.py IS broken in the older version of Sigil (v0.9.5) being provided by the 16.04 repositories (beyond a certain version of the html5lib).

This needs to be reported upstream. If they don't want to update to the latest Sigil (v0.9.8), then they at least need to cherry-pick the latest sigil_bs4/ contents.

In the meantime, I recommend users use ppa:mapreri/sigil to install Sigil v0.9.8 instead.

**Comment by dougmassay** [comment] 2017-09-29 23:56
Closing this, as it's fixed in the latest version of Sigil

**Closed** 2017-09-29 23:56 UTC

**Comment by JuneFreer** [comment] 2019-08-31 05:37
> I have solved the problem：
> 
> 1. /usr/share/sigil/plugin_launchers/python/sigil_bs4/builder$>sudo emacs _html5lib.py
> 2. replace the string "_base" by "base" in "_html5lib.py "
>    now the sigil works.

I have solved this problem by using your method, thank you!

**Comment by kevinhendricks** [comment] 2019-08-31 14:19
This should not be needed with any recent version of Sigil.  What Sigil version are you using?

**Comment by JuneFreer** [comment] 2019-08-31 14:35
> This should not be needed with any recent version of Sigil. What Sigil version are you using?

actually I did not use Sigil, and I don't know what is Sigil, I just met a similar problem.

**Comment by kevinhendricks** [comment] 2019-08-31 15:21
And commented about it in Sigil github issues on a bug that was fixed over 2 years ago.

**Comment by eli-schwartz** [comment] 2019-09-01 02:56
I wonder how you could possibly solve your problem by editing the file /usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_html5lib.py if you don't use sigil....

Whatever software you do use that is self-declared as totally unrelated to this repository has quite possibly been subtly broken by API-level incompatibilities, though, which you are papering over by editing a file you don't understand, from a project you don't use. If you had any idea what you were doing, you would know this...

*/me headdesk* 🤦🤦🤦

**Comment by JuneFreer** [comment] 2019-09-01 05:42
> And commented about it in Sigil github issues on a bug that was fixed over 2 years ago.

oh, sorry, I didn't noticed that this is a Sigil github issue. I just copy and paste the error message and this page is the first link showed in google, sorry about that...

**Comment by JuneFreer** [comment] 2019-09-01 06:01
> I wonder how you could possibly solve your problem by editing the file /usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_html5lib.py if you don't use sigil....
> 
> Whatever software you do use that is self-declared as totally unrelated to this repository has quite possibly been subtly broken by API-level incompatibilities, though, which you are papering over by editing a file you don't understand, from a project you don't use. If you had any idea what you were doing, you would know this...
> 
> _/me headdesk_ 🤦🤦🤦

Thank you for your reply and guide. I just searched that Sigil is an open source software. I met this problem because I was learning how to use the BeautifulSoup, the _html5lib.py is a file that inside the BeautifulSoup folders, and I just got the same Traceback message as this issue, so I tried to use this method to solve it, even though I don't very understand the principles. I'm learning it now.

**Comment by JuneFreer** [comment] 2019-09-01 06:02
> I wonder how you could possibly solve your problem by editing the file /usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_html5lib.py if you don't use sigil....
> 
> Whatever software you do use that is self-declared as totally unrelated to this repository has quite possibly been subtly broken by API-level incompatibilities, though, which you are papering over by editing a file you don't understand, from a project you don't use. If you had any idea what you were doing, you would know this...
> 
> _/me headdesk_ 🤦🤦🤦

and if my reply is not permitted in this issue, I will delete it

**Comment by saranvdev** [comment] 2020-06-23 15:29
> I have solved the problem：
> 
>     1. /usr/share/sigil/plugin_launchers/python/sigil_bs4/builder$>sudo emacs _html5lib.py
> 
>     2. replace the string "_base" by "base" in "_html5lib.py "
>        now the sigil works.

Thank you very much, this fixed the error perfectly.

**Comment by eli-schwartz** [comment] 2020-06-23 16:03
@saranvdev 

This should not be needed with any recent version of Sigil. What Sigil version are you using?

**Comment by saranvdev** [comment] 2020-06-24 15:10
I have no idea what Sigil is to be honest, but it was still helpful for another app.

**Comment by eli-schwartz** [comment] 2020-06-24 15:30
Again???

Why are people posting about non-Sigil related stuff here. The problem is a fundamental API problem. You need to use the correct versions of beautifulsoup and html5lib in your application. If you do, things work. If you don't, things break.

After careful evaluation of the versions involved, the Sigil developers determined it was safe to rename one specific version of **their beautifulsoup fork** without ill effects. You cannot just rename things willy-nilly.

Your other program has a good chance of being broken in subtle ways now. It should be fixed properly... Please consult the upstream developers of your other program.
