### ISSUE TITLE
[Suggestion]Update toc.ncx, toc.xhtml and legacy manifests automatically if they are existed in an Epub3 file

### ISSUE THREAD

**Issue by vinixwu** [Sigil-Ebook/Sigil#379] opened 2018-08-03 04:28 UTC
I knew toc.ncx is left for backward compatibility, and toc.xhtml is optional, but when they DO exist in an Epub3 file, everytime I add a chapter, I have to:
1. Using "Generate Table Of Contents" icon to update the nav.xhtml.
2. Using "Epub3 Tools -> Generate NCX from Nav" to update toc.ncx.
3. Using "Epub3 Tools -> Update Manifest properties" to update legacy manifest. Both 3 and 4 have to be done for most Epub2 readers to show updated TOC.(Like Microsoft Edge and Moon Reader+)
4. Using "Tools -> Table Of Contents -> Create HTML Table Of Contents" to update toc.xhtml.

Is it possible to add options in "Generate Table Of Contents" dialog, so user can do above steps semi-automatically? Or even better, when user updated TOC, and these files are existed, update them automatically?

**Comment by kevinhendricks** [comment] 2018-08-03 14:07
On epub3, you only need to generate the toc.ncx and update manifest properties ONCE just before you do the final save.  This will sync the toc.ncx to the nav and look for and identify any use of script, mathml, svg tags you may have added to any of the xhml files to properly update the opf manifest properties.

You do not need to run it for every file change or chapter add.  The nav is primary in epub3 ( and is a legal html toc as well ).

Given updating manifest properties requires walking every single tag of every single xhtml file, this is an expensive operation and should only be done at the end (once if possible) and not after any xhtml file edits are done.

So manual control of when you need to recreate the toc ncx, and when to update manifest files is by design. 

Closing this

**Closed by kevinhendricks** 2018-08-03 14:07 UTC
