### ISSUE TITLE
Can't save: Sigil has encountered a problem

### ISSUE THREAD

**Issue by adamthedorsey** [Sigil-Ebook/Sigil#525] opened 2020-05-07 18:58 UTC
**Error:**

```
Error info: Cannot save file /Users/***/Desktop/***.epub: /private/var/folders/j9/fdbfnht93lsg336yfvsmwb7h0000gn/T/Sigil-eKTGXH/OPS/fonts/.37536.otf: http://www.idpf.org/2008/embedding: F79B7645-E9AF-4B2D-B3ED-B1D5EECA80D2
Sigil version: 1.2.0
Runtime Qt: 5.12.7
Compiled Qt: 5.12.7
System: macOS 10.15
Architecture: x86_64
```

Running Mac Os Catalina - 10.15.4 (19E287)

Thanks!

**Comment by kevinhendricks** [comment] 2020-05-07 21:30
I will need a sample epub that displays this problem as I can not recreate it on any of my macOS machines.

It appears to be caused by an exception being thrown because you are trying to obfuscate a font using the IDPF font obfuscation algorithm.  

Does your epub really have a font file name that begins with "."?
As in the error message: ".37536.otf"

Have you enabled font obfuscation? 

How was this font file added to the epub?

How long has your macOS and Sigil been running continously (and sleep counts)?  Please note that after a set number of days, macOS will "clean up" its tmp folder and delete files out from under Sigil and this would cause an exception if the font file was deleted by macOS.

The only way is to prevent this is to use Sigil's Preferences to set a local private temp folder path that you manually manage or never allow Sigil to remain running with an epub open over many days.

**Comment by adamthedorsey** [comment] 2020-05-07 21:35
I actually tracked it down to embedding fonts. When I was embedding a
specific font I was getting that error.

For now I’m just going to use system fonts.

Here is an example ePub with embedded fonts.

Thanks!

**Comment by kevinhendricks** [comment] 2020-05-07 22:36
There are no embedded fonts in that posted epub.  There are no font files of any type in that epub file.

Again, it is not font embedding that is caused that exception, it is instead the trying to obfuscate a non-existent font file.   The only way that could happen is if there was an encryption.xml file with font obfuscation entries in the epub along with missing font files.

I can not fix this or even tell if it is a bug until I get an example of an epub that has embedded fonts, that tries to use idpf font obfuscation upon saving that actually fails.

Please post a sample of an epub that actually when trying to save it.

**Comment by kevinhendricks** [comment] 2020-05-07 22:49
FWIW,  I have now loaded and saved a number of test epubs with actual embedded fonts with no issues at all on the latest version of Sigil running on macOS.  I was able to test with both Adobe and IDPF font obfuscation.

So whatever is causing your problem must be file specific.  Have you actually tested the problem otf font file to make sure it is not corrupted, has the proper read permissions, etc?

**Comment by adamthedorsey** [comment] 2020-05-07 22:58
Sorry, stepped away. And apologies for the wrong file, I must have overwritten it.

The ePub was originally exported from Apple pages. 

Let me reexport and upload.

Great product btw! Saving me a to. If time editing the markup and styles directly.

**Comment by adamthedorsey** [comment] 2020-05-07 23:06
Again, this could be an Apple Pages issue, not sure. But my task is editing epubs from Apple Pages and iBooks Author, so that is how I stumbled on this error.

**Okay, here are the steps I used to re-produce.** 

1. Export epub from Apple Pages and select "Embed Fonts." - It doesn't matter which fonts you are using, I tested a half dozen.

![Screen Shot 2020-05-07 at 7 02 04 PM](https://user-images.githubusercontent.com/63333236/81352908-b639f580-9095-11ea-9375-01bc9aecdd74.png)

2. Open ePub in Sigil and click "save."

![Screen Shot 2020-05-07 at 7 02 31 PM](https://user-images.githubusercontent.com/63333236/81352961-dbc6ff00-9095-11ea-9a7a-7e05279c1760.png)

**Example epub file:**
[Testing Fonts.epub.zip](https://github.com/Sigil-Ebook/Sigil/files/4596189/Testing.Fonts.epub.zip)

Thanks!

**Comment by dougmassay** [comment] 2020-05-07 23:11
> Again, this could be an Apple Pages issue, not sure.

It wouldn't be the first time Pages was guilty of doing silly things to epubs. ;)

**Comment by dougmassay** [comment] 2020-05-07 23:19
I can't even open that epub on Linux. 

> Error info: Cannot load file /home/dlmassay/Documents/Testing.Fonts.epub: /tmp/Sigil-GoWtMU/META-INF/container.xml: Epub has missing or improperly specified OPF.

**Comment by dougmassay** [comment] 2020-05-07 23:21
Never mind. Bone-headed mistake on my part. I thought he .zip extension was just added so it could be uploaded to github.

**Comment by dougmassay** [comment] 2020-05-07 23:27
It really is all about the font filename that begins with a "." 

Rename it (in Sigil's Book Browser) and the error goes away. Epubcheck doesn't squawk at all about the filename, so it wouldn't surprise me if it's technically valid. But it sure isn't a good idea!

**Comment by adamthedorsey** [comment] 2020-05-07 23:35
Got it. Thanks!

**Comment by kevinhendricks** [comment] 2020-05-07 23:47
Reopening as there must be a bug in Sigil's ExportEpub functions someplace.
I checked and the font file with the "." is the issue but Sigil finds that font file properly, unobfuscates it, uses it properly, and it only when trying to save the epub that it then tries to re-obfuscate that font file, but can not find it as it is never copied to the output temp directory that is used to create the epub.

So I want to leave this open to we find that bug and track it down and get it fixed.

That said, using a "." to start a file name (especially on a unix based systems like Linux and macOS is really never a good idea.

Once I have tracked down and committed a fix for this I will close it.

Thank you for your bug report and sample epub to debug with.

**Comment by kevinhendricks** [comment] 2020-05-08 00:03
Okay, in ExportEpub we use Utility::CopyFiles to copy files to the destination directory and to list the files to copy we use QDir::infoentryList with no filter.  

Unfortunately, we need to explicitly add a filter to get QDir::Hidden files (those starting with a "." on unix like systems), otherwise these files are never generate in the infoEntryList in Qt's QDir.

We need to figure out how to set a filter and include the hidden as well.

**Comment by adamthedorsey** [comment] 2020-05-08 00:04
You got it. Thanks for the stellar support and product!

**Comment by kevinhendricks** [comment] 2020-05-08 00:25
@dougmassay 
Just pushed a "fix" in Misc/Utility.cpp in CopyFiles.  Tested with the test case provided and even filenames that start with "." are now properly processed on save in Sigil.

The issue is I am not sure if the QDir::Drives flag is needed on Windows.  
See https://doc.qt.io/qt-5/qdir.html

So when you get a free moment would you look at that (and maybe try with and without that flag)  in CopyFiles and confirm if we need to add that flag for Windows to list all files of a folder properly.

If so please add it and close this.  Otherwise we can just close this as is.

Thanks!

**Comment by dougmassay** [comment] 2020-05-08 00:36
Whoops! Commented on the commit by mistake.

Looks about right. I'll check it out on Windows and linux.

Will we need to do something similar for Utility::GetAbsolutePathsToFolderDescendantFiles (right above CopyFiles? I see you've manually handled the NoDotAndDotDot in that function, but will that use of entryInfoList need similar treatment? Or is that not relevant there?

**Comment by kevinhendricks** [comment] 2020-05-08 00:50
Yes, technically, we should add it there as well but a search for:
    GetAbsolutePathsToFolderDescendantFiles
shows nothing links to it.

That was with a github search.  I will grep for it to be sure.  If now unused we should probably remove that routine from Utility.cpp so we no longer have to worry about it.

**Comment by dougmassay** [comment] 2020-05-08 19:31
The change seems to work as expected on Windows (though Windows had no problem with this case originally).

There is, however, an edge case on Windows (that has been present all along). It's hardly worth mentioning, but I will just for thoroughness. ;)  If someone accidentally renames a file to have a .lnk extension, they won't be able to rename it to anything else after that. And although the epub will save without error, the file will silently disappear when the epub is next opened.

Clearly there's no valid reason to have an .lnk file in an epub, but I wonder if it might be worth adding QDir::System to the filter for thoroughness? Is there any chance doing so would adversely affect unix? Sockets and device files wouldn't be an issue with epub files would they?

QDir::Drives should be unnecesary. C:\ or D:\ and the like are not valid file names on Windows anyway. Sigil didn't allow naming a file "E:\" before or after this change.

**Comment by kevinhendricks** [comment] 2020-05-08 23:56
Please just ifdef that to Windows as no special system or unix dev files or sockets should ever exist in an epub so I would rather not enable them on macOS and Linux.

I deleted the GetAbsolutePathsToFolderDescendantFiles call from Misc/Utility.cpp and .h as it is no longer being used anyplace.

**Comment by dougmassay** [comment] 2020-05-09 00:02
I'm still debating whether to even do it for Windows, to be honest. It's never come up before, and there's little point in trying to save everyone from themselves. I'm leaning toward closing this as it stands. The error reported is fixed.

**Comment by kevinhendricks** [comment] 2020-05-09 00:35
Sounds good to me!

**Closed** 2020-05-09 01:46 UTC
