### ISSUE TITLE
QtWebKit is unmaintained (again)

### ISSUE THREAD

**Issue by a17r** [Sigil-Ebook/Sigil#418] opened 2019-04-29 20:58 UTC
While not having an official release since Qt 5.5 (for ages), the intermittent external support (that even got merged back upstream) dried up 15 months ago. As a consequence, distributions like openSUSE and Gentoo are starting to phase it out for good this time. Are there plans to support QtWebEngine at least alternatively?

**Comment by eli-schwartz** [comment] 2019-04-29 20:59
See the "engine" branch.

**Comment by dougmassay** [comment] 2019-04-29 21:04
Yes, though still fairly experimental, the engine branch is quite functional/useable at this point. And we're keeping it in sync with the master branch. Whether it's the future of Sigil is undetermined as of yet, but early testing (and the lack of meaningful activity on the "revived" QtWebKit fork) would suggest it's pretty likely.

**Comment by kevinhendricks** [comment] 2019-04-29 21:28
As stated above, Sigil has already been ported to QtWebEngine, see our engine branch..  Work to polish/clean the port is ongoing and that branch already compiles and works on Linux, Windows, and Mac.  Right now it requires backported fixes from future Qt 5.12.4 to not leak QWebEngine pages.

Both master and engine branches are kept in sync.  So closing this issue.

**Closed by kevinhendricks** 2019-04-29 21:28 UTC

**Comment by a17r** [comment] 2019-04-29 21:36
Thanks, that is good news for our sigil maintainers.

**Comment by annulen** [comment] 2019-06-10 15:40
No need to worry, QtWebKit is actively developed and new versions will be released soon

**Comment by kevinhendricks** [comment] 2019-06-10 16:11
@annulen 
Sigil must support all 3 main platforms, Linux, Mac, and Windows equally.

From your recent patreon posts and posts on your own github webkit project in replies to issues, you specifically state you are planning support for only Linux with your upcoming QtWebkit releases?  Has that changed?

What release or tag from webkit master or release from webkitgtk will be used as the basis of your new port?  As the version used for qt-5.212 is quite old now and suffers from a number of webkit bugs documented in their bug tracking.  How often will updated releases be made?

Currently the QtWebkit 5.212 seems to heavily leak memory when loading xhtml with svg image files, and with embedded fonts under Qt 5.11.x and Qt 5.12.x.  There does not seem to be an easy way to debug memory leaks in QtWebkit especially where javascript is used.  Heavily leakage on Windows in particular is causing many problems for Sigil.  None of these issues are a problem with QtWebkit 5.6 used with Qt 5.6.4.  Is anything being done for leak testing and fixes for your port when used with the current stable LTS versions of Qt (ie. Qt 5.12.x).  

Will the Web Inspector port be completed allowing memory usage by javascript reporting during debugging?

Will you be supporting a Qt interface to WebKit2 on all platforms as activity on webkit1 has been marked as legacy even in the latest WebKitGTK releases?

These are all issues driving us to QtWebEngine in Qt 5.12.x.

**Comment by annulen** [comment] 2019-06-10 16:23
>Has that changed?

Yes, funds were collected to support Windows. It would be great to have more backing from macOS users, however this platform is less problematic so it will be supported at least on current level

>How often will updated releases be made?
~ every 6 months with update to WebKit trunk

>Currently the QtWebkit 5.212 seems to heavily leak memory when loading xhtml with svg image files, and with embedded fonts under Qt 5.11.x and Qt 5.12.x.

It might be that some of these issues are caused by upstream bugs and will disappear, in particular your SVG issue may be of that kind

>Will the Web Inspector port be completed allowing memory usage by javascript reporting during debugging?

Yes

>Will you be supporting a Qt interface to WebKit2 on all platforms as activity on webkit1 has been marked as legacy even in the latest WebKitGTK releases?

This issue is specific to WebKitGTK port. "webkit1" is just a name of API later running directly on top of WebCore components, which is maintained as a part of specific WebKit port. I see no reason for application like e-book reader to require multiprocess web renderer.

**Comment by dougmassay** [comment] 2019-06-10 16:32
> I see no reason for application like e-book reader to require multiprocess web renderer.
Sigil's not an ebook _reader_ it's an ebook editor/creator. As such it can have many, many resources open simultaneously. With embedded fonts and SVG images and javascript on each loaded page, it can be quite resource intensive (and each "leaky area" accumulates quickly). Much more so than a simple ebook reader that displays one page at a time.

**Comment by kevinhendricks** [comment] 2019-06-10 16:33
Sigil is actually not an ebook reader but an ebook editing environment.  It already is multithread.  In fact, QtWebkit 5.212 with Qt 5.12.x will spawn over 30 threads on a older i7 chip with 4 real cpu chips on macOS right now.  These count basic Qt worker threads, javascript compile threads, javascript garbage collection threads, main gui thread, event dispatching thread, etc .  Isolating many of these threads into another process or processes  will simply help stability and help security in the long run at the expense of a  asynchronous interface.

**Comment by annulen** [comment] 2019-06-10 16:34
Okay

**Comment by annulen** [comment] 2019-06-10 16:36
It's possible to use WebKit2 with 5.212 (as well as previous versions), but there is no public C++ API and existing one may be too limiting for your application.

**Comment by kevinhendricks** [comment] 2019-06-10 17:11
In the end, this will really be determined by what the various main Linux distributions decide to do.  If they drop QtWebkit support from their internal Qt packages, QtWebEngine will be the only alternative.  If you do actually release an updated QtWebkit that supports all 3 platforms that builds and works with Qt 5.12.x (on a ongoing basis) and that fixes the main memory leaks, and the main Linux platforms keep including it, then we will have a real decision to make. 

As it stands now because of the current issues with QtWebkit 5.212 with Qt 5.12.x, we are releasing our last QtWebKit based build this week, and moving to our engine branch as next master.  We can keep the webkit branch in parallel with the new master for the next 6 months or so until this all shakes out one way or the other.

**Comment by kevinhendricks** [comment] 2019-06-10 17:16
BTW, one feature to think about, would be a way to isolate the javascripts that are used by the application itself to operate separate from user/content javascripts embedded in xhtml pages.  This is one feature QtWebEngine got right as it allows our users to disable javascript when editing epub3's while keeping the application itself actually running.  This allows the user's to prevent nastily crafted epubs from running unchecked.

**Comment by annulen** [comment] 2019-06-10 17:23
WebKit supports JavaScript "worlds" in the same way as QtWebEngine does, it just isn't exposed in API

However, from what you described above and given that your code doesn't use much of QWebElement, it would probably be better for your project to switch to QtWebEngine

**Comment by annulen** [comment] 2019-06-10 18:52
BTW, could you give more details about fonts issue with Qt 5.11 and 5.12?

**Comment by kevinhendricks** [comment] 2019-06-10 20:24
When epub has its own embedded fonts and the QWebView is reloaded, the fontcache appears to not be cleared resulting in increasing memory usage.  This may be Qt not WebKit related as there are many fontcache and QRawfont related bugs in Qt 5.12.x and earlier.  For example see the discussion around QTBUG-76219

I would be happy to try put together a stand-alone testcase that illustrates the memory issues we are running into, if you want one. 

That said Qt5.12.4 may fix our issues or upstream changes from WebKit may also fix our issues.  I agree the svg image file bug is probably fixed in WebKit upstream as that bug is very evident.  WebKit seemed to be in some kind of a smart/weak/ref counted pointer hell (PassPtr, PassRefPtr, Ref, RefPtr, plus weak pointers) when you forked it a couple of years back.  I hope that has improved.

**Comment by annulen** [comment] 2019-06-10 21:29
>This may be Qt not WebKit related as there are many fontcache and QRawfont related bugs in Qt 5.12.x and earlier.

Yes, QTBUG-76219 ineed can be the culprit

> I agree the svg image file bug is probably fixed in WebKit upstream as that bug is very evident. 

And I actually see a few commits in trunk featuring "SVG" and "leak", and there are other leak fixes.

>I would be happy to try put together a stand-alone testcase that illustrates the memory issues we are running into, if you want one.

I don't need it right now, but if you have remaining issues after Qt 5.12.4, then it would be great
