### ISSUE TITLE
Warning to consider upgrading sigil-editor-browser to the latest version or downloading Google Chrome or Mozilla Firefox

### ISSUE THREAD

**Issue by niroGH** [Sigil-Ebook/Sigil#303] opened 2017-07-12 13:21 UTC
Hey all,

I am new here and this is my first issue if there are mistakes sorry for that.

I want to add iframe in my ebook, which I creates with sigil.
Some external websites works fine but on others it shows this warning: 
"ReferenceError: Can't find variable: WeakMap

Unfortunately you cannot use the Open Roberta Lab with this browser.
Please, consider upgrading your browser to the latest version or downloading Google Chrome or Mozilla Firefox"

Iframe for that warning is: 
<p><iframe src="https://lab.open-roberta.org/" width="400" height="200"></iframe><br/></p>

My question is:
Is it possible to bypass this warning?
If yes, could you please help me with that?

thank you

**Comment by kevinhendricks** [comment] 2017-07-12 21:57
An ebook is not a website in a box and Sigil is not a browser, nor a browser replacement.  External resources will not load on epub2 devices (they are illegal in the spec) and even most epub3 reading devices will not show external resources in iframes.

Please read the epub2 and epub3 spec and understand what Sigil is trying to accomplish.

Closing this as not a bug.

**Closed by kevinhendricks** 2017-07-12 21:57 UTC

**Comment by niroGH** [comment] 2017-07-13 09:57
Thany you very much.
Yes, I have read the spec, you are right.
