### ISSUE TITLE
Sigil introducing errors in to epub3

### ISSUE THREAD

**Issue by Tinker-Terry** [Sigil-Ebook/Sigil#367] opened 2018-07-03 16:33 UTC
Trying to convert epub2 to epub three. With 'mend xhtml on open'  I am trouble with getting my epub verified at epub check (http://validator.idpf.org/). Because the errors it indicated didn't make any sense i tried opening a verified error free epub to see what the css etc looked like in it. When I did so Sigil popped up a message that it had created an .ncx or opf file to make it backwards compatible with epub2. Lo and behold when I ran it through epub check again  it was showing several errors. It also doulbel up the TOC. The errors displayed don't make any  sense as they seem to point to empty line/column references.
The error reads:
ERROR | OEBPS/toc.ncx | 17 | 46 | Referenced resource could not be found in the EPUB.
The reference reads:
<content src="Text/Section0001.xhtml"/>*
(*)And line 17 column 46 is what the position indicator shows when I place the cursor where I put the asterix. There is no file >section0001.xhtml to be found anywhere in the book.

**Comment by kevinhendricks** [comment] 2018-07-03 17:31
No, it is doing exactly what it is created to do.  Sigil always adds a toc.ncx to an epub3 so that an epub2 only reader can generate a proper toc for the reading device..  It is the user's job to then generate contents for the toc.ncx by using the appropriate tools provided in Sigil.  That is what Sigil was designed to do.

If you have a valid (passes epubcheck) epub2, simply load it into Sigil and use the epub3-itizer plugin to convert it to a valid epub3.  

See our Sigil user forum on www.mobileread.com to get help deciphering your original epubcheck error messages, for help in using Sigil properly, and for access to the epub3-itizer plugin which should do exactly what you want.

Closing this as a user support request not a bug in Sigil.

**Closed by kevinhendricks** 2018-07-03 17:31 UTC

**Comment by Tinker-Terry** [comment] 2018-07-19 20:16
When I load an epub 2 (valid passed epub check with no errors) and then run
clean up html it has errors. When I run epbu 3izer on a valid error free
epub 2 it results in an epub 3 with a bunch of errors.

**Comment by kevinhendricks** [comment] 2018-07-19 21:30
Again, this is a user support thread not a Sigil bug or issue.  Please use Sigil's support forum on www.mobileread.com to get futher help.  Locking this issue as it is not the correct place to get user help for plugins.
