### ISSUE TITLE
New identifier element is added if EPUB file contains font files

### ISSUE THREAD

**Issue by Changilainen** [Sigil-Ebook/Sigil#179] opened 2016-02-01 11:19 UTC
Not sure if this is a bug or supposed to work like this.
If EPUB contains font files and the EPUB is saved in Sigil (0.9.3 and also some previous versions), new identifier element is added in content.opf file.
`<dc:identifier opf:scheme="UUID">urn:uuid:14b85803-3b65-4778-8640-0a07fc203e0a</dc:identifier>`
It can't be removed, it's added everytime the EPUB file is saved.

If EPUB doesn't contain font files and the EPUB is saved in Sigil, no identifier element is added.

**Comment by kevinhendricks** [comment] 2016-02-01 12:45
Yes, the font obfuscation algorithms (both IDPF and Adobe)  requires a dc:identifier with the correct format.  Closing this as not a bug.  Questions like this are better directed to our support forum on www.mobileread.com.

**Closed by kevinhendricks** 2016-02-01 12:45 UTC
