### ISSUE TITLE
wrong media type is set when inserting m4a audio (text/plain instead of audio/m4a)

### ISSUE THREAD

**Issue by shorshe** [Sigil-Ebook/Sigil#198] opened 2016-03-23 11:25 UTC
Inserting an .m4a audio file in an EPUB3 will result in the media type "text/plain" instead of "audio/m4a" in content.opf. This breaks playback in iBooks.

Sigil Version 0.9.4

     <item  id="Test01_Compressor_Preset_AAC.m4a" href="Audio/Test01_Compressor_Preset_AAC.m4a" media-type="text/plain"/>

**Comment by kevinhendricks** [comment] 2016-03-23 14:35
Since m4a is an Apple only creation and .m4a is a container file able to hold many audio formats, subtitles, etc, Sigil is not aware of it.  I can fix that but ... I am not sure what the official media-type should be.  A web search for epub media-type and .m4a files returned the following:

audio/mpeg
audio/mp4
audio/x-m4a

None of which match your audio/m4a.

What official reference did you get that media-type from?  Is it a recognized media-type for epub3?  Does epubcheck 4.0.1 recognize that media-type?

Kevin

**Comment by kevinhendricks** [comment] 2016-03-23 15:00
FYI
"audio/m4a"  is NOT a legal mimetype according to the official registration list:
    https://www.iana.org/assignments/media-types/media-types.xhtml

Nor is it on the list of epub3 recognized idpf core audio types so it will technically need a fallback.

From what I have read It appears that .m4a is simply just a made-up new extension by Apple for an .mp4 container audio format that is not officially recognized by anyone else.

My guess is if you rename the file to .mp4 and add it, all will just work.

**Comment by shorshe** [comment] 2016-03-23 16:49
Hi Kevin,

thanks for the clarification. I understand your point.
I'm producing an ePub just for the iBooks store and was following apple guidelines:
https://help.apple.com/itc/booksassetguide/?lang=en#/itc2288fb02e
where they propose audio/m4a.
They will indeed accept mp4:
"Video files must be H.264 in an MPEG-4 container and the file extension .m4v (.mp4 is allowed, but less preferable)."

**Comment by kevinhendricks** [comment] 2016-03-23 16:55
Actually without media-type info, a file with an .mp4 extension is mapped to mp4 video not audio.  So my suggestion would not work either.
Hmm..., Sigil will now recognize the .m4a as audio and the .m4v as video but without an official mimetype for those extensions/file types, I think .m4a should map to audio/mp4 and .m4v should map to video/mp4 and not audio/m4a and video/m4v respectively.  

That is unless you can site an official source for the latter set of media-types on Apple's site, the idpf site or the iana site which registers mimetypes.

**Comment by kevinhendricks** [comment] 2016-03-23 16:59
Our posts crossed.  To prevent issues with the epub3 core media types at least for audio, I will commit a fix to map .m4a to audio/mp4 and .m4v to video/mp4 media-types.

This fix will apoear in the next release (a regression fix release) hopefully by  this weekend.

Thanks for your bug report.

**Comment by kevinhendricks** [comment] 2016-03-23 17:21
Just committed the changes to recognize .m4a as audio/mp4 to Sigil and its plugin code.
Closing this as fixed for the next release.  If after the next release you still see a problem, please re-open the issue.

Thank you again for your bug report.

**Closed by kevinhendricks** 2016-03-23 17:21 UTC
