### ISSUE TITLE
Chapter split/division

### ISSUE THREAD

**Issue by LeoM49** [Sigil-Ebook/Sigil#324] opened 2017-12-06 09:12 UTC
Hi, I just downloaded the latest version of sigil on my Windows 64 PC. I was missing the tick button for validation and found out that I had to downlod flightcrew as a plugin. Solved! But I have no idea where the button "Chapter split" (I do not know the exact name) has been gone - with which I can easily generate  a new chapter within a text. Please help.

**Comment by kevinhendricks** [comment] 2017-12-06 12:02
Closing as this is not a bug. As explained in the README on this site, this is for bug reports.  Please use our User Support forums on www.mobileread.com for user questions and help related to Sigil.

**Closed by kevinhendricks** 2017-12-06 12:02 UTC
