### ISSUE TITLE
[Bug Report] Preview is broken in Sigil 1.5.1 on macOS 10.14

### ISSUE THREAD

**Issue by laggardkernel** [Sigil-Ebook/Sigil#608] opened 2021-04-12 04:58 UTC
### environment

- macOS: 10.14.6
- sigil: 1.5.1

### Behavior
The preview is broken. Only a blank page is displayed. Besides, image files are not display (blank page) either when opened with double clicking the image.

What I've tried:

- Delete sigil conf `~/Library/Application Support/sigil-ebook`
- Delete sigil cache `~/Library/Caches/sigil-ebook`

The problem still exists after deleting the sigil conf, cache.

**Comment by laggardkernel** [comment] 2021-04-12 05:09
Downgrading to 1.4.3, or 1.3.0 doesn't solves the bug. Maybe the problem is not related with sigil?

**Comment by kevinhendricks** [comment] 2021-04-12 12:47
It is not.  Sigil is compiled and built on macOS 10.14.6 on my iMac dev machine and believe me when I say it works just fine on it and all of my macOS machines.

You have probably installed something on your system that is interfering with Sigil, or you have installed a third party video driver or third party open gl library.

Are you using homebrew or something like that by chance?

**Comment by kevinhendricks** [comment] 2021-04-12 12:50
Hmm, if image files are not loaded, you may be seeing Sigil's URLInterceptor preventing you from opening something or you have not given Sigil permission to access your tmp folder?

**Comment by kevinhendricks** [comment] 2021-04-12 13:01
Have you installed it someplace unusual?  Are you using a third party anti-virus program by any chance that is interfering?  Both Preview and Image display  use Qt's QWebEngine Framework for displaying.  This Framework (part of Sigil) is the one being interfered with.  It is basically a version of the Chrome browser modified and adapted by Qt.  Does the chrome browser work on your machine or is it broken as well?

**Comment by laggardkernel** [comment] 2021-04-13 07:04
@kevinhendricks Thanks for your tips. After trying, I finally find a way to reproduce this bug. Seems related with GPU acceleration of the terminal apps.

1. Open Sigil and make sure preview works.
1. Open a terminal app with GPU acceleration. e.g. kitty, or iTerm2 with GPU renderer enabled.
1. In the terminal, run command `tree` in your home dir, and interrupt it with <kbd>Ctrl-C</kbd>
1. Quit Sigil and reopen it. Now the preview is broken.
1. Put your macbook into sleep. The next time you wake it up, the Sigil preview works again. (may need to wait some time, I waked up my macbook the next day)

**Comment by kevinhendricks** [comment] 2021-04-13 12:25
I have no idea why a terminal program would need gpu acceleration in any  way different from what Terminal.app provides.  So I would file a bug with those third party apps.  My guess is they are using older versions of Qt somehow or are changing the system path in some way.

Closing this as Sigil works just fine on macOS.

**Closed by kevinhendricks** 2021-04-13 12:25 UTC

**Comment by laggardkernel** [comment] 2021-04-15 12:00
@kevinhendricks Apologies for iTerm2 and kitty. This is related with Sigil and Calibre, not with terminals.

Preparation: Import a epub book into Calibre. At the right panel, find "Formats: EPUB". Right click it "Open EPUB with ..." -> "Add other application for EPUB files ...", then choose Sigil. Now we can find Sigil under "Open EPUB with ..."  -> "Sigil".

Step to reproduce

- In Calibre, choose "Open EPUB with ..."  -> "Sigil". At the 1st time, we may need to quit Sigil with <kbd>Command-Q</kbd>
- Again, choose "Open EPUB with ..."  -> "Sigil". This time, the ebook we imported is opened in Sigil. Besides that, another **empty ebook** is opened in another Sigil window, on top of the imported ebook. (this is what you to see)
- If there's an empty ebook, close the empty ebook, navigate the real ebook we want open, check the preview.

**Comment by dougmassay** [comment] 2021-04-15 13:02
Yes. The Open With feature (or the older plugin) of calibre quite often causes issues with Sigil. We don't support launching Sigil in this manner (even thought many people seems to be able to do so with no issues). If the issue cannot be reproduced with calibre taken out out of the equation, we're not too likely to tackle it.

**Comment by kevinhendricks** [comment] 2021-04-15 13:25
In other words Calibre's Qt environment is interfering with Sigil's in some way.
