### ISSUE TITLE
Copy Paste in File Names

### ISSUE THREAD

**Issue by DH95035** [Sigil-Ebook/Sigil#276] opened 2017-02-02 22:03 UTC
When editing a file name, if only part of the filename is selected, 'Copy' incorrectly copies the entire file name not just the selected part.  As a result, attempting to paste the selected text into another file name doesn't work correctly.  Also, when selecting part of a filename 'Paste' replaces the entire filename not just the selected portion.  Also, per standard GUI convention, clicking a filename and hovering over the name should open the name for editing.  Currently this doesn't do anything - the only ways to edit a filename are Ctrl-Alt-R and right-click / select 'Rename...'.

**Comment by dougmassay** [comment] 2017-02-02 22:11
I don't experience any of the copy/paste issues you're having when editing filenames in the Book Browser on Windows or Linux. I can copy/paste all or any portion of the filename I wish to.

As to:

>Also, per standard GUI convention, clicking a filename and hovering over the name should open the name for editing.  Currently this doesn't do anything - the only ways to edit a filename are Ctrl-Alt-R and right-click / select 'Rename...'.

Those are the only ways to rename a file in the Book Browser we're willing to offer. I'm not sure what "GUI convention" you're referring to, but we're not interested in offering that method for renaming filenames in Sigil's Book Browser at this time.

**Comment by kevinhendricks** [comment] 2017-02-03 02:41
I can not recreate this on Mac OS X either.  You can use Sigil Preference Setting to set the key sequence for doing a Rename.  Be careful if you are on Mac OSX because many of these key sequences are absorbed at the OS level.  Alternatively, you can use the right click.  

In both case you can easily cut and paste fragments of names quite easily into other filenames or anywhere (the fragments are properly copied to the clipboard).

If you single click on a name in the BookBrowser or a group of file names, you are selecting that file  or files for other operations to be done later (such as plugins or block rename or ...) not just trying to rename it.  Hover is used to show semantic settings.  This is not a File Browser.

Closing this as I can not recreate it either and click and hover will not be implmented as it is part of group selection process.

**Closed by kevinhendricks** 2017-02-03 02:41 UTC

**Comment by DH95035** [comment] 2017-02-09 19:29
Doug,

I don't think you understood my posting, so I'll try to be more specific
with examples that you will be able to recreate.

 

Regarding copy/paste, when editing an epub document, if I have a filename
inside the epub file such as "Against the Fall of Night Prologue.xhtml" and
decide to split the file using 'Split at Cursor', it creates a new file
called "Section0001.xhtml".  I want to rename that file to "Against the Fall
of Night Chapter 1.xhtml". What I would like to do (and what works when
editing filenames directly in Windows) is to edit the original file and
select just the "Against the Fall of Night " text and paste it into the new
file name.  This does not work in Sigil.  Currently, if I select only the
"Against the Fall of Night" text, right click and select 'copy' then edit
the new filename, select just the "Section000" text, then right-click &
'paste,' it replaces the entire "Section0001" filename not just the selected
text.  This is not per Windows GUI convention.  Try this on a filename in
Windows and it will work correctly as I described.

 

Regarding renaming a file in Sigil, try opening any Window in Windows and
clicking on a filename.  If you click on that same file again, the text of
the name will be selected for editing. You can then type new text for the
file name or click/drag in the selected text and replace only part of the
name. That is what I mean by "Windows GUI convention".  All I am saying is
that in Sigil, this doesn't work the same way. Clicking on a file name
selects the file but clicking on it again doesn't do anything, the click is
ignored.  This not a major issue, but I've been using Windows very long time
and this is second nature to me so it is somewhat irritating in Sigil to
have to take the extra step to 'right-click, edit file', so it would be
nice, as a convenience and time-saver for your users, if you could fix it at
some point.

 

I'm using Windows 7 but this has worked the same since Windows was first
introduced and I think works essentially the same on Macs.

 

Dean Hays

 

  _____

**Comment by dougmassay** [comment] 2017-02-09 19:45
I understood you perfectly the first time. I simply can't reproduce the issue you're describing on Windows or Linux with the latest version of Sigil. And Kevin can't reproduce it on a Mac. Copying or pasting all, or portions of filenames works exactly as it should when renaming files within Sigil. I don't know why you're having difficulty, but it's clearly not an inherent problem of Sigil's

As to the second part of your question: asked and answered. Sigil's Book Browser is not a native OS-level file browser. It is not intended to--nor is it going to in the future--work in the manner you wish it to. Right-clicking and selecting Rename is (and will continue to be) the only way to rename a file within an epub being edited with Sigil.
