### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cmcknight** [Sigil-Ebook/Sigil#688] opened 2022-06-23 22:13 UTC
### Bug Description

Sigil throwing parse error on '@' symbol.

### Platform (OS)

macOS

### OS Version / Specifics

12.4. (M1 iMac)

### What version of Sigil are you using?

1.9.10

### Any backtraces or crash reports

```shell
This page contains the following errors:
error on line 10 at column 50: error parsing attribute name
Below is a rendering of the page up to the first error.

Minimal Test Case:


<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
  <title></title>
</head>

<body>
  0: (SWANK::DEBUG-IN-EMACS #<UNDEFINED-FUNCTION @ #x716b082a>)
</body>
</html>
```
```

**Comment by kevinhendricks** [comment] 2022-06-23 22:21
As far as I can tell, that is not a bug.  Your xhtml is just not valid (what you have above is not valid xhtml).  

Please post the original xhtml page you are actually trying to load.  Zip it up and attach it to this issue.

**Comment by cmcknight** [comment] 2022-06-23 22:39
Here you go.


[sigil-issue-688.zip](https://github.com/Sigil-Ebook/Sigil/files/8971794/sigil-issue-688.zip)

**Comment by kevinhendricks** [comment] 2022-06-23 23:20
Closing thisa.  See my response on your mobileread thread.  You can not have bare "<" and ">" in text xhtml.  They must be xml encoded.

This is not a bug.

**Closed by kevinhendricks** 2022-06-23 23:20 UTC
Labels: info
