### ISSUE TITLE
Allow multiple replacement with "Add existing files"

### ISSUE THREAD

**Issue by hantsaniala** [Sigil-Ebook/Sigil#421] opened 2019-05-08 13:37 UTC
Sometimes, I need to replace all of the graphics inside the ePub. So after adding them all again, I must confirm one by one for replace existing file. This process is getting annoying after clicking multiple time. 😕 
By the way, many thanks for the great work.

**Comment by kevinhendricks** [comment] 2019-05-08 14:18
Have you thought about using a plugins? Sigil has FolderIn and FolderOut plugins that would make mass replacement much easier using your own OS commands once saved to a folder.  

As mass replace of files can be dangerous and I am leery of making this any easier for the very few use cases that would require it.

**Comment by kevinhendricks** [comment] 2019-05-09 02:53
I am closing this as it is a duplicate of issue #99.

**Closed** 2019-05-09 02:53 UTC

**Comment by hantsaniala** [comment] 2019-05-09 05:45
Thanks for the reply. I've never though about using plugin but I'll search for another way to do it before scripting. But anyway, I think, replacing multiple files is not a few use cases. But  that's my opinion only.

Thanks again for the great work 👍

**Comment by kevinhendricks** [comment] 2019-05-09 13:31
The FolderIn and FolderOut plugins already exist and are stored in the Sigil forum on Mobileread.  Once saved to a folder, a drag and drop of new images into the Images subfolder inside should work and then FolderIn can be used to load up Sigil.

I have closed this only as a duplicate and not the original issue as this is still a valid issue that should be addressed at some point but it is very very low on my priority list as valid workarounds exist and are relatively painless, and I am leery of what damage could be done by newer users..  Hope that makes things a bit clearer.
