### ISSUE TITLE
[Bug]: Case-Sensitive Renaming Of Image Or Text Files Not Possible (Minor Issue)

### ISSUE THREAD

**Issue by KarlG1965** [Sigil-Ebook/Sigil#750] opened 2024-04-06 05:40 UTC
### Bug Description

Let's say an epub has a file called Cover.xhtml. 

I wish to rename it to cover.xhtml, but Sigil tells me that the name is already in use. 

I get the same error message when trying to change the case of an image name. 
e.g. change CH01FIG01.jpg to ch01fig01.jpg

As a workaround, I can rename the file something like Covera.xhtml and then rename again to cover.xhtml, but it would be nice to avoid this additional step.

### Platform (OS)

Linux

### OS Version / Specifics

Xubuntu 23.10

### What version of Sigil are you using?

current from git

**Comment by dougmassay** [comment] 2024-04-06 11:59
That's not likely to change. Sigil being the cross-platform program it is, we often have to cater to the lowest common denominator of the ones we support (where issues are concerned). In this case that's Windows and its general case-insensitivity.

**Comment by KarlG1965** [comment] 2024-04-06 12:30
What about adding an additional step? Mv Cover.xhtml -> abcde.xhtml (or some random name). Mv abcde.xhtml -> cover.xhtml.

As it's only one file at a time, I don't think the overhead from the extra step would be noticed, and that would also work on Windows.

**Comment by kevinhendricks** [comment] 2024-04-06 12:42
That is a feature request not a bug, as Sigil must operate on both case sensitive and case insensitive file systems.

Closing this as it is not a bug report.  This was done by design.

Feature requests belong in Mobileread and not here.

**Closed by kevinhendricks** 2024-04-06 12:42 UTC
Labels: bug

**Comment by KarlG1965** [comment] 2024-04-06 12:45
Understood. I'll create a feature request on Mobileread
