### ISSUE TITLE
Sigil Issue for Bengali Unicode

### ISSUE THREAD

**Issue by debavasya** [Sigil-Ebook/Sigil#533] opened 2020-07-11 12:05 UTC
Bengali Unicode is not supported in Sigil code editor. In the preview section the rendering seems to be fine. But when saving the work in epub version and reading the same in readers format issue coming again. Means the final epub book is not supporting Bengali as code editor. Please find the screenshot below for the issue:
![Issue](https://user-images.githubusercontent.com/68150934/87223635-36cde880-c39c-11ea-90cb-47caa1246f42.PNG)

**Also giving here the Sigil Preferences Appearance Screen Shot for your reference:**
![Issue1](https://user-images.githubusercontent.com/68150934/87223714-bc519880-c39c-11ea-95d6-b730ae82ce59.PNG)

As I am new to Sigil please advice me if I am missing anything.

**Comment by dougmassay** [comment] 2020-07-11 12:19
Sigil has no control over whether or not your target reading device will support your font of choice. If the device doesn't already have the font installed on it, you will need to embed the font in your epub (that's an epub topic and not a Sigil topic, by the way).

**Comment by debavasya** [comment] 2020-07-11 12:30
May I know how we can fix the font issue in Sigil code editor?

**Comment by dougmassay** [comment] 2020-07-11 13:00
Does Noto Mono claim full support for Bengali monopspace unicode glyphs? To properly display monospace Begali unicode glyphs in Sigil's Code View, the monospace font selected in preferences must support monospace Begali unicode glyphs. The list of monospace fonts that fit that particular bill is pretty short, I believe.

**Comment by kevinhendricks** [comment] 2020-07-15 00:59
This is not a Sigil issue.  If you install a monospaced font that supports your language, CodeView will work.

The remaining issue is about how to embed a font into an epub.  This is really an issue for our support forum, not a bug.

So closing this as not a bug report.

**Closed by kevinhendricks** 2020-07-15 00:59 UTC
