### ISSUE TITLE
Insert File issue：there is sudden noise  when you open the pub file before you has insert mp3 file.

### ISSUE THREAD

**Issue by survagchron** [Sigil-Ebook/Sigil#240] opened 2016-09-04 12:56 UTC
Hi everyone,
I want to make audio book for prepare some exam, but there has a problem, I insert some mp3 file(more then ten) in the audio book but when I open the pub file again by Sigil that make many noise .... have any idea?

OS:windows 10
Sigil: 0.9.6

**Comment by survagchron** [comment] 2016-09-04 13:11
Hi everyone,
I find the reason for the noise sound issue, when I enable the "Preview window(F10)" that make the noise problem issue. Now... I closed the Preview windows to fix the problem. thanks all.

**Comment by survagchron** [comment] 2016-09-05 12:09
Hi everyone,
the sudden noise still current when I open the epub file that include mp3 file.

**Comment by dougmassay** [comment] 2016-09-05 13:16
I am not at all certain what the issue is you're reporting. Can you provide step-by-step instructions to reliably reproduce the problem you're experiencing?

**Comment by survagchron** [comment] 2016-09-08 06:58
Hi Doug Massay,
please check this file =>https://github.com/survagchron/examples/raw/master/sudden%20noise%20issue%20example.epub

Just open it and the sudden noise on my computer. 

My computer OS and epub status:
1.Windows 10 (64 bit)
2.Audio Files use the Audacity to record the sound then insert to Sigil.

thanks you notice this personal issue.

**Comment by kevinhendricks** [comment] 2016-09-08 16:31
FWIW: The file opens without any noise and plays properly on Sigil for Mac OS X.  This may in fact just be a sound driver issue specific to your machine or a platform specific Qt bug of some sort.

**Comment by dougmassay** [comment] 2016-09-08 17:38
I can duplicate the issue on Vista. The epub opens with what sounds like each clip trying to play one after the other (like there's some sort of auto-play feature enabled when the epub opens). This is  followed by a Sigil Error with the following info:

Error info: Critical: QThread::start: Failed to create thread (The access code is invalid.)

That error repeats 5 times but Sigil never closes like it says it's going to. Once the errors stop, it will play the first audio clip I try, but quickly stops responding and hangs. Sigil must be forcibly closed.

I'll check on Windows 7 (I don't have access to Windows 10).

**Comment by dougmassay** [comment] 2016-09-08 18:31
On Arch Linux, Sigil immediately hangs when trying to play any of the epub's audio tracks, or even just switch from Code View to Book View (or vice-versa). None of the tracks play.

Definitely sounding like a codec issue, but the CV to BV switching has me worried.

**EDIT:** installing the gst-plugins-good package (gstreamer plugins) solved all hanging/playing issues on Arch Linux. Looking more and more like a codec issue on Windows.

**Comment by kevinhendricks** [comment] 2016-09-08 18:32
Is this with Qt 5.4 or Qt 5.6.1?  

FWIW a similar bug existed in earlier versions but this might not be related:

QTBUG-34658:    WMF: Media playback starts automatically after loading
https://bugreports.qt.io/browse/QTBUG-34658

**Comment by dougmassay** [comment] 2016-09-08 18:41
The Windows Vista test was with 5.6.1

5.6.1 on Linux as well (but I don't think there's an issue there--only missing codecs on my part).

**Comment by dougmassay** [comment] 2016-09-08 19:06
No hanging or crashing on Windows 7 (with Qt5.6.1), but the autoplay thing (every single track it seems) happens if Preview or Book View is open when Sigil starts. It also occurs each time Preview is opened. Tracks will play Ok after, though.

With Book View AND Preview visible at the same time, initiating playback from Book View has the added feature of repeating the garbled sound (the auto play of every track) after playback of each track. It seems Preview is reloading after playback is initiated from Book View causing the sound.

**Comment by kevinhendricks** [comment] 2016-09-08 19:20
Preview once started is auto-reloaded by a timer every so often so that is scrolls to keep up with your editing in CodeView.  So yes, it will constantly reload the page as it is edited, it was designed that way.

So the real question is why do any of these audio files play at all on load, ever.  They should not.

**Comment by dougmassay** [comment] 2016-09-08 19:23
Explicitly setting all audio tags' preload attributes to "none" makes the problem go away on Windows. Not at all sure what to make of that.

Whatever is happening, it's not autoplay. Explictly setting the autoplay attribute will truly display what the auto play of all those tracks sounds like!

**Comment by kevinhendricks** [comment] 2016-09-08 22:18
If it plays, then it is not a codecs issue on Windows.  Most probably a Qt bug in the audio code or multimedia plugins.  If you built the Qt examples when building Qt from source, you should have access to a QWebEngine based demo browser.  We could try unzipping the epub and loading the html file directly in the demo browser to see if it gets the same noise.  If so, it is probably in the multimedia plugins and not webkit vs webengine.  I have tried everything on Mac and can not create any issues.  It is rock solid.

**Comment by dougmassay** [comment] 2016-09-08 23:14
All I can say is: make sure you add preload="none" to audio tags if you're working with Sigil on Windows. If you need stuff to auto-play, then the autoplay attribute will cause the preload attibute to be ignored.

I'm still getting Qt Thread errors (tons of them) on Windows Vista (even with the preload="none" addition), but I have a feeling that's something else. Probably (low) memory related. I'll see if it can get more info on that. Not quite ready to abandon Vista as a platform yet. Even if some audio/video stuff won't play on Vista, I'd like to eliminate the errors/crashes if possible.

**Comment by dougmassay** [comment] 2016-09-09 12:26
The problem wasn't introduced with Qt5.6.1, by the way. The epub provided behaves the exact same way with the stock 0.9.6 release (Qt5.4.2). But it must have something to do with the sheer number of audio tracks, as test epubs with one or two tracks embedded don't exhibit the noise upon opening.

I have options when building Qt for Windows of whether to use the Windows Media Foundation engine for multimedia or Directshow. The former is newer, but the latter can be more stable (but might mean specific directshow codec filters will need to be installed by the end user that wants to make use of audio/video).

I'll have to do some experimenting before we go live with the next version.

For now, I recommend the preload="none" workaround. It doesn't seem to barf anything up on the other platforms.

**Comment by dougmassay** [comment] 2019-02-01 00:01
The audio playback controls in QtWebKit (WMF) for Windows is badly broken. I'm closing this issue as "Can't Fix." If I find some free time, I may kick this issue upstream, but I don't hold out much hope. QtWebKit development is simply not very active.

**Closed by dougmassay** 2019-02-01 00:01 UTC
