### ISSUE TITLE
Sigil's offer to "fix" files results in file structure that is incompatible with Apple Books (iBooks)

### ISSUE THREAD

**Issue by jlhopes** [Sigil-Ebook/Sigil#652] opened 2021-11-14 20:30 UTC
After creating a new EPUB book with InDesign (or in some cases, opening a pre-existing EPUB), when I open it with Sigil (v. 1.8.0), Sigil offers to "fix" the file (see attached screenshot). I've discovered that this "fix" changes the file structure of the EPUB, so that files like images are no longer in their own folder. This change doesn't affect most e-reader devices, but when opening these EPUBs with Apple Books (iBooks), the images no longer display. Once I change the file structure to have the images in their own folder, Apple Books can display the images properly again.
![Screen Shot](https://user-images.githubusercontent.com/24940562/141697514-3f3b68e3-4fce-4bb1-b56c-f8594a58d094.jpg)

**Comment by kevinhendricks** [comment] 2021-11-14 20:40
No.  That message indicates that your epub xhtml files have no <!DOCTYPE> which is a requirement according to the epub spec.  It only fixes / mends xhtml files nothing else. 

Nothing in Sigil 1.0+ moves anything around to create any folders anymore.  

The BookBrowser Window in Sigil is not showing physical paths of files but virtual grouping by media-type.  Simply mouse-over the file in Sigil's BookBrowser's window and the tooltip will show the physical path to the file.  If you would prefer to always see the the physical path, then use Sigil's Preferences to set it to show the full book path.

There are also a pop-up menu  items to create new phyical folder and to move files around between folders.

If you have trouble with files showing up in specific readers, you should run the epubcheck validator plugin and fix any errors it reports.  I have no idea why iBook fails to show images from the root of the epub as technically that is valid under the epub 3 spec.  I would file a bug report with Apple's iBooks if that turns out to be the case.

Closing this as expected behaviour since you seem to misunderstand what that "fix" files is really doing.
Feel free to post here and if needed I can and will re-open the issue.

**Closed by kevinhendricks** 2021-11-14 20:40 UTC

**Comment by jlhopes** [comment] 2021-11-14 21:29
Thank you for your quick reply. I'm very sorry, I didn't check thoroughly enough to find out that Sigil wasn't causing the change in file structure. In that case, maybe it is due to a change in InDesign's epub export? I will look into it. And I will contact Apple too, for sure. Thank you again!

**Comment by kevinhendricks** [comment] 2021-11-14 21:48
If iBooks needs things to be moved to folders like pre-Sigil 1.0 versions always did, you can elect to use the "Restructure Epub to Sigil Norm" in the Sigils Tools menu after loading the epub.  It will covert things to use the more typical folder structure and update all links for you automatically

OEBPS/
OEBPS/Text
OEBPS/Images
OEBPS/Styles
...

**Comment by jlhopes** [comment] 2021-11-14 22:44
Okay, thank you, that is good to know. This was the first ebook that I made after updating my OS and upgrading to a post-1.0 version of Sigil. So now I'm guessing that InDesign has never exported EPUBs with that folder structure, and in the past when I opened them in Sigil after exporting, Sigil restructured it. I just wasn't aware of it before; now I know I need to do the extra step to make sure it's compatible with iBooks. Thank you!
