### ISSUE TITLE
Support for 4k/hi dpi screens

### ISSUE THREAD

**Issue by MazenS** [Sigil-Ebook/Sigil#226] opened 2016-06-19 23:49 UTC
Ello, great bit of software. 
Wondering if there is a fix or possible support for 4k/hi dpi screens as all the icons are a bit tiny.

Thanks
![sigil](https://cloud.githubusercontent.com/assets/11826437/16180570/c98a23da-3680-11e6-90f4-4122b2ef3c74.jpg)

**Comment by kevinhendricks** [comment] 2016-06-20 01:37
What OS and version?  I have a retina display on my Mac and the icons are normally sized even with the 27 inch monitor in highest res.  Does you OS properly scale things for your display?

**Comment by MazenS** [comment] 2016-06-20 15:03
Running Windows 10, it seems to be application dependant - until only recently 3DS Max had tiny icons.
90% of programs work correctly, I seem to be a fan of the 10% that don't.

**Comment by ScotsScripts** [comment] 2016-06-20 16:20
Yeah, icon sizes in apps on Windows 10 on a surface pro are application 
dependent. Photoshop and others on the surface still have tiny icons. 
Most big software names are fixing their software to run on these kinds 
of monitors but it seems to be a very slow process. More and more 
monitors are going to be like this, though, so putting at least a choice 
in icon size in the configuration might be a good start.

On 6/20/2016 8:03 AM, MazenS wrote:
> Running Windows 10, it seems to be application dependant - until only
> recently 3DS Max had tiny icons.
> 90% of programs work correctly, I seem to be a fan of the 10% that don't.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Sigil-Ebook/Sigil/issues/226#issuecomment-227169408>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/AChB68sitg4I6lGsuBc23-8U0VgoVWWNks5qNqvagaJpZM4I5R4q>.
>

-- 

----------------------

http://www.scotsscripts.com
Miva Scripting since 1996

**Comment by MazenS** [comment] 2016-06-20 16:52
I'm on a laptop. 
Paint.Net gets around it by having an option to set base dpi, which shouldnt be too awkward a solution?
(I know nothing on how to implement)

**Comment by dougmassay** [comment] 2016-07-30 15:57
If anyone is still tracking this issue (with a Windows 10 4K monitor), I'm going to post a link (Google Drive) to a beta version of Sigil that uses a newer version of Qt5 which is supposed to offer better support for scaling on high-dpi monitors. If anyone would like to test it and get back to me, I'd sure appreciate it.

If you do download the installer, please drop a note here to let me know. I'm not going to leave the link here indefinitely.

https://drive.google.com/open?id=0BwuQyKLvJUjyMkw2aDRwT2RWR3c

**Comment by gengjiawen** [comment] 2016-08-02 01:45
@dougmassay nope, the icon in toolbar still too small.

**Comment by dougmassay** [comment] 2016-08-02 02:41
@gengjiawen Thanks for downloading/testing. There are some settings introduced in Qt5.6 that can be manipulated (with environment variables and with application settings). If you would be willing to do some testing, I'd appreciate it.

First up would be to create an environment variable called QT_AUTO_SCREEN_SCALE_FACTOR and set it to 1 (boolean).

If you could let me know if that makes any difference whatsoever, that would be great. 

The environment variable would affect any Qt application using Qt5.6 or higher, so don't forget you've set it.

**Comment by gengjiawen** [comment] 2016-08-02 03:04
@dougmassay now toolbar icon is a little big,and content area is bit of unreadable because of scale.

**Comment by kevinhendricks** [comment] 2016-08-02 12:42
@dougmassay  We may have to use QCoreApplication's SetAttribute in main.cpp to set the following attribute:  Qt::AA_EnableHighDpiScaling to true following this comment on the Qt site:

"The application attribute Qt::AA_EnableHighDpiScaling, introduced in Qt 5.6, enables automatic scaling based on the pixel density of the monitor."

This then should enable auto scaling as is done automatically for Mac OS X.

Not sure if the environment variable does that or not.

**Comment by dougmassay** [comment] 2016-08-02 12:54
@kevinhendricks Yes. The environment variable does the same thing (according to my reading, anyway). Either should make the app dpi "unaware" and use the pixel density that the OS reports.

I think our hi dpi problems are more complicated than that. I don't think our icon resources are providing a viable choice for Qt's QIcon to choose from on hi-dpi monitors. I'm guessing that the 16x16 and 24x24 options are too limiting. I admit I'm terribly unfamiliar with Qts icon resource scaling process, but it seems to me that we may need to provide higher pixel-count versions of Sigil's various icons if we have any hope of supporting higher resolution mnotors on Windows. Even if the scaling factor is forced manually, the icons will develop artifacts and likely look horrible.

We need a Windows Qt Gui-guru, I fear.

**Comment by dougmassay** [comment] 2016-08-02 12:57
Can qt stylesheets offer the hi-dpi users any possible relief in the meantime?

**Comment by kevinhendricks** [comment] 2016-08-02 13:03
Hi Doug,

I am really not sure.  I don’t understand why this all works for the Mac with a retina display but does nto just work on Windows.  Something is strange.  I guess we could try having the user change:

	• QT_SCALE_FACTOR [numeric] defines a global scale factor for the whole application, including point sized fonts.

Setting it equal to 2 and getting a screenshot just to see what the differences are.

Kevin

**Comment by dougmassay** [comment] 2016-08-02 13:11
I have a feeling that Mac's floating-point scaling is simply better than Windows'.

The QT_SCALE_FACTOR variable will certainly make a difference, but I doubt it will look acceptable. We can hope, though!

**Comment by kevinhendricks** [comment] 2016-08-02 13:22
The problem is there are really many many ways to deal with this on Windows and so we don’t know what people have set as minimum font sizes, and etc of their own, enabled some internal scaling, etc.  And from reading the docs, these things are said to be multiplicative.

As for icons, to get high dpi versino0s we just provide them as twice as large in pixel dmiensions right?  So we go from 16x16 pixel icons to 32 x 32 icons, and similarly 24x24 would become 48x48?

Any idea how to do that in Gimp, or any other image processing program?  I really do not want to have to design pixel by pixel larger versions of all of our icons.  I had a hard enough time just adding 3 little dots to the bottom of the plugin electric cord plug icon and dread having to make a 4 dot one!

**Comment by dougmassay** [comment] 2016-08-22 01:43
@gengjiawen @MazenS 

Another Windows beta version of Sigil to try for anyone who may still be tracking this issue (who has a hi-dpi monitor).

Uninstall any other versions of Sigil and delete/unset any of the environment variables that were experimented with in the older beta test before installing/launching this new beta.

Any input/screenshots would be greatly appreciated.

Again: it's a 64-bit beta version of Sigil uploaded to my Google Drive.

https://drive.google.com/open?id=0BwuQyKLvJUjyQnpDVHR2TnZRWUU

**Comment by gengjiawen** [comment] 2016-08-23 09:07
@dougmassay This version works fine :)

**Comment by dougmassay** [comment] 2016-08-23 09:50
@gengjiawen Yeah, a few of the icons mght need a little tweaking, but it looks lke we have the scalng working properly. Thanks so much for reporting back!

**Comment by dougmassay** [comment] 2016-08-24 01:47
Closing this issue, as I think we have a pretty good road map to success. Sigil will be much more hi-dpi-compliant as of the next version. Thanks to all who helped.

**Closed by dougmassay** 2016-08-24 01:47 UTC
