### ISSUE TITLE
"Restructure Epub to Sigil Norm" changes values in quotation marks

### ISSUE THREAD

**Issue by richilton** [Sigil-Ebook/Sigil#592] opened 2021-02-22 19:32 UTC
Open an ePub containing a CSS file that is **not** in a folder called `Styles`, and select `Tools > Restructure Epub to Sigil Norm`. Any CSS values in quotation marks will be URL-encoded and prefixed with `"../[name of original CSS folder]"`.

For example, the following CSS is changed from...
```
div {
	content: "this is a test string!";
}
```
...to...
```
div {
	content: "../css/this%20is%20a%20test%20string%21";
}
```
A [minimal example](https://github.com/Sigil-Ebook/Sigil/files/6024677/Test.zip) is attached (renamed to .zip so GitHub would allow the upload!).

Sigil version: `1.4.3`
Loaded Qt: `5.12.9`
Platform: Windows 10

**Comment by dougmassay** [comment] 2021-02-22 19:46
All quoted strings? Or just quoted strings that are part of a content attribute's value.

**Comment by kevinhendricks** [comment] 2021-02-22 21:45
Hopefully the latter.  We will need to narrow down our css updates regular expressions we use to try to detect this case.

**Comment by kevinhendricks** [comment] 2021-02-22 21:49
Also we may want to consider incorporating our new css parser into this regular expression css updating process to help rule out things we should not touch.  It might help.

**Comment by kevinhendricks** [comment] 2021-02-23 00:12
Looking at PerformCSSUpdates because of @import we support updating  paths  in quotes as @import can use a path in quotes instead of the url() function.  We also look for url() as part of content: but because of what we do for @import we are catching things in quotes following content: incorrectly.


One solution is to handle @import with just a quoted path separately.

Thoughts?

**Comment by richilton** [comment] 2021-02-23 09:19
> All quoted strings? Or just quoted strings that are part of a content attribute's value.

It appears to be selective. 
```css
div {
	content: "Test String";
	background-image: url("Test String");
	background-image: url('Test String');
	cursor: url("Test String");
	quotes: "“" "”" "‘" "’";
	font-family: "Test String";
	invalid-property: url("Test String");
	margin: "Test String";
	"Test String";
}
```
...becomes...
```css
div {
	content: "../css/Test%20String";
	background-image: url("../css/Test%20String");
	background-image: url('../css/Test%20String');
	cursor: url("Test String");
	quotes: "“" "”" "‘" "’";
	font-family: "Test String";
	invalid-property: url("Test String");
	margin: "Test String";
	"Test String";
}
```

**Comment by dougmassay** [comment] 2021-02-23 11:33
The content property handling is definitely a problem we'll look into, but I'm not certain it's feasible to suggest that Sigil leave broken urls alone (or that it be able to automatically fix them). Anything wrapped in url() in a property that CAN contain an url will be treated as an url (and will be url escaped as necessary). And if that url is invalid to begin with, it's highly likely to be invalid after.

**Comment by richilton** [comment] 2021-02-23 11:40
Yes, the `content` property was where I first noticed the problem. The tests in my previous post show that it is choosy about which properties it updates. Not sure if that is deliberate, but it is interesting to see that it changes the `url()` value for `background-image` but not `cursor` or `invalid-property`. And the only non-url() string it touches is `content`.

**Comment by dougmassay** [comment] 2021-02-23 12:02
Other than the content property, the choosiness is definitely deliberate. There are only certain properties where Sigil recognizes that urls can be present according to spec. Cursor is not in that list because of an oversight. And invalid-property is exempted along with the several billion other  invalid css properties not listed in the regex that's currently being asked to determine which css properties have urls that need updating under these conditions. ;)

**Comment by dougmassay** [comment] 2021-02-23 12:23
@kevinhendricks : both of your suggestions seem reasonable to me. If dealing with @import separately will simplify things for the current regex, I'm in favor of it. In a perfect world, I'd also  love to be able to eliminate the need to constantly update/curate the list of properties that are ALLOWED to contain urls. And if our new css parser would prevent the updating of things that only _appear_ to be urls, I say we try to incorporate it.

**Comment by kevinhendricks** [comment] 2021-02-23 14:55
We would have to change the parser code to explicitly add a state to mark urls.  So let's make that a long term goal.

So the idea is to search for all leading elements that may contain a url:

If @import we look for url() and quotes for source updating
ow: we just look for url()

You are better at regex with lookahead and look behind than I am.  Would you take a shot at fixing it?  If you do not have time, just let me know and I will take a shot at it.

BTW: according to MDN the elements that can have a url() associated with it are:

```
The url() function can be included as a value for background, background-image, list-style, list-style-image, content, cursor, border, border-image, border-image-source, mask, mask-image, src as part of a @font-face block, and @counter-style/symbol
```

which is quite the list!   If RE is not the way to go for this, we can use our css parser to do basic parsing and keep state ourselves outside of it and then use simpler regex based on state of the parsing.  So a mix of parser and regex expressions.

**Comment by kevinhendricks** [comment] 2021-02-23 14:58
Just let me know how you think we should proceed.

**Comment by dougmassay** [comment] 2021-02-23 18:18
I can certainly take a crack at it. To be clear though: you're saying that with the exception of @import, our regex should ignore anything not designated with url() for all the css properties we include?

**Comment by kevinhendricks** [comment] 2021-02-23 18:28
Unless there is something in @fonts that allows just a quoted string form instead of a url?

The css spec is a bit of a nightmare of cludge addons.  

I will look for examples of urls used without the url() outside of @imports to see if there are other cases.

**Comment by dougmassay** [comment] 2021-02-23 18:35
if the list is small, mightn't it make sense to special-case the likes of @import and @font-face, and then just parse urls() wherever else they occur (regardless if that property allows the use of url() according to the spec?

**Comment by kevinhendricks** [comment] 2021-02-23 19:24
I am okay with that but it could catch comments or use of the string sequence "url(" within a quoted string.

So lets try to restrict it to valid leading property names.

**Comment by kevinhendricks** [comment] 2021-02-23 19:33
From what ai have read only the quoted path is valid for @import, the spec for things like background and background-image are only valid with url().  

We do not need to update invalid css, so only @import needs the special case as far as I can tell so far.

**Comment by kevinhendricks** [comment] 2021-02-23 19:47
I did find url() used in two places we do *NOT* want to update in css:

@namespace - as it is really a uri not a url

offset-path 

The latter one sets a drawing path as a url but it is independent of the location of the stylesheet and should not be updated.

So we do need to restrict where we check for url() to that list from the Mozilla-Developers network I posted to be safest.  And only worry about quoted strings paths for @import.

That should do it.

**Comment by richilton** [comment] 2021-02-25 12:11
Many thanks for jumping on this so quickly, and sorry for opening such a can of worms! :)

**Comment by dougmassay** [comment] 2021-02-25 23:27
I've been tinkering with this, and thought I had a pretty easy workaround, but I couldn't get it to update @import urls of the form: 

`@import` "test.css";

No matter what I did, I couldn't get PerformCSSUpdates to update valid urls with that syntax when renaming/reorganizing. Imagine my surprise when I discovered that Sigil hasn't been able to update @import urls using that syntax for a while now! At least  not on Linux where I'm currently working.

The expression being used to include those "naked" @import  urls is correct. I've tested it outside of Sigil to be sure.  So I'm not sure what's going on. But I'm pretty happy that I haven't actually broken anything that wasn't already broken with my recent tinkering! :)

**Comment by kevinhendricks** [comment] 2021-02-26 00:12
Perhaps it was a do until/while first pass issue as @imports are typically the first line in the css file?

I will study the code to see if anything jumps out at me.

**Comment by dougmassay** [comment] 2021-02-26 00:29
I screwed up when testing. The current version of Sigil can update `@import "test.css";` just fine. As can my new code. But both can only update the same path ONCE per CSS file.  If you have something like the following in a css file.

/*@import url(test.css);*/
@import "test.css:;

The url in the commented out line will be updated, but the second line won't be updated. I'm guessing it's because the underlying path no longer matches after the first update when examining at the next occurrence.

I'm assuming the same would happen if the same image url was referenced multiple times in the same css file.

**Comment by dougmassay** [comment] 2021-02-26 00:33
Github ate the asterisks in my css block comment in the previous post. I'll see if I can escape them properly,

**Comment by kevinhendricks** [comment] 2021-02-26 00:48
We do not update the hash table passed in as it is passed in as const so it should happily update the same url again and again.  So I not not sure why?

**Comment by kevinhendricks** [comment] 2021-02-26 01:08
We never write anything to keys or m_CSSUpdates so no changes are made to them after an update has been done, so there really is no reason that the same url can not be updated multiple times. 

So something else funny us going in.  Perhaps the changes_made flag or perhaps we are somehow updating to the wrong next position skipping the second replacement somehow.
The  code is really messy so it is hard to see what is going on without adding some debug output.

If you want me to take a closer look at it just let me know.

**Comment by kevinhendricks** [comment] 2021-02-26 01:25
In current Sigil master:

I created an empty epub and an empty stylesheet "Style0001.css".
I linked the stylesheet to Section0001.xhtml
I added the following lines to the Style0001.css

/* @import url(test.css); */
@import "test.css";

Then I moved OEBPS/Styles/Style0001.css" to a new destination: OEBPS/Styles2/ and made no other changes.

So when we moved that file it should update the links to now point back to where the "test.css" actually was back in OEBPS/Styles/ since I did not move it.

Here is what I see:

/* @import url(../Styles/test.css); */
@import "../Styles/test.css";

So the duplicate links both to the same non-existent OEBPS/Styles/test.css were properly updated.

So at least on macOS, I am not seeing what you are seeing so something else must be going on.

**Comment by kevinhendricks** [comment] 2021-02-26 02:14
Okay, I see the issue.

When we change the first item to be a much shorter path, the starting position to search for the next match is wrong since it calculates position before the replacement is done but once first replacement is done all earlier match positions are wrong.

We should only update the search index to the start position plus the replaced (new length) not the old length.

That or we do all of the replacements in reverse order so that changes at the end do not impact positions at the start.

Or we really need to move to just incorporate the qCSSParser to do most of the work.

I will see if I can get the new start_index properly set.

**Comment by dougmassay** [comment] 2021-02-26 02:27
> We should only update the search index to the start position plus the replaced (new length) not the old length.

Let me see if I can accommodate that. Thanks for figuring out what was going on!

**Comment by kevinhendricks** [comment] 2021-02-26 02:39
Be careful.  It is tricky as we have repeated that same bug when replacing within the "fragment" itself.
So there are two places that need to be fixed.

Every time a replacement is done either in "result" or in the "fragment" the new starting_index or frag_starting_index  needs to be the original capturedStart(x) + the length of whatever we are replacing things with and not the thing that was replaced ie. the  capturedLength() / capturedEnd() to prevent the bug.

**Comment by dougmassay** [comment] 2021-02-26 16:42
@kevinhendricks : I just pushed a commit to (hopefully) deal with properly updating the search index. I wanted to get that nailed down before pushing my workaround for the additional problem this current open issue exposed.

I _THINK_ I'm ok, but would like a second pair of eyes on it to make sure. My concern is ensuring that it's ok to rely upon new_href.length() and fragment.length() to increment the two start indexes. I'm pretty sure the various hasMatch()/isEmpty() tests ensures these integers will be both correct and in scope when accessed.

**Comment by kevinhendricks** [comment] 2021-02-26 20:42
Took a look. 

I think you code is correct if replacements are made.  But I think  if **no** actual replacement is made, we need to use the capturedEnd() as the new start index to prevent refinding the same match twice.  But I have not tried it so I can not be sure.

Does that make sense?

**Comment by dougmassay** [comment] 2021-02-26 21:03
Actually yes, it makes sense. I'll take a look. You're talking about the final replace, right? Or do you mean the fragment replace, too?

**Comment by kevinhendricks** [comment] 2021-02-26 21:08
Another way to deal with the no replacement issue is to update to the capturedStart(x) plus 1 so we do not re-find the same thing.

But I think the best way to do this when starting a search at search_index and finding something at capturedStart(x) we want to:

if no replacement made:
    search_index = capturedStart(x) + capturedLength(x)    /* i.e. capturedEnd(x)  */
else
    search_index = capturedStart(x) + replacement.length()

This will prevent re-finding the same thing while doing the least amount of searching over the same characters twice.

But I have not tested this.

**Comment by kevinhendricks** [comment] 2021-02-26 21:08
Yes both.

**Comment by dougmassay** [comment] 2021-02-26 23:12
I'm struggling a bit with this. The indices are currently being updated outside of the scope of the for-loops where the x in capturedStart(x) + capturedLength(x) is relevant.

**Comment by kevinhendricks** [comment] 2021-02-26 23:57
I think we need to create a new int variable called index_correction that accumulates the differences in lengths each time and then we add it in at those points.

Let me give something a try and push it so you can see if that works or not.

**Comment by dougmassay** [comment] 2021-02-27 00:16
Please do!

**Comment by kevinhendricks** [comment] 2021-02-27 00:40
Sent something to you via e-mail.  I have my fingers crossed this will work.  If not, I say we ditch these dual regex loops and instead incorporate the qCSSParser to handle the outer loop and regex to handle the inner loop with regex by building a list of all replacements and doing them in reverse order so that all position info is sane at all times.

**Comment by dougmassay** [comment] 2021-02-28 19:15
OK. After dealing with multiple power outages this weekend, I've pushed something that I _think_ will incorporate @kevinhendricks 's refactored capture position index tracking, and will special-case @import lines so that standard strings are only parsed for urls when part of an @import statement. I updated the list of properties that url() should be checked, for as well.

Still probably not going to be perfect, but we should at least be a little better off than we were before! :)

**Comment by kevinhendricks** [comment] 2021-03-04 16:50
Your changes seem to work well.  So can we close this since it is now fixed in master?  Also do you want to leave on the qdebug output through the beta release or disable it now just to make line number matching for translations easier?

**Comment by dougmassay** [comment] 2021-03-04 18:06
Yes. I'll close this issue. I say we can remove most, if not all, of the debug output. If something does happen to turn up later, it shouldn't be that hard to reproduce the issue with provided css samples we can debug ourselves.

**Closed by dougmassay** 2021-03-04 18:06 UTC
