### ISSUE TITLE
[Bug]: loadlibrary error in Windows Remote Desktop Protocol

### ISSUE THREAD

**Issue by wuyu8512** [Sigil-Ebook/Sigil#668] opened 2022-01-26 02:45 UTC
### Bug Description

in my windows
I can open sigil in native
but when i rdp to my windows, i cant open sigil
Is there some file where I can view detailed logs?
![image](https://user-images.githubusercontent.com/33444499/151095295-c13c0d11-9705-4cd0-bbfc-060d81239481.png)

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 11

### What version of Sigil are you using?

1.8.0

**Comment by dougmassay** [comment] 2022-01-26 02:55
Can't say as I ever tried running Sigil via rdp. You enable a debug log by setting an environment variable, but without a version of Sigil that's compiled to be very "loggy" there'll be very little in it. Can you use the error log in the Windows event viewer to see which library is failing to load? 

It could be a permissions thing. Is Sigil installed for All Users, or is it installed for the user you're trying to rdp as? The latter might work better for remote desktops.

**Comment by dougmassay** [comment] 2022-01-26 03:17
I've heard that Microsoft's Remote Desktop has some issues with openGL. I'm not familiar with how rdp works, but you might try creating a batch/cmd file that sets the QT_OPENGL environment variable to "software" before launching Sigil and see if that makes a difference

**Comment by wuyu8512** [comment] 2022-01-26 03:24
![image](https://user-images.githubusercontent.com/33444499/151098851-46d61028-1064-45b2-8426-7bbc3b8fd691.png)
Here are some things I saw, don't know if it helps you

**Comment by dougmassay** [comment] 2022-01-26 03:32
Those dlls in the Sigil directory are not part of the standard Sigil distribution. If rdp is trying to create them there, then that definitely suggests a permissions issue. I would recommend uninstalling Sigil for All Users and reinstalling it as the user being used to rdp.

**Comment by wuyu8512** [comment] 2022-01-26 03:51
now, i reinstalling it as the user being used to rdp, and i have a detail log

![image](https://user-images.githubusercontent.com/33444499/151100817-a7c9dafd-193d-4d15-a171-66574192833a.png)

[Logfile.CSV](https://github.com/Sigil-Ebook/Sigil/files/7938787/Logfile.CSV)

**Comment by dougmassay** [comment] 2022-01-26 14:02
I'm at a bit of a loss, here. It's natural for Sigil to look for those system libraries in the Sigil directory first, but then it should find them in the normal system locations. I saw some compatibility registry entries the first time around. You don't have Sigil marked as needing to run in compatibility mode on the "server" do you?

Are your server and client running the same OS (and version)?

**Comment by dougmassay** [comment] 2022-01-26 14:04
I'm afraid I won't have a lot of time to spend on this issue. It's not a very common use case, and I don't use rdp to be able to do any testing.

**Comment by kevinhendricks** [comment] 2022-01-26 15:00
Two things ... have you tried forcing Sigil to use software based opengl - per the rec here:

https://forum.qt.io/topic/122892/windows-remote-desktop-and-opengl

One other thing to try ... first start up Sigil by using a batch file to launch it so it sees real hardware.  Then try attaching to the Sigil process that is already running via rdp.   As per this link https://stackoverflow.com/questions/51705471/current-state-and-solutions-for-opengl-over-windows-remote

**Comment by kevinhendricks** [comment] 2022-01-31 16:04
Should this be closed?

The reporter has not responded to either of us about forcing Sigil/Qt to use software based opengl or about attaching to the process after launch.

Since neither of us use Windows rdp, we have little chance of figuring this out without his/her input and feedback about what has been tried.  Trace output is probably not going to be helpful.

**Comment by wuyu8512** [comment] 2022-01-31 16:11
Sorry, I've been busy lately, I think I can give the test results tomorrow

**Comment by dougmassay** [comment] 2022-02-01 13:31
After much fiddling around to set up rdp to work with passwordless account logins on a physical Windows 10 machine, as well as a Virtual Windows 10 machine, I am able launch Sigil with a variety of client machines (with both Windows and Android rdp clients) on at least 2 different Windows 10 server machines. So I don't think the issue is inherently a Sigil's bug.

This is all just by connecting to a remote Windows desktop and then simply launching Sigil from there. If you're doing something more complicated than that, I'd need some exact rdp setup details to try and recreate your issue.

**Comment by wuyu8512** [comment] 2022-02-01 15:13
Hi, I tried these two methods and they both work
Also, I also tried my virtual machine in esxi, It can open the software but the page is blank, when i set QT_OPENGL=angle , this work good

**Comment by kevinhendricks** [comment] 2022-02-01 17:06
This is really a Qt issue and not something we can control or change.  Glad to hear you have multiple working solutions.

**Closed by kevinhendricks** 2022-02-01 17:06 UTC
Labels: bug, Windows
