### ISSUE TITLE
Duplicate semantic entries

### ISSUE THREAD

**Issue by Carmina16** [Sigil-Ebook/Sigil#620] opened 2021-05-29 14:25 UTC
There are two identic copies of available semantics in the Semantics dialog for `introduction`, `backmatter`, `toc`, and `preface`.

**Comment by dougmassay** [comment] 2021-05-29 14:41
I can't reproduce this with the new release. 
Sigil version and platform?

**Comment by Carmina16** [comment] 2021-05-29 14:42
1.5.1

**Comment by Carmina16** [comment] 2021-05-29 15:20
Are you trying to retrieve the role code by its localized name from the role list? That is prone to localization errors.

**Comment by BeckyDTP** [comment] 2021-05-29 17:49
I confirm. For English and Polish is OK, but change UI language to Russian and them in Semantics dialog are duplicates.
![semantics-russian](https://user-images.githubusercontent.com/22416021/120079987-e98f5e00-c0b6-11eb-92a3-e1189d2cf97d.png)

**Comment by kevinhendricks** [comment] 2021-05-29 20:07
Then that is a Translation or Transifex issue since the translations are not unique but the codes are.  Not sure what can be done other than filing a bug report with Transifex.

**Comment by kevinhendricks** [comment] 2021-05-29 20:43
Each semantic has a different description at the bottom of the add semantics window when highlighted.  Are these duplicated as well?

**Comment by kevinhendricks** [comment] 2021-05-29 20:53
It is not the translations (at least not in Sigil-1.6.0).

The Russian language ts file has only two entries for "Preface".  One in Misc/GuideItems.cpp line 185, and one in Misc/Landmarks.cpp line 190.

So there is no reason for it to appear twice.

**Comment by kevinhendricks** [comment] 2021-05-29 21:02
But these terms mean different things in books:

(from a web search).

A foreword is written by someone other than the author and tells the readers why they should read the book. A preface is written by the author and tells readers how and why the book came into being.

So this is a bug in the Russian translations and there is nothing we can do to "fix" it code-wize in Sigil.

**Comment by kevinhendricks** [comment] 2021-05-29 21:07
You should be able to tell the difference by clicking on each one and reading the short explanatory description attached to each at the bottom of the Dialog.  It should include the code as well in Sigil-1.6.0.

Closing this as the bug is not in Sigil but in the Russian translations.  If someone can provide improved Russian ts file, I will pass it along to Transifex.

**Closed** 2021-05-29 21:08 UTC

**Comment by BeckyDTP** [comment] 2021-05-29 21:32
I can confirm that this is a translation problem. If different semantics are translated in the same way – duplicates are displayed.

I did the test and changed the Russian .ts file, adding an English equivalent to the Russian translation, and then it works fine.
In epub2 we see that _foreword_ and _preface_ are translated as _Предисловие_.
After adding the English name to the translation – Semantics dialog is displayed correctly. 

![semantics-russian-test](https://user-images.githubusercontent.com/22416021/120085174-27e84580-c0d6-11eb-95dc-0b9380f376d0.png)

**Comment by kevinhendricks** [comment] 2021-05-30 00:06
Thanks for confirming!

**Comment by Carmina16** [comment] 2021-05-30 03:24
> You should be able to tell the difference by clicking on each

The items with the same name have the same description and the code, and insert the same landmark, as you seem to build the list incorrectly (by keying it on the names probably?). Please reopen and identify items by the actual roles instead of localized names.

**Comment by kevinhendricks** [comment] 2021-05-30 11:31
The semantics list is built from unique semantic codes, the translated names are sorted only for display.   Descriptions are built from unique codes not translated names.  This is a translation issue not a code issue.  The translations must be unique for unique codes.

**Comment by kevinhendricks** [comment] 2021-05-30 11:58
The only thing I could do is remove the actual semantic code we added to the Description for Sigil 1.6.0 and instead add it to the translated name in parentheses to force each translated name to be unique as it would have the unique code attached.

But the easiest and quickest solution is to simply fix the bad translation.  What language  are you seeing this issue with.

**Comment by Carmina16** [comment] 2021-05-30 14:48
> Descriptions are built from unique codes not translated names. This is a translation issue not a code issue.

O'RLY?

https://github.com/Sigil-Ebook/Sigil/blob/13e85c154add7fbb98e945a3e8e5fcedddacfc32/src/Dialogs/AddSemantics.cpp#L52

https://github.com/Sigil-Ebook/Sigil/blob/13e85c154add7fbb98e945a3e8e5fcedddacfc32/src/Dialogs/AddSemantics.cpp#L66

Descriptions are built from translated names indexing the `m_Name2Code` mapping. As a mapping can hold only one value for each unique key, it is impossible to have various items with same name yielding the same key. The selection logic is incorrect, and should be fixed, using the methods of unique identification of list items available in your toolkit.

**Comment by kevinhendricks** [comment] 2021-05-30 17:01
Yes, I know.  I wrote it.  As I said, translations from different codes MUST be unique as they represent unique constructs.

People  want to see and choose by the translated names not codes.

So as I suggested I could add the codes in parentheses to the translated names to force them to be unique.  But again, if you just translate the codes properly, there would not be an issue.

**Comment by kevinhendricks** [comment] 2021-05-30 17:02
If you look earlier in that routine you will see the codes are walked to produce the names and descriptions.  It is the Name2Code map that must be unique it is if properly translated.

**Comment by kevinhendricks** [comment] 2021-05-30 17:04
The problem is the translation.  The code works just fine as long as the translations are unique. Which is what  I have said repeatedly.

**Comment by Carmina16** [comment] 2021-05-30 17:43
The problem is that you are doing weird things instead of storing `code` directly in the list item (Qt seems to be able to do that: https://stackoverflow.com/questions/7136818/can-i-store-some-user-data-in-every-item-of-a-qlistwidget). Application logic should never depend on translation.

**Comment by kevinhendricks** [comment] 2021-05-30 18:00
Again, I can store both the description and the exact code easily in QListWidgetItem data fields.  BUT THAT WILL NOT CHANGE THE FACT THAT THE USER WILL SEE TWO IDENTICAL ENTRIES with no easy way to tell the difference.

**Comment by kevinhendricks** [comment] 2021-05-30 18:02
The best I can offer is to add the always unique code in parentheses to the end of the translated name.  Thereby always making them unique.

**Comment by kevinhendricks** [comment] 2021-05-30 18:06
The problem is that Preface and Foreward should never translate to the same word.
The code can be made to tell them apart but the user is selecting from a set of translated names (that have been sorted) and they will not be able to tell the difference!

**Comment by kevinhendricks** [comment] 2021-05-30 18:37
According to Google Translate, the russian word for Preface is exactly identical to the russian word for Foreword.  The descriptive info only differs by the word "not" so their translations would be nearly identical as well.

So I will add the semantic code in parentheses after the translated name so that they become visually distinctive enough for a user to detect and select them as separate items.  I will remove it from the Description as it need not be in both places.

It is the only way to allow the user to select using translated names.

**Comment by kevinhendricks** [comment] 2021-05-30 18:50
That said, the Cambridge English to Russian dictionary uses the following:

foreword: предисловие, введение

preface: предисловие

**Comment by Carmina16** [comment] 2021-05-30 19:02
> Again, I can store both the description and the exact code easily in QListWidgetItem data fields. BUT THAT WILL NOT CHANGE THE FACT THAT THE USER WILL SEE TWO IDENTICAL ENTRIES with no easy way to tell the difference.

You don't have to store descriptions in list items, you need to store only the key, which is unique and untranslatable. The user will be able to tell the difference by the description and code shown below the list; those will be unique if they are selected by the unique, non-translated role code like `toc` which is different for each list item, no matter what its text says. You are already doing that, just extract `code` from the currently selected item instead of your homebrew map lookup.

**Comment by dougmassay** [comment] 2021-05-30 19:26
How about you just submit a pull request for the perfect solution then? If it works correctly, we'll use it. I'm tired of this whole issue. First you provide no info to help find the problem. Then you get dismissive, rude and insulting when we make decisions you don't care for.  Homebrew my ass.

**Comment by kevinhendricks** [comment] 2021-05-30 19:49
Or add the code in parentheses after the translated name making distinguishing the translated names easier.  BTW, using QVariant (unions) to store extra data just uses a map like we do in most models, plus you have the casting to a union and back we do not need.

And I have to agree with DiapDealer here and say you have been extremely rude while providing no real help.  You have used up any and all goodwill from me.

Do not bother with any pr, I will be implementing the solution I proposed at the beginning which can be done with 2 one-line changes versus storing things in data items that actually are stored in dicts/maps in the underlying model code anyway.

**Comment by kevinhendricks** [comment] 2021-05-30 21:05
Pushed prevent duplicate translations for semantics to master

**Comment by Carmina16** [comment] 2021-05-31 03:58
> Then you get dismissive, rude and insulting

Please quote me where I was "rude" or "insulting".

**Comment by Carmina16** [comment] 2021-05-31 04:15
> say you have been extremely rude while providing no real help.
1. nowhere in the course of conversation I was being rude
2. I guessed what a problem could be, https://github.com/Sigil-Ebook/Sigil/issues/620#issuecomment-850850366
I provided a correct solution https://github.com/Sigil-Ebook/Sigil/issues/620#issuecomment-850933393
I even provided you a sample code for that solution https://github.com/Sigil-Ebook/Sigil/issues/620#issuecomment-851035617
I was helpful and patient all that time.
