### ISSUE TITLE
 Error: guide href not in manifest

### ISSUE THREAD

**Issue by hantsaniala** [Sigil-Ebook/Sigil#534] opened 2020-07-24 10:02 UTC
Hello,

After the upgrade of my Sigil to 1.2, I've got this kind of error when I run my own plugin. This one worked with Sigil 1.0. Can someone help ? I can't find how to solve this.

![image](https://user-images.githubusercontent.com/8157490/88381430-185de900-cdaf-11ea-9539-036098ffff2b.png)

The code that give the error inside the plugin I used
![image](https://user-images.githubusercontent.com/8157490/88380804-e8faac80-cdad-11ea-932c-0303f503ff67.png)

Thanks.

**Comment by kevinhendricks** [comment] 2020-07-24 11:00
This is not the place to debug your plugin code issues.  Newer versions of Sigil allow the epub layout to be whatever the dev wants.  Plugin code therefore needs changes to support that.   We have a Sigil Plugin Developer's forum on www.mobileread.com for supporting plugin developers (See Sigil's README for links to user support forums).

Please redirect your inquiry there.

Closing this as it is not a bug/issue in Sigil and this is not the proper place for plugin dev support.

**Comment by kevinhendricks** [comment] 2020-07-24 11:25
BTW: that error message means the href you set for that guide item does not exist in the manifest.  A guide item href should be identical to at least one of the hrefs in the manifest (ie. it should point to a file that the manifest says exists in the book). 

bk.addfile will default to adding it to where ever the current folder for xhtml files are set (which no longer needs to be OEBPS/Text).

If you want to specify the full bookpath (path from book root) for a new file, you can do that via newer plugin interface calls.  Then you must create the proper guide href to point from the opf to where you put the newly added file.  There are newly added support routines to help with that too.  Again, all of this was discussed in the Sigil plugin forums on Mobileread.

**Comment by kevinhendricks** [comment] 2020-07-24 11:27
closing

**Closed** 2020-07-24 11:47 UTC
