### ISSUE TITLE
opf error just by saving

### ISSUE THREAD

**Issue by CJClink** [Sigil-Ebook/Sigil#184] opened 2016-02-08 21:43 UTC
I'm not a maven, I have just downloaded Sigil this past weekend, and have never used it before. I had uploaded a word file to Draft2Digital and downloaded an ePub file. I put the epub file through ePubCheck and it said there were no errors. Zero. So, I open up the file in Sigil (latest release) make one change (adding a letter to a text word) and saved the file. I take the saved file, put it through ePubCheck and now I have an opf error that says:

OPF-001, /OEBPS/content.opf, There was an error when parsing the EPUB version: Version not supported

If I take this bad file and put it through FlightCrew, The error message says:

OEBPS/content.opf, line 2, Error OPF bad package version: the <package> element's version "attribute" value needs to be "2.0", but is "1.0". near column 173.

And if I try to edit the version number, Sigil says I can't do that from within Sigil.

Now, obviously I did a LOT of editing before I realized that my file was no good anymore. This test above was devised afterwards.

There were also errors in FlightCrew to do with the meta data attributes which I seemed to be able to fix.

I'd really like to NOT lose all the editing I did. AND I really liked Sigil's editing powers/interface.

Is there any way to change the OPF package version to "2.0"  OR any way to get Sigil to NOT make any changes to the content.opf file? Or just tell me where I went wrong. :(

**Comment by kevinhendricks** [comment] 2016-02-08 22:23
The problem is the Draft2Digital generated an incorrect epub which either had no package version attribute set in the content.opf or a package version tag set to "1.0".  There really is no epub version 1.0.  The only correct versions of epub today are "2.0" and "3.0" for the content.opf package version attribute.

Recently Sigil started to add epub3 support and we did not want people trying to upgrade from epub2 to epub3 by just editing the content.opf.  So we prevented that change.  The issue is it prevents a change form a bad "1.0" epub to a proper "2.0" epub as well.  This was an unexpected side-effect as we thought no epub "1.0" existed in the wild anymore.

You have a few options to not lose your work.
1) Download Sigil-0.9.2 (or any recent earlier version) and it will happily let you change the content.opf package version attribute to anything you like by opening the content.opf tab and changing the package version attribute value.  I recommend "2.0".

2) Since an epub is just a zip archive.  Simply unzip the epub, and open the resulting folder and edit the OEBPS/content.opf file inside and change that "1.0" to "2.0" with any text editor, and then Sigil-0.9.3 will happily open it.

3) A Sigil plugin was created to convert those few extinct epub types to somethign Sigil can read.
You can find this plugin in the Sigil User's Forum on the www.mobileread.com website.
The link to the plugin is here:

http://www.mobileread.com/forums/showpost.php?p=3252427&postcount=25

The nice thing about the plugin, is that it will actually fix a bunch of little nits to make your epub move from version "1.0" to "2.0" painless.  It will also teach you how to use Sigil plugins (with the Plugins->ManagePlugins menu.  It is written by one of the co-developers of Sigil.

Of the 3 options, option 3) should be easiest and won't let you mess up when editing the content.opf since it is automated.

**Comment by kevinhendricks** [comment] 2016-02-08 22:25
FWIW, my guess is epubcheck did not reveal any issues since it checks against the old pre epub2 standard.

**Comment by CJClink** [comment] 2016-02-08 22:45
OMG!
The plug-in worked!
Thank you!
I'll look at it more tonight, but the version tag is now "2.0" :)
- Carolyn 
-------------
 Carolyn Clink
 http://www.sfwriter.com/carolyn.htm carolyn@sfwriter.com

**Comment by kevinhendricks** [comment] 2016-02-09 00:14
Glad to hear it worked for you.  There are a number of Sigil plugins available on the Mobileread.com site and lots of authors, small scale epub makers and advanced users there at MR that would be happy to answer any questions.

Closing this issue.

**Comment by CJClink** [comment] 2016-02-21 23:25
Hi, Kevin,
All went well with the first ebook using the plugin to import it and having the fixOPFv1 work and fix the problem.

BUT, now I'm trying to import the 2nd ebook into Sigil, using the same plugin fixOPFv1 -- I get a message that the plugin failed because the file is not v1.
BUT, it IS! When importing directly into Sigil, first I got the pop-up message saying that Sigil won't correct the package number in the file. AND when I look at the code, it's totally package 1.0.
I went back to the fixOPFv1 folder on my desktop and unzipped the files again... but that didn't seem to help.
Am I missing a step?
- Carolyn
-------------
 Carolyn Clink
 http://www.sfwriter.com/carolyn.htm carolyn@sfwriter.com

**Comment by dougmassay** [comment] 2016-02-21 23:55
This is more than likely an issue with my plugin. Let's take the discussion there instead.

http://www.mobileread.com/forums/showthread.php?t=271268

More than likely, if you post the entire contents of the opening <package> tag in the OPF file, I'll be able to see what's going wrong. Just don't post a copyrighted epub at Mobileread whatever you do.

**Comment by kevinhendricks** [comment] 2016-02-21 23:58
No you are not missing anything that I know.  There was a bug reported on MR just today that reports that the package version gets changed to "1.0" in some epubs when imported that do NOT begin with a proper xml declaration.

I am guess the real problem is that the opf produced by your software is missing the xml declaration.  It is generally not required but Sigil always adds it and thus hid the bug. 

So the best way to deal with this issue right now is to look at what is really being delivered by the software you are using:

1. Make a copy of your epub before it is loaded into Sigil (not after).
2. Change the name of that copy to end with .zip (epubs are really zip archives)
3. Unzip that copy using any zip tool (on Mac simply double-click it)
4. Look for and find the OPF file (called content.opf or package.opf or somethign along those lines).
5.  It is a text file so open it with NotePad or any text editor you have

What does the package version attribute really say before importing it?  

Does it have a xml declaration as its first line?  I.e something that looks like this:

```
<?xml version="1.0" encoding="utf-8" ...
```

Please let me know what you see.

KevinH

**Comment by kevinhendricks** [comment] 2016-02-22 00:01
Doug,

Please allow it to pass through for either version "1.0" (and fix it)  or "2.0"  but please make sure to add a proper xml declaration to the first line of the content.opf to prevent the bug just reported on MR from causing a problem.

Thanks,

Kevin

**Comment by CJClink** [comment] 2016-02-22 00:23
Hi, Kevin,
This is what the first few lines of the content.opf look like:
<package xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf" xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="BookId">
  <metadata>

So, seems to be missing the declaration as you say...
- Carolyn 
-------------
 Carolyn Clink
 http://www.sfwriter.com/carolyn.htm carolyn@sfwriter.com

**Comment by kevinhendricks** [comment] 2016-02-22 01:50
Yes, you have been bitten by the bug just reported today (and just fixed in master).  The easiest workaround is to add an xml declaration as the first line of the opf file.   I will ask Doug, to modify his import plugin to pass along package versions that have "2.0" and to add the xml declaration to prevent the bug from hitting you.  That way you can use it to import epubs whose content.opf files are missing xml declarations.  The only other solution is to drop back to Sigil-0.9.2 which will allow you to change the package tag from 1.0 to 2.0 and will add the xml declaration, until a Sigil-0.9.4 is released with these bug fixes.

**Comment by dougmassay** [comment] 2016-02-22 02:25
There's a new version of the plugin available at Mobileread that I hope will do the trick until Sigil 0.9.4 is released. 

http://www.mobileread.com/forums/showthread.php?t=271268

**Comment by CJClink** [comment] 2016-02-22 03:21
Thank you, Doug!
I've got my ePub into Sigil now. :)
Looks good at first blush.
- Carolyn 
-------------
 Carolyn Clink
 http://www.sfwriter.com/carolyn.htm carolyn@sfwriter.com

**Comment by kevinhendricks** [comment] 2016-02-22 03:58
glad to hear it is working.  reclosing this issue.

**Closed by kevinhendricks** 2016-02-22 03:58 UTC

**Comment by Jacksmith6981** [comment] 2022-04-02 09:02
Ever encountered this problem "could not find .opf file"?  Maybe or not!  When using the .opf file, sometimes we encounter the problem of "could not find the .opf file" while opening the file.  So friends, in today's article I will discuss with you how you can solve this problem.  Get a complete guide on [how to solve could not find Opf file](https://freegamesandsoftwaredownload.com/how-to-solve-could-not-find-opf-file/) check this full article to get rid of your issue.
