### ISSUE TITLE
Reformat HTML feature doesn't handle <table> correctly

### ISSUE THREAD

**Issue by firstrose** [Sigil-Ebook/Sigil#158] opened 2015-11-16 06:05 UTC
![b83ef0310a55b3196b17618b45a98226cdfc175b jpg](https://cloud.githubusercontent.com/assets/1551595/11175268/14121c34-8c6b-11e5-87c0-2651e823c703.png)

Version: 0.9.0

Thanks

**Comment by kevinhendricks** [comment] 2015-11-16 14:49
You should set your Sigil Clean Preferences to Clean with Gumbo NOT PrettyPrint Gumbo.  Prettyprint is prone to run into corner cases that can confuse it.  

For example using a structural element like a div inside of inline element such as a td element is probably not the best idea and so has probably never been tested or seen in our test cases, especially since most early ebook readers did not support tables at all.

I assume you were hoping for something along the lines of:
```
<table>
    <tbody>
        <tr>
            <td> blah </td>
            <td> blah2 </td>
        </tr>
    </tbody>
</table>
```

I will check out what current pretty print code in master does and see if I can clean it up a bit.  I doubt it will ever properly handle structural elements like a div inside an inline tag like a td in a visually pleasing way.

If you clean with just Gumbo, none of this is an issue as it tried to reproduce the original as closely as possible.

**Comment by kevinhendricks** [comment] 2015-11-17 00:45
Just committed a fix for this to master.  
Closing this issue.
Thanks for your bug report!

**Closed by kevinhendricks** 2015-11-17 00:45 UTC

**Comment by firstrose** [comment] 2015-11-17 08:33
Thank you for your work.

But I just tried BOTH cleaner and NONE works on 0.9.0. Things looking interesting...
I think you're right. Early readers don't support <table> , neither do Gumbos.

I'll wait for the next version.

Again, thank you very much.
