### ISSUE TITLE
Sigil takes forever to open large ebooks

### ISSUE THREAD

**Issue by bumblebritches57** [Sigil-Ebook/Sigil#85] opened 2015-07-08 07:45 UTC
Like, over half an hour in some instances, and currently it's using 776% of my CPU.

Here is the ebook in question (it's an open source textbook, beware it's about 260 MB.): https://dl.dropboxusercontent.com/u/52358991/Biology.epub

and here is a sample from Activity Monitor: http://pastebin.com/1DRjW2ja

**Comment by kevinhendricks** [comment] 2015-07-08 17:42
Unfortunately, that is not a bug.  A 260 meg e-book is literally huge.  As for CPU usage I assume you mean 77.6% since 776% is an impossible value.  Sigil is multi-threaded and will use multiple threads when working on epubs (zip archives) with mutlitple resources.  FYI, a typical epub is under 2 meg in size with some reaching 3 or 4meg and these open in reasonable time on my machine and even much older machines.

When opening an epub for the first time, Sigil will move and validate (at least partially) every page and resource in the ebook.  It does this by design as it standardizes locations of and relative positions of images, fonts, text, etc.  This allows Sigil's wysiwyg BookView editing to actually function.

Sigil master does have some speed-ups for loading larger epubs, but nothing that will magically sort and validate a 260 meg epub quickly.

**Comment by bumblebritches57** [comment] 2015-07-08 18:57
No, I mean 776%, OS X measures CPU use as a percentage of ALL cpu cores put together, not X% of CPU1, Y% of CPU2, etc.

**Comment by kevinhendricks** [comment] 2015-07-08 20:08
Okay based on the few number of html files to update, that does appear to be a bug.
So to confirm I downloaded your huge test case.  It has 1001 jpegs, 449 png images, 6 ttf fonts and 65 html files.
Upon load, each of these files will be moved to a standardized location, and the xhtml text will be parsed to update all of the links accordingly.  So I do expect this to take quite some time to load.

That said, it definitely seems to be hung.  I snoopped around through my /tmp files until I found the place where the relocated epub files are stored (grep for scratchpad and Sigil) and looked and all of thehuge epub's  files and the code appeared to be relocated properly and updated properly in just a few cpu seconds.  The rest of the time is spent waiting for QtConncurrent (multi-threading is handled via Qt) to respond to say it is done.  It simply never responds or if it did, the 
"I am finished" condition signal is lost. 

It appears that there must be a bug in QtConcurrent (Qt) on Mac OS X that misses the condition that the updating is completed or some other bug that causes the "done" signal to be lost.

Have you tested loading your huge epub on Linux or Windows with Sigil?  Does it show the same issue?

**Comment by kevinhendricks** [comment] 2015-07-08 21:11
Upon further examination, the content.opf manifest in Biology.epub is incorrect.
It includes manifest entries for the following two image files that are NOT part epub

Missing manifest entries are:
Figure_14_04_01.jpg
Figure_43_04_02f.png

I am not sure if this is what is causing the problem or not.  Have you tried validating Biology.epub with epubcheck?

**Comment by bumblebritches57** [comment] 2015-07-08 21:27
@kevinhendricks  I have experienced similar behavior on Windows, but I haven't had access to that machine for about a month, so I can't currently test it.

**Comment by kevinhendricks** [comment] 2015-07-09 15:36
Okay, tracked this down to a performance bottleneck.  Your huge epub has over 1500 images and each image may be set as a background image anyplace inside inline styles or inside the style tag of nay of your html text files.    The way Sigil handles this case is using regular expressions since the contents of style tags themselves are not parsed by html parsers.  Your 65 files store over 14 meg of text and each one must be searched using regular expressions for each of the 1500 images in case a background image is used anyplace.

For normal epubs with say 5 to 10 jpegs and only 1 - 2  meg of text, this is not an issue.  But for your epub given the huge number of images and large size of text files, this is an issue.

I will see what I can do about it for a future release but no promises.

**Comment by kevinhendricks** [comment] 2016-01-15 17:03
Hi,
I believe I have a fix for this now.  I have reworked how CSS Updates are being done in Sigil for the forthcoming Sigil-0.9.3 release.  I can now open your "Biology.epub" testcase in a reasonable amount of time.  

I will close this as fixed for the next release.  If you have any issues after the next release of Sigil please feel free to reopen the issue.

Thanks again for your bug report!

**Closed by kevinhendricks** 2016-01-15 17:03 UTC
