### ISSUE TITLE
[Bug]: Plugin not a valid Sigil plugin

### ISSUE THREAD

**Issue by QuantumRoseinAmethystVase** [Sigil-Ebook/Sigil#715] opened 2023-05-06 19:36 UTC
### Bug Description

I'm using a Mac with M1 chip and system version 13.3.1. The Sigil I'm using is 1.9.30, but I can't install the plugin ( such as https://github.com/w3c/epubcheck/releases or https://www.mobileread.com/forums/showthread.php?p=2950625#post2950625 ), it says "Error: Plugin not a valid Sigil plugin.

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/62452364/236643321-f39c8bba-40f6-4c85-8d69-5171ab34528d.png">

### Platform (OS)

macOS

### OS Version / Specifics

macOS 13.3.1

### What version of Sigil are you using?

1.9.30

**Comment by dougmassay** [comment] 2023-05-06 19:54
The first download is precisely because it IS an invalid plugin. The W3C does not host any Sigil plugins. The second url is the correct one for the Sigil Epubcheck plugin, but you need to make sure that a) neither you nor your browser can rename the zip file. It has to remain named precisely at as it is hosted on the server. You also can't unzip the file. Safari sometimes does this on Macs and you need t configure it not to do so.

This really isn't a Sigil issue. in the future, if you have trouble with installing plugins, start by asking in the plugin's thread (where you downloaded it from) at Mobileread.com.

**Comment by QuantumRoseinAmethystVase** [comment] 2023-05-06 20:00
> The first download is precisely because it IS an invalid plugin. The W3C does not host any Sigil plugins. The second url is the correct one for the Sigil Epubcheck plugin, but you need to make sure that a) neither you nor your browser can rename the zip file. It has to remain named precisely at as it is hosted on the server. You also can't unzip the file. Safari sometimes does this on Macs and you need t configure it not to do so.
> 
> This really isn't a Sigil issue. in the future, if you have trouble with installing plugins, start by asking in the plugin's thread (where you downloaded it from) at Mobileread.com.

Thanks for your answer, I re-downloaded the attachment in the second site and now it is ready to install.

**Comment by kevinhendricks** [comment] 2023-05-06 20:10
Closing as not a bug

**Closed by kevinhendricks** 2023-05-06 20:10 UTC
Labels: invalid
