### ISSUE TITLE
OleSetClipboard: Failed to set mime data (text/plain) on clipboard

### ISSUE THREAD

**Issue by mrprobert** [Sigil-Ebook/Sigil#401] opened 2019-03-06 03:31 UTC
From time to time Sigil reports the error:

Failed to set mime data (text/plain) on clipboard: COM error 0xffffffff800401d0 (Unknown error 0x0ffffffff800401d0) (The parameter is incorrect.)

It's never been fatal.

On 0.9.10 and 0.9.12, I can reproduce the error by doing this:

Open a new Sigil instance.
Insert this text: Fd
Search for: Fd
Put the Cursor in the Replace box
Type: F
Bring up the insert special character window
Click on the Closing Single Quote symbol

==> Error

Error info: Critical: OleSetClipboard: Failed to set mime data (text/plain) on clipboard: COM error 0xffffffff800401d0 (Unknown error 0x0ffffffff800401d0) (The parameter is incorrect.)
Sigil version: 0.9.10
Runtime Qt: 5.6.2
Compiled Qt: 5.6.2
Platform: Windows SysInfo ID 192 

![screen1](https://user-images.githubusercontent.com/13193709/53854005-aba93b00-3f7c-11e9-848e-0aa463c3ccc3.jpg)

![screen2](https://user-images.githubusercontent.com/13193709/53854016-b368df80-3f7c-11e9-8a1f-cc482385c368.jpg)

**Comment by dougmassay** [comment] 2019-03-06 03:37
Someone reported the exact same error with nearly identical steps to reproduce on the forum a while back, but I was never able get it to happen. I'll try your steps when I get a moment.

**Comment by dougmassay** [comment] 2019-03-06 03:44
Ahhh, nevermind. I see it was you -- and it's the exact same steps to reproduce. That's why it sounded so familiar.

Kevin identified it in a later thread as a Qt bug that's been fixed in Qt5.12, but we can't move to Qt5.12 because of worse bugs that would adversely affect Sigil.

https://www.mobileread.com/forums/showthread.php?t=314543

The bottom line is that the problem occurs when there is another app or service open that has control or is monitoring the clipboard. The list of things that do that us quite long, Dropbox, Virtual Machines, QtCreator itself, other editors, etc, etc. So restarting just temporarily seems to fix this but given the potential clash, it will reoccur.

**Comment by dougmassay** [comment] 2019-03-07 15:23
We can't fix this Qt bug (or work around it) from our end. If and when we move to Qt5.12.2 in Sigil's Windows installer packages (or if you can figure out which program on your system exacerbates it), this will hopefully go away.

**Closed by dougmassay** 2019-03-07 15:23 UTC
