### ISSUE TITLE
carriage return character code produces XML not well formed error

### ISSUE THREAD

**Issue by JulesDoe** [Sigil-Ebook/Sigil#297] opened 2017-06-08 09:01 UTC
In Sigil 9.8 the XHTML parser reports an error if the character code for carriage return **&#xd;** is inside alt attribute.
`<img src="http://via.placeholder.com/350x150" alt="this &#xd; produces an error"/>`
The parsing prevents form using all the functionalities that relay on valid XHTML for example reports.
The pretty printer fixes this, but im not sure if it should be a problem in the first place. To the w3c XHTML validator this seems okay to do.
I stumbled upon this because Mac IndesignCC2015.3 exports alt text like this.

**Comment by kevinhendricks** [comment] 2017-06-08 16:38
According to the html browser spec character 13 entities are not allowed and must be converted to their character equivalent.  The gumbo parser used internally by Sigil will detect and fix these to meet the spec.

So not a bug as far as I can tell.   If you disagree, you might want to file a bug report with the Google’s gumbo parser on github.

**Comment by kevinhendricks** [comment] 2017-06-08 16:39
Closing this as not a bug.

**Closed by kevinhendricks** 2017-06-08 16:39 UTC
