### ISSUE TITLE
[Bug]: Building and installing sigil 1.9.10 on ubuntu 20.04 LTS breaks qt

### ISSUE THREAD

**Issue by ickam** [Sigil-Ebook/Sigil#692] opened 2022-07-10 17:56 UTC
### Bug Description

Upon installing current version of sigil (1.9.10), after building it from source, qt breaks. I had a working install of calibre and now neither calibre nor sigil open.
I'm using X forwarding on my linux server. The most commonly suggested solution of installing libxcb-xinerama0, doesn't work, because it was already installed.

### Platform (OS)

Linux

### OS Version / Specifics

Ubuntu 20.04 LTS

### What version of Sigil are you using?

1.9.10

### Any backtraces or crash reports

```shell
sigil                                                
Warning: could not connect to display localhost:10.0
Info: Could not load the Qt platform plugin "xcb" in "" even though it was found.
[1]    41831 segmentation fault (core dumped)  sigil
root@ryzenvm ~/sigil-build » calibre                                      139 ↵
qt.qpa.xcb: could not connect to display localhost:10.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

[1]    41240 abort (core dumped)  calibre
```

**Comment by eli-schwartz** [comment] 2022-07-10 17:59
There should not be any reason one application modifies another. How are you building Sigil? Do you use the system Qt? A custom one?

Where is it installed to?

**Comment by ickam** [comment] 2022-07-10 18:06
@eli-schwartz  I've built it using the linux build md file. Installed all the dependencies, including optional ones. QT is the version available from the ubuntu repos, I believe (5.12.8).
I am as confused why this is happening as you are, Eli.

**Comment by eli-schwartz** [comment] 2022-07-10 18:09
It looks like they're both failing for the same reason, which is failing to load the display server plugin. Do you have a graphical install on the same machine that you could test to see if that works directly?

**Comment by dougmassay** [comment] 2022-07-10 18:18
If you followed the Sigil build instructions, then I can imagine no way that Sigil broke Calibre or your system Qt. Something has happened to your system that is affecting both Sigil and calibre. Perhaps a system update?

I'll not be much help with display server/client issues. Not my forte or preference.

**Comment by ickam** [comment] 2022-07-10 18:18
startx on that VMs console is broken now as well.

` 12698.880]
X.Org X Server 1.20.13
X Protocol Version 11, Revision 0
[ 12698.890] Build Operating System: linux Ubuntu
[ 12698.894] Current Operating System: Linux ryzenvm 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64
[ 12698.894] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.4.0-121-generic root=UUID=1176faad-80eb-4ba8-97f0-e5c17082d3b9 ro maybe-ubiquity
[ 12698.900] Build Date: 14 December 2021  02:14:13PM
[ 12698.902] xorg-server 2:1.20.13-1ubuntu1~20.04.2 (For technical support please see http://www.ubuntu.com/support)
[ 12698.903] Current version of pixman: 0.38.4
[ 12698.905] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[ 12698.905] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[ 12698.907] (==) Log file: "/var/log/Xorg.0.log", Time: Sun Jul 10 18:11:09 2022
[ 12698.920] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[ 12698.948] (==) No Layout section.  Using the first Screen section.
[ 12698.948] (==) No screen section available. Using defaults.
[ 12698.948] (**) |-->Screen "Default Screen Section" (0)
[ 12698.948] (**) |   |-->Monitor "<default monitor>"
[ 12698.949] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[ 12698.949] (==) Automatically adding devices
[ 12698.949] (==) Automatically enabling devices
[ 12698.949] (==) Automatically adding GPU devices
[ 12698.949] (==) Automatically binding GPU devices
[ 12698.949] (==) Max clients allowed: 256, resource mask: 0x1fffff
[ 12698.949] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[ 12698.949] 	Entry deleted from font path.
[ 12698.949] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[ 12698.949] 	Entry deleted from font path.
[ 12698.949] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[ 12698.949] 	Entry deleted from font path.
[ 12698.949] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[ 12698.949] 	Entry deleted from font path.
[ 12698.949] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[ 12698.949] 	Entry deleted from font path.
[ 12698.949] (==) FontPath set to:
	/usr/share/fonts/X11/misc,
	/usr/share/fonts/X11/Type1,
	built-ins
[ 12698.949] (==) ModulePath set to "/usr/lib/xorg/modules"
[ 12698.949] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[ 12698.949] (II) Loader magic: 0x55e9a602b020
[ 12698.949] (II) Module ABI versions:
[ 12698.949] 	X.Org ANSI C Emulation: 0.4
[ 12698.949] 	X.Org Video Driver: 24.1
[ 12698.949] 	X.Org XInput driver : 24.1
[ 12698.949] 	X.Org Server Extension : 10.0
[ 12698.950] (++) using VT number 1

[ 12698.952] (II) systemd-logind: took control of session /org/freedesktop/login1/session/_318
[ 12698.953] (II) xfree86: Adding drm device (/dev/dri/card0)
[ 12698.954] (II) systemd-logind: got fd for /dev/dri/card0 226:0 fd 11 paused 0
[ 12698.957] (--) PCI:*(0@0:2:0) 1234:1111:1af4:1100 rev 2, Mem @ 0xfd000000/16777216, 0xfea90000/4096, BIOS @ 0x????????/131072
[ 12698.958] (II) LoadModule: "glx"
[ 12698.974] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[ 12699.022] (II) Module glx: vendor="X.Org Foundation"
[ 12699.022] 	compiled for 1.20.13, module version = 1.0.0
[ 12699.022] 	ABI class: X.Org Server Extension, version 10.0
[ 12699.022] (==) Matched modesetting as autoconfigured driver 0
[ 12699.022] (==) Matched fbdev as autoconfigured driver 1
[ 12699.022] (==) Matched vesa as autoconfigured driver 2
[ 12699.022] (==) Assigned the driver to the xf86ConfigLayout
[ 12699.022] (II) LoadModule: "modesetting"
[ 12699.022] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[ 12699.028] (II) Module modesetting: vendor="X.Org Foundation"
[ 12699.028] 	compiled for 1.20.13, module version = 1.20.13
[ 12699.028] 	Module class: X.Org Video Driver
[ 12699.028] 	ABI class: X.Org Video Driver, version 24.1
[ 12699.028] (II) LoadModule: "fbdev"
[ 12699.028] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[ 12699.029] (II) Module fbdev: vendor="X.Org Foundation"
[ 12699.029] 	compiled for 1.20.1, module version = 0.5.0
[ 12699.029] 	Module class: X.Org Video Driver
[ 12699.029] 	ABI class: X.Org Video Driver, version 24.0
[ 12699.029] (II) LoadModule: "vesa"
[ 12699.029] (II) Loading /usr/lib/xorg/modules/drivers/vesa_drv.so
[ 12699.048] (II) Module vesa: vendor="X.Org Foundation"
[ 12699.048] 	compiled for 1.20.4, module version = 2.4.0
[ 12699.048] 	Module class: X.Org Video Driver
[ 12699.048] 	ABI class: X.Org Video Driver, version 24.0
[ 12699.048] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[ 12699.048] (II) FBDEV: driver for framebuffer: fbdev
[ 12699.048] (II) VESA: driver for VESA chipsets: vesa
[ 12699.048] (II) modeset(0): using drv /dev/dri/card0
[ 12699.048] (WW) Falling back to old probe method for fbdev
[ 12699.048] (II) Loading sub module "fbdevhw"
[ 12699.048] (II) LoadModule: "fbdevhw"
[ 12699.048] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[ 12699.057] (II) Module fbdevhw: vendor="X.Org Foundation"
[ 12699.057] 	compiled for 1.20.13, module version = 0.0.2
[ 12699.057] 	ABI class: X.Org Video Driver, version 24.1
[ 12699.057] (II) modeset(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[ 12699.057] (==) modeset(0): Depth 24, (==) framebuffer bpp 32
[ 12699.057] (==) modeset(0): RGB weight 888
[ 12699.057] (==) modeset(0): Default visual is TrueColor
[ 12699.057] (II) Loading sub module "glamoregl"
[ 12699.057] (II) LoadModule: "glamoregl"
[ 12699.057] (II) Loading /usr/lib/xorg/modules/libglamoregl.so
[ 12699.095] (II) Module glamoregl: vendor="X.Org Foundation"
[ 12699.095] 	compiled for 1.20.13, module version = 1.0.1
[ 12699.095] 	ABI class: X.Org ANSI C Emulation, version 0.4
[ 12699.369] (II) modeset(0): Refusing to try glamor on llvmpipe
[ 12699.408] (EE) modeset(0): glamor initialization failed
[ 12699.408] (II) modeset(0): ShadowFB: preferred NO, enabled NO
[ 12699.408] (II) modeset(0): Output Virtual-1 has no monitor section
[ 12699.408] (II) modeset(0): EDID for output Virtual-1
[ 12699.408] (II) modeset(0): Manufacturer: RHT  Model: 1234  Serial#: 0
[ 12699.408] (II) modeset(0): Year: 2014  Week: 42
[ 12699.408] (II) modeset(0): EDID Version: 1.4
[ 12699.408] (II) modeset(0): Digital Display Input
[ 12699.408] (II) modeset(0): 8 bits per channel
[ 12699.409] (II) modeset(0): Digital interface is DisplayPort
[ 12699.409] (II) modeset(0): Max Image Size [cm]: horiz.: 26  vert.: 19
[ 12699.409] (II) modeset(0): Gamma: 2.20
[ 12699.409] (II) modeset(0): No DPMS capabilities specified
[ 12699.409] (II) modeset(0): Supported color encodings: RGB 4:4:4
[ 12699.409] (II) modeset(0): Default color space is primary color space
[ 12699.409] (II) modeset(0): First detailed timing is preferred mode
[ 12699.409] (II) modeset(0): Preferred mode is native pixel format and refresh rate
[ 12699.409] (II) modeset(0): redX: 0.640 redY: 0.330   greenX: 0.300 greenY: 0.600
[ 12699.409] (II) modeset(0): blueX: 0.150 blueY: 0.060   whiteX: 0.312 whiteY: 0.329
[ 12699.409] (II) modeset(0): Supported established timings:
[ 12699.409] (II) modeset(0): 640x480@60Hz
[ 12699.409] (II) modeset(0): 800x600@60Hz
[ 12699.409] (II) modeset(0): 1024x768@60Hz
[ 12699.409] (II) modeset(0): Manufacturer's mask: 0
[ 12699.409] (II) modeset(0): Supported standard timings:
[ 12699.409] (II) modeset(0): #0: hsize: 2048  vsize 1152  refresh: 60  vid: 49377
[ 12699.409] (II) modeset(0): #1: hsize: 1920  vsize 1080  refresh: 60  vid: 49361
[ 12699.409] (II) modeset(0): #2: hsize: 1920  vsize 1200  refresh: 60  vid: 209
[ 12699.409] (II) modeset(0): #3: hsize: 1600  vsize 1200  refresh: 60  vid: 16553
[ 12699.409] (II) modeset(0): #4: hsize: 1680  vsize 1050  refresh: 60  vid: 179
[ 12699.409] (II) modeset(0): #5: hsize: 1440  vsize 900  refresh: 60  vid: 149
[ 12699.409] (II) modeset(0): #6: hsize: 1280  vsize 1024  refresh: 60  vid: 32897
[ 12699.409] (II) modeset(0): #7: hsize: 1280  vsize 960  refresh: 60  vid: 16513
[ 12699.409] (II) modeset(0): Supported detailed timing:
[ 12699.409] (II) modeset(0): clock: 82.3 MHz   Image Size:  260 x 195 mm
[ 12699.409] (II) modeset(0): h_active: 1024  h_sync: 1280  h_sync_end 1310 h_blank_end 1382 h_border: 0
[ 12699.409] (II) modeset(0): v_active: 768  v_sync: 771  v_sync_end 774 v_blanking: 794 v_border: 0
[ 12699.409] (II) modeset(0): Established timings III: (not decoded)
[ 12699.409] (II) modeset(0): Ranges: V min: 50 V max: 125 Hz, H min: 30 H max: 160 kHz,
[ 12699.409] (II) modeset(0): Monitor name: QEMU Monitor
[ 12699.409] (II) modeset(0): Number of EDID sections to follow: 1
[ 12699.409] (II) modeset(0): EDID (in hex):
[ 12699.409] (II) modeset(0): 	00ffffffffffff004914341200000000
[ 12699.409] (II) modeset(0): 	2a180104a51a137806ee91a3544c9926
[ 12699.409] (II) modeset(0): 	0f5054210800e1c0d1c0d100a940b300
[ 12699.409] (II) modeset(0): 	9500818081402520006641001a30001e
[ 12699.409] (II) modeset(0): 	334004c310000018000000f7000a0040
[ 12699.409] (II) modeset(0): 	82002820000000000000000000fd0032
[ 12699.409] (II) modeset(0): 	7d1ea0ff010a202020202020000000fc
[ 12699.409] (II) modeset(0): 	0051454d55204d6f6e69746f720a013d
[ 12699.409] (II) modeset(0): 	02030a00457d6560591f000000100000
[ 12699.409] (II) modeset(0): 	00000000000000000000000000000010
[ 12699.409] (II) modeset(0): 	00000000000000000000000000000000
[ 12699.409] (II) modeset(0): 	00100000000000000000000000000000
[ 12699.409] (II) modeset(0): 	00000010000000000000000000000000
[ 12699.409] (II) modeset(0): 	00000000001000000000000000000000
[ 12699.409] (II) modeset(0): 	00000000000000100000000000000000
[ 12699.409] (II) modeset(0): 	00000000000000000000000000000092
[ 12699.409] (II) modeset(0): Printing probed modes for output Virtual-1
[ 12699.409] (II) modeset(0): Modeline "1024x768"x75.0   82.29  1024 1280 1310 1382  768 771 774 794 -hsync -vsync (59.5 kHz eP)
[ 12699.409] (II) modeset(0): Modeline "1920x1080"x60.0  148.50  1920 2008 2052 2200  1080 1084 1089 1125 -hsync -vsync (67.5 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1920x1080"x50.0  148.50  1920 2448 2492 2640  1080 1084 1089 1125 +hsync +vsync (56.2 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1600x1200"x60.0  162.00  1600 1664 1856 2160  1200 1201 1204 1250 +hsync +vsync (75.0 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1680x1050"x60.0  146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync (65.3 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1400x1050"x60.0  121.75  1400 1488 1632 1864  1050 1053 1057 1089 -hsync +vsync (65.3 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1280x1024"x60.0  108.00  1280 1328 1440 1688  1024 1025 1028 1066 +hsync +vsync (64.0 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1440x900"x59.9  106.50  1440 1520 1672 1904  900 903 909 934 -hsync +vsync (55.9 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1280x960"x60.0  108.00  1280 1376 1488 1800  960 961 964 1000 +hsync +vsync (60.0 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1360x768"x60.0   85.50  1360 1424 1536 1792  768 771 777 795 +hsync +vsync (47.7 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1280x768"x59.9   79.50  1280 1344 1472 1664  768 771 778 798 -hsync +vsync (47.8 kHz e)
[ 12699.409] (II) modeset(0): Modeline "1024x768"x60.0   65.00  1024 1048 1184 1344  768 771 777 806 -hsync -vsync (48.4 kHz e)
[ 12699.409] (II) modeset(0): Modeline "800x600"x60.3   40.00  800 840 968 1056  600 601 605 628 +hsync +vsync (37.9 kHz e)
[ 12699.409] (II) modeset(0): Modeline "640x480"x60.0   25.20  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
[ 12699.409] (II) modeset(0): Modeline "640x480"x59.9   25.18  640 656 752 800  480 490 492 525 -hsync -vsync (31.5 kHz e)
[ 12699.409] (II) modeset(0): Output Virtual-1 connected
[ 12699.409] (II) modeset(0): Using exact sizes for initial modes
[ 12699.409] (II) modeset(0): Output Virtual-1 using initial mode 1024x768 +0+0
[ 12699.409] (==) modeset(0): Using gamma correction (1.0, 1.0, 1.0)
[ 12699.409] (==) modeset(0): DPI set to (96, 96)
[ 12699.409] (II) Loading sub module "fb"
[ 12699.409] (II) LoadModule: "fb"
[ 12699.409] (II) Loading /usr/lib/xorg/modules/libfb.so
[ 12699.421] (II) Module fb: vendor="X.Org Foundation"
[ 12699.421] 	compiled for 1.20.13, module version = 1.0.0
[ 12699.421] 	ABI class: X.Org ANSI C Emulation, version 0.4
[ 12699.421] (II) UnloadModule: "fbdev"
[ 12699.421] (II) Unloading fbdev
[ 12699.421] (II) UnloadSubModule: "fbdevhw"
[ 12699.421] (II) Unloading fbdevhw
[ 12699.421] (II) UnloadModule: "vesa"
[ 12699.421] (II) Unloading vesa
[ 12699.429] (==) modeset(0): Backing store enabled
[ 12699.429] (==) modeset(0): Silken mouse enabled
[ 12699.435] (II) modeset(0): Initializing kms color map for depth 24, 8 bpc.
[ 12699.435] (==) modeset(0): DPMS enabled
[ 12699.435] (II) Initializing extension Generic Event Extension
[ 12699.435] (II) Initializing extension SHAPE
[ 12699.436] (II) Initializing extension MIT-SHM
[ 12699.436] (II) Initializing extension XInputExtension
[ 12699.436] (II) Initializing extension XTEST
[ 12699.436] (II) Initializing extension BIG-REQUESTS
[ 12699.436] (II) Initializing extension SYNC
[ 12699.437] (II) Initializing extension XKEYBOARD
[ 12699.437] (II) Initializing extension XC-MISC
[ 12699.437] (II) Initializing extension SECURITY
[ 12699.437] (II) Initializing extension XFIXES
[ 12699.437] (II) Initializing extension RENDER
[ 12699.437] (II) Initializing extension RANDR
[ 12699.437] (II) Initializing extension COMPOSITE
[ 12699.437] (II) Initializing extension DAMAGE
[ 12699.438] (II) Initializing extension MIT-SCREEN-SAVER
[ 12699.438] (II) Initializing extension DOUBLE-BUFFER
[ 12699.438] (II) Initializing extension RECORD
[ 12699.438] (II) Initializing extension DPMS
[ 12699.438] (II) Initializing extension Present
[ 12699.438] (II) Initializing extension DRI3
[ 12699.438] (II) Initializing extension X-Resource
[ 12699.438] (II) Initializing extension XVideo
[ 12699.438] (II) Initializing extension XVideo-MotionCompensation
[ 12699.438] (II) Initializing extension SELinux
[ 12699.438] (II) SELinux: Disabled on system
[ 12699.438] (II) Initializing extension GLX
[ 12699.439] (II) AIGLX: Screen 0 is not DRI2 capable
[ 12699.446] (II) IGLX: Loaded and initialized swrast
[ 12699.446] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[ 12699.446] (II) Initializing extension XFree86-VidModeExtension
[ 12699.446] (II) Initializing extension XFree86-DGA
[ 12699.447] (II) Initializing extension XFree86-DRI
[ 12699.447] (II) Initializing extension DRI2
[ 12699.447] (II) modeset(0): Damage tracking initialized
[ 12699.447] (II) modeset(0): Setting screen physical size to 270 x 203
[ 12699.683] (II) config/udev: Adding input device Power Button (/dev/input/event0)
[ 12699.684] (**) Power Button: Applying InputClass "libinput keyboard catchall"
[ 12699.684] (II) LoadModule: "libinput"
[ 12699.685] (II) Loading /usr/lib/xorg/modules/input/libinput_drv.so
[ 12699.784] (II) Module libinput: vendor="X.Org Foundation"
[ 12699.784] 	compiled for 1.20.4, module version = 0.29.0
[ 12699.784] 	Module class: X.Org XInput Driver
[ 12699.784] 	ABI class: X.Org XInput driver, version 24.1
[ 12699.784] (II) Using input driver 'libinput' for 'Power Button'
[ 12699.786] (II) systemd-logind: got fd for /dev/input/event0 13:64 fd 22 paused 0
[ 12699.786] (**) Power Button: always reports core events
[ 12699.786] (**) Option "Device" "/dev/input/event0"
[ 12699.787] (**) Option "_source" "server/udev"
[ 12699.824] (II) event0  - Power Button: is tagged by udev as: Keyboard
[ 12699.825] (II) event0  - Power Button: device is a keyboard
[ 12699.825] (II) event0  - Power Button: device removed
[ 12699.825] (**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input0/event0"
[ 12699.825] (II) XINPUT: Adding extended input device "Power Button" (type: KEYBOARD, id 6)
[ 12699.825] (**) Option "xkb_model" "pc105"
[ 12699.825] (**) Option "xkb_layout" "pl"
[ 12699.843] (II) event0  - Power Button: is tagged by udev as: Keyboard
[ 12699.843] (II) event0  - Power Button: device is a keyboard
[ 12699.844] (II) config/udev: Adding input device QEMU QEMU USB Tablet (/dev/input/event4)
[ 12699.844] (**) QEMU QEMU USB Tablet: Applying InputClass "libinput pointer catchall"
[ 12699.844] (II) Using input driver 'libinput' for 'QEMU QEMU USB Tablet'
[ 12699.903] (II) systemd-logind: got fd for /dev/input/event4 13:68 fd 25 paused 0
[ 12699.903] (**) QEMU QEMU USB Tablet: always reports core events
[ 12699.903] (**) Option "Device" "/dev/input/event4"
[ 12699.903] (**) Option "_source" "server/udev"
[ 12699.904] (II) event4  - QEMU QEMU USB Tablet: is tagged by udev as: Mouse
[ 12699.905] (II) event4  - QEMU QEMU USB Tablet: device is a pointer
[ 12699.905] (II) event4  - QEMU QEMU USB Tablet: device removed
[ 12699.905] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:01.2/usb1/1-1/1-1:1.0/0003:0627:0001.0001/input/input5/event4"
[ 12699.905] (II) XINPUT: Adding extended input device "QEMU QEMU USB Tablet" (type: MOUSE, id 7)
[ 12699.905] (**) Option "AccelerationScheme" "none"
[ 12699.905] (**) QEMU QEMU USB Tablet: (accel) selected scheme none/0
[ 12699.905] (**) QEMU QEMU USB Tablet: (accel) acceleration factor: 2.000
[ 12699.905] (**) QEMU QEMU USB Tablet: (accel) acceleration threshold: 4
[ 12699.906] (II) event4  - QEMU QEMU USB Tablet: is tagged by udev as: Mouse
[ 12699.906] (II) event4  - QEMU QEMU USB Tablet: device is a pointer
[ 12699.907] (II) config/udev: Adding input device QEMU QEMU USB Tablet (/dev/input/mouse2)
[ 12699.907] (II) No input driver specified, ignoring this device.
[ 12699.907] (II) This device may have been added with another device file.
[ 12699.908] (II) config/udev: Adding input device AT Translated Set 2 keyboard (/dev/input/event1)
[ 12699.908] (**) AT Translated Set 2 keyboard: Applying InputClass "libinput keyboard catchall"
[ 12699.908] (II) Using input driver 'libinput' for 'AT Translated Set 2 keyboard'
[ 12699.909] (II) systemd-logind: got fd for /dev/input/event1 13:65 fd 26 paused 0
[ 12699.909] (**) AT Translated Set 2 keyboard: always reports core events
[ 12699.909] (**) Option "Device" "/dev/input/event1"
[ 12699.909] (**) Option "_source" "server/udev"
[ 12699.910] (II) event1  - AT Translated Set 2 keyboard: is tagged by udev as: Keyboard
[ 12699.910] (II) event1  - AT Translated Set 2 keyboard: device is a keyboard
[ 12699.910] (II) event1  - AT Translated Set 2 keyboard: device removed
[ 12699.910] (**) Option "config_info" "udev:/sys/devices/platform/i8042/serio0/input/input1/event1"
[ 12699.910] (II) XINPUT: Adding extended input device "AT Translated Set 2 keyboard" (type: KEYBOARD, id 8)
[ 12699.910] (**) Option "xkb_model" "pc105"
[ 12699.910] (**) Option "xkb_layout" "pl"
[ 12699.911] (II) event1  - AT Translated Set 2 keyboard: is tagged by udev as: Keyboard
[ 12699.911] (II) event1  - AT Translated Set 2 keyboard: device is a keyboard
[ 12699.912] (II) config/udev: Adding input device VirtualPS/2 VMware VMMouse (/dev/input/event3)
[ 12699.912] (**) VirtualPS/2 VMware VMMouse: Applying InputClass "libinput pointer catchall"
[ 12699.912] (II) Using input driver 'libinput' for 'VirtualPS/2 VMware VMMouse'
[ 12699.913] (II) systemd-logind: got fd for /dev/input/event3 13:67 fd 27 paused 0
[ 12699.913] (**) VirtualPS/2 VMware VMMouse: always reports core events
[ 12699.913] (**) Option "Device" "/dev/input/event3"
[ 12699.913] (**) Option "_source" "server/udev"
[ 12699.914] (II) event3  - VirtualPS/2 VMware VMMouse: is tagged by udev as: Mouse
[ 12699.914] (II) event3  - VirtualPS/2 VMware VMMouse: device is a pointer
[ 12699.914] (II) event3  - VirtualPS/2 VMware VMMouse: device removed
[ 12699.915] (**) Option "config_info" "udev:/sys/devices/platform/i8042/serio1/input/input3/event3"
[ 12699.915] (II) XINPUT: Adding extended input device "VirtualPS/2 VMware VMMouse" (type: MOUSE, id 9)
[ 12699.915] (**) Option "AccelerationScheme" "none"
[ 12699.915] (**) VirtualPS/2 VMware VMMouse: (accel) selected scheme none/0
[ 12699.915] (**) VirtualPS/2 VMware VMMouse: (accel) acceleration factor: 2.000
[ 12699.915] (**) VirtualPS/2 VMware VMMouse: (accel) acceleration threshold: 4
[ 12699.916] (II) event3  - VirtualPS/2 VMware VMMouse: is tagged by udev as: Mouse
[ 12699.916] (II) event3  - VirtualPS/2 VMware VMMouse: device is a pointer
[ 12699.916] (II) config/udev: Adding input device VirtualPS/2 VMware VMMouse (/dev/input/mouse1)
[ 12699.916] (II) No input driver specified, ignoring this device.
[ 12699.916] (II) This device may have been added with another device file.
[ 12699.917] (II) config/udev: Adding input device VirtualPS/2 VMware VMMouse (/dev/input/event2)
[ 12699.917] (**) VirtualPS/2 VMware VMMouse: Applying InputClass "libinput pointer catchall"
[ 12699.917] (II) Using input driver 'libinput' for 'VirtualPS/2 VMware VMMouse'
[ 12699.918] (II) systemd-logind: got fd for /dev/input/event2 13:66 fd 28 paused 0
[ 12699.918] (**) VirtualPS/2 VMware VMMouse: always reports core events
[ 12699.918] (**) Option "Device" "/dev/input/event2"
[ 12699.918] (**) Option "_source" "server/udev"
[ 12699.919] (II) event2  - VirtualPS/2 VMware VMMouse: is tagged by udev as: Mouse
[ 12699.919] (II) event2  - VirtualPS/2 VMware VMMouse: device is a pointer
[ 12699.919] (II) event2  - VirtualPS/2 VMware VMMouse: device removed
[ 12699.919] (**) Option "config_info" "udev:/sys/devices/platform/i8042/serio1/input/input4/event2"
[ 12699.919] (II) XINPUT: Adding extended input device "VirtualPS/2 VMware VMMouse" (type: MOUSE, id 10)
[ 12699.919] (**) Option "AccelerationScheme" "none"
[ 12699.919] (**) VirtualPS/2 VMware VMMouse: (accel) selected scheme none/0
[ 12699.919] (**) VirtualPS/2 VMware VMMouse: (accel) acceleration factor: 2.000
[ 12699.919] (**) VirtualPS/2 VMware VMMouse: (accel) acceleration threshold: 4
[ 12699.920] (II) event2  - VirtualPS/2 VMware VMMouse: is tagged by udev as: Mouse
[ 12699.921] (II) event2  - VirtualPS/2 VMware VMMouse: device is a pointer
[ 12699.921] (II) config/udev: Adding input device VirtualPS/2 VMware VMMouse (/dev/input/mouse0)
[ 12699.921] (II) No input driver specified, ignoring this device.
[ 12699.921] (II) This device may have been added with another device file.
[ 12701.646] (**) Option "fd" "22"
[ 12701.646] (II) event0  - Power Button: device removed
[ 12701.646] (**) Option "fd" "25"
[ 12701.646] (II) event4  - QEMU QEMU USB Tablet: device removed
[ 12701.646] (**) Option "fd" "26"
[ 12701.646] (II) event1  - AT Translated Set 2 keyboard: device removed
[ 12701.646] (**) Option "fd" "27"
[ 12701.646] (II) event3  - VirtualPS/2 VMware VMMouse: device removed
[ 12701.646] (**) Option "fd" "28"
[ 12701.646] (II) event2  - VirtualPS/2 VMware VMMouse: device removed
[ 12701.647] (II) UnloadModule: "libinput"
[ 12701.647] (II) systemd-logind: releasing fd for 13:66
[ 12701.690] (II) UnloadModule: "libinput"
[ 12701.690] (II) systemd-logind: releasing fd for 13:67
[ 12701.730] (II) UnloadModule: "libinput"
[ 12701.730] (II) systemd-logind: releasing fd for 13:65
[ 12701.746] (II) UnloadModule: "libinput"
[ 12701.746] (II) systemd-logind: releasing fd for 13:68
[ 12701.779] (II) UnloadModule: "libinput"
[ 12701.779] (II) systemd-logind: releasing fd for 13:64
[ 12701.849] (II) Server terminated successfully (0). Closing log file`

I very rarely use full desktop on this machine, but I think it worked before. I can double check once I restore system backup.
Either way, I know for a fact that calibre worked in a gui mode over ssh -X, all the way until I attempted installing sigil.

**Comment by kevinhendricks** [comment] 2022-07-10 21:10
There is nothing in your startx log that is even Sigil related.  My guess is you have updated a driver or some other library which is breaking X and therefore neither calibre or Sigil will work.

**Comment by kevinhendricks** [comment] 2022-07-11 12:04
Closing this as not a bug in Sigil.  

Please feel free to post additional information here and if it warrants action on Sigil's part we will happily reopen this bug.

Building and installing Sigil on Linux following our build instructions does not interfere with calibre or and X or anything else.  You have most probably updated or changed some package related to X such as a video driver or something else used by X.

**Closed by kevinhendricks** 2022-07-11 12:04 UTC
Labels: bug
