### ISSUE TITLE
Is the code-view or book-view switching function lost?

### ISSUE THREAD

**Issue by caidreamh** [Sigil-Ebook/Sigil#469] opened 2019-11-24 02:41 UTC
Is the code-view or book-view switching function lost?

After checking the wrong place in the book-view, we can edit immediately by switching to code-view.
It was very convenient

**Comment by kevinhendricks** [comment] 2019-11-24 02:58
BookView has been gone for 5 releases. Use the Views menu to show the Preview Window.  For simple visual editing and proofing use PageEdit (see the PageEdit repository of the Sigil-Ebook repo) and set it as Sigil's preferred external xhtml editor.

If you want PageEdit to access all xhtml pages of the epub currently being edited in Sigil, open the content.opf tab in BookBrowser before running Sigil's preferred xhtml editor.

Closing this as it is not a bug.  Please use our MobileRead Forum to get help, not Sigil's bug reports

**Closed by kevinhendricks** 2019-11-24 02:58 UTC
