### ISSUE TITLE
Remove 0.9.17 notes from Linux instructions on Wiki?

### ISSUE THREAD

**Issue by matkoniecz** [Sigil-Ebook/Sigil#660] opened 2021-12-17 09:20 UTC
I think that it is fine to consider 

> Avoid updating to lxml 4.4.0 until we work out some compatibility issues with our sigil_bs4 module. Downgrade to lxml 4.3.4 in the meantime. EDIT: this one has been fixed in the latest github master branch. That fix will be included in Sigil 0.9.17 (it can also be safely backported to earlier Sigil versions).

as not worth mentioning? Even Ubuntu managed to upgrade to 1.1.0 by now

https://github.com/Sigil-Ebook/Sigil/wiki/Linux-Notes

**Comment by kevinhendricks** [comment] 2021-12-17 10:43
Closing this as a duplicate of your #661 issue.

**Closed by kevinhendricks** 2021-12-17 10:43 UTC
