### ISSUE TITLE
Tab Behavior in Code View

### ISSUE THREAD

**Issue by Evolution0** [Sigil-Ebook/Sigil#238] opened 2016-08-28 01:48 UTC
Some editors (Sublime for example) allow you to highlight and tab multiple lines at a time without erasing everything that is highlighted, adding this feature would make it easier to create cleaner (x)html (rather than returning to the beginning of the line and tabbing each one)

**Comment by kevinhendricks** [comment] 2016-08-28 01:58
Or just enable cleaning with PrettyPrint

**Comment by dougmassay** [comment] 2016-08-28 02:07
That's what I was thinking. Why "tab" at all? Use the Reformat HTML->Mend and Prettify feature.

**Comment by kevinhendricks** [comment] 2016-08-28 20:30
Closing this as not a bug.  If you want to discuss this further, the best place would be Sigil's User's forum on www.mobileread.com as this is more a feature request.

**Closed by kevinhendricks** 2016-08-28 20:30 UTC
