### ISSUE TITLE
Sigil segmentation fault in Plasma 5 (only)

### ISSUE THREAD

**Issue by hifi25nl** [Sigil-Ebook/Sigil#114] opened 2015-09-19 09:56 UTC
Please take a look at
https://bbs.archlinux.org/viewtopic.php?id=202046

Sigil has a segmentation fault only in Plasma 5 (also with sigil-git)
In the thread reported above there is also a gdb output

**Comment by kevinhendricks** [comment] 2015-09-19 14:26
Your report is missing details.  Which exact version of Qt?  Which version of Sigil? Whose builds are you using?  Your backtrace indicates an issue with Qt creating icons via pixmaps and not something specific to Sigil.

**Comment by kevinhendricks** [comment] 2015-09-19 14:34
A quick google search of Plasma 5 and Qt bugs lists many crash reports related to incorrect QT_PLUGIN_PATH, icon issues and etc.  Given Sigil works well on other platforms and desktop/display combinations on your platform, I suggest you file a bug report in Qt as well, which is most likely the issue.

**Comment by hifi25nl** [comment] 2015-09-19 15:07
Ok.
Qt5 version 5.5
Sigil version 0.8.7 --> https://www.archlinux.org/packages/community/x86_64/sigil
Sigil git (updated to today) --> https://aur.archlinux.org/packages.php?ID=184661

About qt_plugin_path:

[piero@archlinux ~]$ env | grep QT_PLUGIN_PATH
QT_PLUGIN_PATH=/usr/lib/qt/plugins:

**Comment by kevinhendricks** [comment] 2015-09-19 15:14
According to the bug reports at Qt, desktop environments should not be setting QT_PLUGIN_PATH at all in their startkde scripts.

See https://bugreports.qt.io/browse/QTBUG-46714 and linked bug reports from redhat.

Closing this issue.  Please reopen if the fix provided their does not work.

**Comment by kevinhendricks** [comment] 2015-09-21 00:03
I noticed from your ArchLinux bbs post that you are still having issues.  Unfortunately, I have no way of helping to track down this issue.  I do not use the Plasma 5 Display or even have access to a Linux box that supports it.  Our primary development platforms are Windows and Mac OS X.
There are simply too many variations of set-ups and builds on Linux for our small 2 developer team to be able to support it. 

Right now, we do test builds on Linux with Qt 5.4.2. and Python 3.4 and these work just fine.

According to the Qt 5.5 "Known Issues" page there are problems on Linux with Qt built with gcc 4.9.2 since that compiler version is known not to compile Qt properly.  So please check to see which version of gcc was used to compile Qt.

If someone from ArchLinux were to provide an account with ssh access to a box running Plasma 5, with a debug build of Qt and either Python 3.4.3 or Python 3.5 with lxml and bs4 installed alongside cmake-3.0,  I would be happy to try to build a debug version of  the latest Sigil git version (our forthcoming Sigil 0.8.900 series of builds) and try and track this down (assuming it is not a gcc related compiler issue).  Aside from that, there really isn't much help I can provide as currently it is not a supported configuration or even platform for us.

Take care,

Kevin

**Comment by eli-schwartz** [comment] 2015-09-25 18:25
Kevin -- I gave you ssh access in private through MobileRead. ;)
And Sigil is cloned from git at ~/sigil-source
The current sigil (direct from the repositories) would have been built by gcc 5.1.0


I have the account I created for you logged into Plasma 5, sigil crashes when started.
It can't be the QT_PLUGIN_PATH in startkde, as the bugreport indicates it is fixed in kde5.4.0 and Arch is on kde5.4.1
/usr/bin/startkde doesn't set it anymore.

I created a tmux session in Plasma to attach to so you can see the CLI output under normal GUI conditions.


Not sure about a debug build of Qt, there are no debug packages in the repos. The official PKGBUILD wasn't working so well, even without switching to the developer release -- maybe I'll have more luck with makechrootpkg from devtools (which runs in a minimal chroot). At least it's still running this morning, so, promising.

**Comment by JHirte** [comment] 2015-10-01 16:31
Same here on Gentoo with Qt-5.5 and KF5/Plasma from git. I get a segfault in QFileIconProvider::options() const (this=0x7fffffffd150) at itemviews/qfileiconprovider.cpp:291 when starting the program. If a full backtrace helps, I can provide it.

For now, a workaround is to unset KDE_FULL_SESSION and XDG_CURRENT_DESKTOP. It's needed to unset both.

**Comment by kevinhendricks** [comment] 2015-10-01 16:37
Hi,

Yes, I have been so tied up tracking down an instability caused by the VS2013 compiler issues that I have not had time to dig into this yet.

So yes, any full backtraces that can help me get a handle on this would be appreciated.

Your information on KDE_FULL_SESSION and XDG_CURRENT_DESKTOP are quite interesting.   I assume these are environment variables int eh KDE Desktop code environment and not in Qt itself.

if so, can you point to me the correct git repository on your end that houses the source code when these two environment variables are used so that I can see exactly what they are doing and try to track down what Sigil is doing that triggers these issues.

Thanks!

Kevin

**Comment by kevinhendricks** [comment] 2015-10-02 00:53
Reopening the issue

**Comment by kevinhendricks** [comment] 2015-10-02 03:57
Hi,
Is there any way to change the breeze.so widget style set to something else to see if it has an impact?
I notice it in the backtrace at frame 5 just before things start to go out into the weeds.

I am also curious about reports that "sudo sigil" work.  Sigil should never need to be run as root but if it does run that indicates either an environment variable change or permission change is needed for some reason.

Kevin

**Comment by JHirte** [comment] 2015-10-02 22:55
It's definitively an issue with Qt/KDE environment variables. It's not restricted to the breeze-theme of KDE. I've seen this with the oxygen-theme of KDE too.

About sudo, it's not needed to get root. It will work with the user, you're logged in. When I'm logged in as user jhirte, the following command works:
sudo -u jhirte sigil

Looks like Qt problems to me. Backtraces for the different KDE themes are in progress....

**Comment by kevinhendricks** [comment] 2015-10-05 17:10
@JHirte,
Any interesting backtraces?  Thanks,

Kevin

**Comment by chrisanthropic** [comment] 2015-10-16 22:27
@JHirte - thanks for the 'sudo' workaround. I've been downgrading a bunch of QT packages every time I need to use Sigil and this is much easier.

@kevinhendricks - thanks for looking into this when you can. I understand that Linux isn't your main use case and appreciate the time you put in.

**Comment by demmm** [comment] 2015-10-25 18:53
Seems here the issue of sigil segfaulting with Plasma 5 is resolved with the update to Qt 5.5.1, can only reproduce it with 5.5.0.

**Comment by kevinhendricks** [comment] 2015-10-25 19:07
Hi,
Glad to hear it. That means this never was a Sigil issue and should have been filed at Qt/KDE to begin with.  Thanks for letting me know.  I will now close this issue.

**Closed by kevinhendricks** 2015-10-25 19:07 UTC
