### ISSUE TITLE
Code View shows different Path than Text editor

### ISSUE THREAD

**Issue by shorshe** [Sigil-Ebook/Sigil#147] opened 2015-10-30 10:51 UTC
Please have a look at the last link on line 21.

White Background = Sigil source View
Black Background = Textmate

../Text/Section0033.xhtml#fn_1

vs.

./Section0033.xhtml#fn_1

Same file different Path. Is this expected behavior? 

![bildschirmfoto 2015-10-30 um 11 45 33](https://cloud.githubusercontent.com/assets/867891/10843895/12a8a736-7efc-11e5-854c-474f5b8be7b2.png)
![bildschirmfoto 2015-10-30 um 11 45 46](https://cloud.githubusercontent.com/assets/867891/10843894/12a52b88-7efc-11e5-8ee4-230de6eb7bb5.png)

**Comment by dougmassay** [comment] 2015-10-30 11:00
Yes. This is expected behavior. Sigil normalizes the physical structure of all epub zip archives it opens/saves and adjusts all links accordingly. It always has.

**Comment by shorshe** [comment] 2015-10-30 11:05
Ok, thanks! Never knew.
... I've got an Apple Ticket regarding this exact link. Seems they try and fail to expand the path.

ERROR ITMS-9000: "9783862487806.epub: OEBPS/Text/Section0010.xhtml(21): 'OEBPS/Text/./Section0033.xhtml': referenced resource missing in the package.. This error occurs 67 times.  (For more information refer to http://support.apple.com/kb/HT6213)" at Book

**Comment by dougmassay** [comment] 2015-10-30 11:18
You're not editing/adjusting any links after the final Sigil save are you? That's the only way I can see that kind of failure happening. Although it's not impossible that Sigil could be failing to properly update a link under certain circumstances, it's the first I've report I've heard of it if so.

Sigil should never intentionally create a link like 'OEBPS/Text/./Section0033.xhtml'. If you could upload a sample (a pre-sigil sample where everything is ok and a post-sigil sample with a broken link) somewhere we could retrieve them, we'd be happy to take a look it.

**Comment by dougmassay** [comment] 2015-10-31 01:37
I can't reproduce the type of invalid link you mentioned in your Apple ticket, so I'm going to close this issue for now. If you can provide a sample epub where Sigil fails to properly update all links, please feel free to reopen it.

**Comment by shorshe** [comment] 2015-10-31 14:39
It seems that Apple has problems creating the correct path.
Just to make sure:

My screenshots show the same state of the same file after saving with sigil. 
The path in the source view of sigil is only displayed differently but not actually written to file like this. 
correct?

**Comment by kevinhendricks** [comment] 2015-10-31 14:47
Hi,
Sorry, I develop on Mac and I am not seeing this.  So there is something strange going on.  So if you want us to "fix" this we need to reproduce it and the only way to do that is with a test case.  So please post an epub that shows this issue and we would be happy to try and track it down.  If you want to keep your epub test case private, post it someplace (not here!) and then go to MobileRead Forum and personal mail either DiapDealer or KevinH on that site with your link. 

Thanks,

KevinH

**Comment by dougmassay** [comment] 2015-10-31 14:52
> The path in the source view of sigil is only displayed differently but not actually written to file like this. 
correct?

No. The source view of Sigil is not display-only. The path displayed in your screenshot will be the path written after saving. But the point is, the opf file is also updated with the correct new path (after the epub's structure has been normalized), as will any other links that point to that xhtml file within the epub.

The only thing that I can think of that would cause this kind of issue is if someone opens the finished epub outside of Sigil and modifies a link without properly updating all other references to it.

I have no idea where that weird path with the relative '/./' portion in the middle of it would come from (the one displayed in the Apple ticket). To my knowledge, Sigil should never create a path like that. If you can provide a sample where it does happen, please use Kevin's recommendations for getting it to us.

**Comment by shorshe** [comment] 2015-10-31 15:03
> No. The source view of Sigil is not display-only. The path displayed in your screenshot will be the path written after saving.

Ok, thanks. Now we are on the same page. This is exactly the behavior I expected.

I'll try to provide a test case on Monday.

I'm on a mac (ElCapitan) too.

**Comment by shorshe** [comment] 2015-11-02 09:43
I can now reproduce the case.
It's the link in line 21.

- Open file in sigil. Change the path notation from ../Text/Section0033.xhtml to ./Section0033.xhtml.
- Save
- Open again
- Sigil shows:
![bildschirmfoto 2015-11-02 um 10 38 39](https://cloud.githubusercontent.com/assets/867891/10878507/4f476048-814e-11e5-8d4b-eee1b29b5de2.png)
- Close file.
- Unzip ePub an look at Section0010.xhml in Text editor:
![bildschirmfoto 2015-11-02 um 10 42 39](https://cloud.githubusercontent.com/assets/867891/10878524/77f13456-814e-11e5-85ed-744d2b31f275.png)




here is my stripped down test file:
https://www.dropbox.com/s/5dbgcckvlg3zp9p/9783862487806_part.epub?dl=0

**Comment by dougmassay** [comment] 2015-11-02 12:38
Hmmm. I see what you're saying. It appears that under certain circumstances, the SourceUpdates routines (which run upon opening an epub) are correctly adjusting the manually altered link (as evidenced by the correct href Code View), but are not being written to disk (as evidenced by the external examination of the xhtml file). That's just a guess for now.

Note that Sigil is not never to automatically fix broken/invalid links (which is what your manually altered href is, by the way), but that still doesn't explain the disparity between what's displayed in Code View and what's being saved to disk.

Thanks very much for the report (and the perseverance), we'll look into it.

Officially reopening this issue.

**Comment by kevinhendricks** [comment] 2015-11-02 12:56
Not a bug.  If you read the sequence the user is doing the following:

1) opening a file, 2) editing it, 3) saving it, 4) unzipping and opening saved file with text editor, 5) then opening the epub file and they the links the way Sigil sets them when opening all  epubs.  Upon the second open in Sigil, the link will be updated automatically to the format Sigil sets, but nothing is written to disk until a save is done by the user.

This is exactly expected behaviour.  ALL links upon opening an epub in Sigil are updated to the format Sigil wants, but no changes to the files on disk are made until the user saves it.  So what the file says and what Sigil says can be different and in most cases will be especially if the file was read in using a different layout

Given, that the links the way Sigil sets them is exactly correct, none of this would create an issue for validation.  The user editing the file to change the links and then saving it will see what they edited and saved inside a text editor, but the next time they opened it in Sigil, they would see the links updated to what Sigil wants.

So this is not a bug. 

Kevin

**Comment by dougmassay** [comment] 2015-11-02 13:07
Thanks for the explanation Kevin. That makes sense. So the manually broken
is correctly saved (which is why Apple's verification process flags it as
wrong). And upon reopening, Sigil is "fixing" the link (hence the correct
href in Code View), but unless another Save is done, that fix is not
committed to disk.

Not a bug. If you read the sequence the user is doing the following:

1) opening a file, 2) editing it, 3) saving it, 4) unzipping and opening
saved file with text editor, 5) then opening the epub file and they the
links the way Sigil sets them when opening all epubs. Upon the second open
in Sigil, the link will be updated automatically to the format Sigil sets,
but nothing is written to disk until a save is done by the user.

This is exactly expected behaviour. ALL links upon opening an epub in Sigil
are updated to the format Sigil wants, but no changes to the files on disk
are made until the user saves it. So what the file says and what Sigil says
can be different and in most cases will be especially if the file was read
in using a different layout

Given, that the links the way Sigil sets them is exactly correct, none of
this would create an issue for validation. The user editing the file to
change the links and then saving it will see what they edited and saved
inside a text editor, but the next time they opened it in Sigil, they would
see the links updated to what Sigil wants.

So this is not a bug.

Kevin

—
Reply to this email directly or view it on GitHub
<https://github.com/Sigil-Ebook/Sigil/issues/147#issuecomment-153009538>.

**Comment by shorshe** [comment] 2015-11-02 13:13
I see your point Kevin.
Shouldn't sigil mark the file as unsaved, then?

**Comment by kevinhendricks** [comment] 2015-11-02 15:26
Sigil never saves anything until the user tells it too.  Just understand Sigil always make changes on loading any epub to update links.  That is the way Sigil has always worked.   If you do not save, any changes made will be lost, just like any other text editor.   

 As for your link, technically it should be correct from any xhtml file, just not correct if used in the content.opf or in the toc.ncx when written that way.  Not sure why Apple or your distributor would barf on that.    You might want to try running FlightCrew and/or epubcheck from within Sigil (both are available as plugins) and if they say all is okay, then save the epub.   They will tell you if any link is incorrect or not.

Take care,
Kevin

**Closed by kevinhendricks** 2015-11-02 15:26 UTC

**Comment by shorshe** [comment] 2015-11-02 17:45
Hi Kevin.

Please let me clarify. I do not want sigil to save for me. I want an indication of the state of my document. If sigil changes something in my document it is in an unsaved state. 
As in: there are changes to the files, which are not written to disk. 

Wouldn't this be consistent with every other text-editor?

Epubcheck and Flightcrew had no issues with the document. The Problem lies with Apple I think. Problem was, I couldn't even find the links Apple was having Problems with.

**Comment by kevinhendricks** [comment] 2015-11-02 18:03
Again, Sigil made no changes to your files.  Every time you open an epub in Sigil, links are updated, entities may be converted, and the files are all parsed by the gumbo parser and are reserialized just to make those source updates.  You have to save the epub if you want those changes to be kept.  They are always made to ensure that the epub is valid enough to be displayed in BookView if needed and fits the Sigil fixed format.   

This is well known for Sigil user's and so writing something to the status bar that Sigil *may* have made changes in what you see on the screen but not to what is in your files simply doesn't add anything.  Given you did not know Sigil does that and thought it was similar to using a text editor on unzipped files,  I can see your point but nothing need change with Sigil, just with your understanding of how Sigil works and has always worked.

**Comment by eli-schwartz** [comment] 2015-11-03 00:16
If you want an EPUB editor that does not use a fixed format and/or make changes for you, but just wraps an EPUB inside a text editor, use calibre's Editor. (It also doesn't have Book View, which explains a lot...)



An indicator that the EPUB is in an unsaved state upon opening (because it **always** is) is redundant, and would be better used as it currently is -- to display the useful information that manual changes have been made.

**Comment by shorshe** [comment] 2015-11-03 09:52
Calibre... not my cup of tea at all. Tried it over and over... 

Sigil has very reliably helped me with over 2000 EPUBs in my publishing house [Münchner Verlagsgruppe GmbH](http://m-vg.de) up to date. Never had an issue I couldn't solve myself. This one tripped me up, though. 

I love the things Sigil does automatically otherwise I'd use Oxygen XML.

**Comment by eli-schwartz** [comment] 2015-11-03 15:11
Well then, that's the point, isn't it? This is one of the things Sigil does automatically. You can't pick and choose.

**Comment by shorshe** [comment] 2015-11-03 18:12
Did you even read what I was proposing?

**Comment by toddcarnes** [comment] 2015-11-03 18:30
It doesn't look like it.

**Comment by eli-schwartz** [comment] 2015-11-03 18:37
Yes, I did.

And it is clearly the opinion of the Sigil developers that Sigil should not indicate the book is in an unsaved state, when the only changes are the **automatic normalization changes** that Sigil performs when opening.
Like Word processors, Sigil expects a certain internal format layout and expects to have full control over that. But I've never heard anyone complain that modifying a Word document in a text editor looks different than modifying it in Word/LibreOffice.
As far as Sigil is concerned, filepaths are "Hands Off!" Reporting that "the file has been modified" when as far as Sigil is concerned, it hasn't been, is incorrect.

And if you want something that doesn't do that, maybe calibre's Editor would work better for you. 
It does a lot of the same bookkeeping for you, but it doesn't make assumptions about the folder layout.

Different tools to do much the same task in a slightly different way and all that...

**Comment by kevinhendricks** [comment] 2015-11-03 22:18
Please ...  this is not a debate forum.  This is for Sigil bug reporting.  The original poster created a bug report because he/she truly felt there was a bug.  After, some investigation, it became clear it was a misunderstanding about how Sigil works compared to text editors.  Then the op suggested something that might have prevented the confusion.    There was nothing wrong with his suggestion.  We simply disagreed about its need given how Sigil works and decided to close the issue.    

This is not the place for people who are NOT part of the development team to attack the request made by the op.  There was nothing wrong with his request, we simply disagree about its usefulness.
