### ISSUE TITLE
toc.xhtml file appears as internal summary

### ISSUE THREAD

**Issue by mariahmiah** [Sigil-Ebook/Sigil#365] opened 2018-06-18 19:42 UTC
the toc.xhtml file appears inside the workbook as if it were an internal summary page. I can not solve it. I am using the sigil version 0.9.9

**Comment by kevinhendricks** [comment] 2018-06-18 23:20
You need to explain exactly the issue you are having.  epubs can and often do include both a toc.ncx and an html basedtoc.xhtml file.  As far as I can tell, this is not a bug or an issue, and is instead simply asking for help on how to use Sigil.

If so, please use the Sigil User's Forum on www.mobileread.com for help on how to use Sigil.
I am closing this issue as it has insufficient information and is not a bug.

**Closed by kevinhendricks** 2018-06-18 23:20 UTC
