### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by runnerpack** [Sigil-Ebook/Sigil#607] opened 2021-04-03 18:47 UTC
I'm using 1.5.1 on Windows 7 and there's no setting to change the white background on the code editor to something non-retina-destroying.  I tried inserting ```code_view_background_color=@Variant(\0\0\0\x43\x1\xff\xff\0\0\0\0  \0\0)``` in sigil.ini and there's no change.
It would be nice if the Book Browser's bg color could be changed, too.
I guess all this stuff is automatic in Windows 10, but throw us Win 7 holdouts a bone, please? 🥺

**Comment by dougmassay** [comment] 2021-04-03 19:00
The bone was thrown long ago. ;)

You can either enable a dark theme in Windows 7 manually (a registry setting that is described in various places). That will enable dark mode for all of Windows 7. Sigil will honor it.

Or you can create an environment variable named SIGIL_USES_DARK_MODE and set it to "1" (actually, anything other than "0" will work).

Once Sigil's dark mode is enabled, you can choose in Sigil's preferences whether you want Preview to override the book's css to create light text on the dark background.

**Comment by kevinhendricks** [comment] 2021-04-03 19:13
Closing this a not a bug.  The feature works as documented in the User's Guide.

**Closed** 2021-04-03 19:14 UTC
