### ISSUE TITLE
Links to parent directories in links break HasUndefinedURLFragments

### ISSUE THREAD

**Issue by HenningJW** [Sigil-Ebook/Sigil#304] opened 2017-07-14 20:13 UTC
When trying to split a html HasUndefinedURLFragments gets triggered and throws me a warning and I have to choose weather to continue with spliting or not. The links work in Sigil and the Flighcheck plugin shows no errors in the file. The links look like this: `<a href="../Text/ch0-p3_split_000.xhtml#a9">`

If you need, I can send you the file in question.

**Comment by kevinhendricks** [comment] 2017-07-14 20:23
An undefined url fragment means that there is a link with a fragment (an anchor id or id on some other element) that does not exist.  This happens most often due to the use of case-sensitive names of file or path in the url or simply a missing id.  On systems with case insenstive file systems, the link appears to work but won't on case sensitive file systems.

The easiest way to diagnose this since your link example is being eaten by github since it uses html, is to post the zip archive of the html file someplace for me to grab.  If you do not want the world to see your link, you can simply pm KevinH on our mobileread users forum.

**Comment by mrprobert** [comment] 2017-07-14 20:27
Changing all instances of name= with id= may solve your problem.

**Comment by kevinhendricks** [comment] 2017-07-14 20:27
Thanks for fixing the link.

Please verify that the file the name  ch0-p3_split_000.xhtml exists and in that file you can find a tag with id="a9" in it that marks the destination.

**Comment by HenningJW** [comment] 2017-07-14 20:29
Sorry I went away (toilet) a few minutes after posting, the link is now fixed and you should receive a pm in few moments. Thanks for the fast reply. The case should be right inside the files.

**Comment by HenningJW** [comment] 2017-07-14 20:33
I see it now, the anchor doesn't exist, but as I had opened the file at the expected position, I did not spot that. I feel slightly stupid now. Should I file a bug in Flightcrew plugin or is that not something Flightcrew should mark as incorrect?

**Comment by kevinhendricks** [comment] 2017-07-14 20:38
Flightcrew will not verify links to fragments.  Official epubcheck might.  The split code can do some strange things if anchor ids are missing.  If you know where the a9 anchor should go, edit it in Sigil and add the missing id="a9" before trying to split the file further.

Closing this as not a bug

**Closed by kevinhendricks** 2017-07-14 20:38 UTC

**Comment by dougmassay** [comment] 2017-07-15 13:08
I'm a little late to this one, but I wanted to add that running Sigil Reports is an easy way quickly identify links that have missing targets, too.
