### ISSUE TITLE
Bug: figcaptions content ignored when copying text from the preview window

### ISSUE THREAD

**Issue by UnrulyNatives** [Sigil-Ebook/Sigil#644] opened 2021-10-03 00:01 UTC
I am quite sure the bug would need me to ask Sigil community for a plug-in, but still, please consider this scenario:

1) I receive a badly edited ePub and some chapters need to be extracted from XHTML for editing with Libre Office or other text processor. 

2) I do "select all: in the Sigil 1.7 preview window. (The figcaptions are marked as selected)

3) After pasting the `figcaption` texts are not present in the target document. 

4) Optimally, of course, the images should be copied too. 

If the above bugfix cannot be implemented for any reason (contrary to my understanding the current behaviour is a feature, not a bug), the button `select-all` in Preview pane should be renamed to `select all paragraph text`. Also, content which is not actually copied should not be highlighted.

Cheers.

**Comment by kevinhendricks** [comment] 2021-10-03 14:07
I can highlight any text in CodeView and copy it  to a clipboard.  So whatever you are doing is an artifact of what you are trying to paste it into.

Images are separate resources that do not exist inside CodeView, so they can not be copied from CodeView.  It almost sounds as if you are trying to highlight text in Preview somehow.  Preview is not an editing widget.

So this is not a Sigil bug. 

Try using "open with" and using a Browser as the application to copy from, or try using PageEdit.  

Closing as not a bug.

**Closed by kevinhendricks** 2021-10-03 14:07 UTC

**Comment by dougmassay** [comment] 2021-10-03 14:12
Just to note: I believe's talking about copying highlighted text from Preview, not Code View.

**Comment by dougmassay** [comment] 2021-10-03 14:16
Not all of the content that Preview's "Select All" action shows as being selected is being copied to the clipboard when copying. At least I _think_ that's what they're saying. I've not tested.

**Comment by kevinhendricks** [comment] 2021-10-03 15:42
I get that now.  I did not see the Preview part.  But that said, exactly what gets selected as text is completely determine by the QWebEnginePage which is part of Qt, not Sigil code we can control.

```
void PreviewWindow::SelectAllPreview()
{
    m_Preview->triggerPageAction(QWebEnginePage::SelectAll);
}

```

So assuming a "figcaption" is considered to be text and not part of the image, then any bug report needs to be made to Qt itself.

I do think the OP would be better using Sigil's OpenWith feature to open that xhtml file in a Browser window (Chrome, Safari, Firefox, Edge, etc) and try to use select all in the Browser to get around this limitation of Qt.

**Comment by dougmassay** [comment] 2021-10-03 15:47
I figured as much (a Qt function we can't control). I just wanted to make sure everyone was on the same page.

**Comment by kevinhendricks** [comment] 2021-10-03 15:51
But I just tested the "figcaption" is not being copied from Preview  report (I had an epub that makes heavy use of figcaption for maps).  I used Preview Select-All and pasted it into a text editor and the "figcaption" text was properly copied.

So whatever bug the OP is seeing, it is in either his clipboard or the program he is trying to paste into.  The figcaption  text itself is properly being copied under all of my testing.

So there is no bug in Qt or Sigil here.

**Comment by dougmassay** [comment] 2021-10-03 15:55
I'll check it out on Windows and Linux when I get a moment. I'm not certain I have anything with figcaption, though. May have to knock something together.

**Comment by kevinhendricks** [comment] 2021-10-03 16:41
Do you want me to email you an epub that uses figcaption for both images and maps for testing on Windows and Linux?

**Comment by dougmassay** [comment] 2021-10-03 16:54
Yes, please. That would be great!

**Comment by kevinhendricks** [comment] 2021-10-03 17:02
e-mailed.  Forgot the attachment but sent it immediately after.
Sorry about the large size.

**Comment by dougmassay** [comment] 2021-10-03 20:49
It seems to work fine in my testing, as well. The figcaption text is highlighted, copied to the clipboard, and pasted into a text editor on both Windows and Linux (Qt5.12.9 on Windows and Qt5.15.2 on Linux--both Sigil 1.7). I was also able to successfully paste the figcaption text in a Libre Office document on Linux and a Word document on Windows (using both the unformatted and formatted paste options in both programs).

One thing I will note, is that one can only use the keyboard-shortcut (Ctrl+c) on Windows and Linux to get the selected text from Preview's "Select All" button copied onto the clipboard. Sigil's "Copy" action on the Edit menu remains grayed out after the content is selected. Seems like a signal of some kind should enable the 'Copy' menu item, no? Or does that only react to Code View highlights/selections?

**Comment by kevinhendricks** [comment] 2021-10-03 21:06
That menu is for CodeView only as it is only enabled when something is selected in CodeView, not Preview.   To copy from Preview, you must use Preview's own Select-All button and Ctrl-C (or Apple-C on macOS).

**Comment by dougmassay** [comment] 2021-10-03 21:17
Then everything appears to be working as it should for me: figcaptions and all.
