### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by hehuahui2023** [Sigil-Ebook/Sigil#764] opened 2024-07-11 10:56 UTC
### Bug Description

关于Sigil 批量重命名的问题；
![f0ec19ef76c6a7ef34ac3019bbfaaf51f2de6601](https://github.com/Sigil-Ebook/Sigil/assets/129085905/2c9ed619-817f-4e2f-8f41-f3ae121bbf4c)
批量重命名，OPF文件不会同步修改。

### Platform (OS)

macOS

### OS Version / Specifics

Sonama 14.5

### What version of Sigil are you using?

Sigil 2.2.1 最新版本

### Any backtraces or crash reports

```shell
批量重命名Html文件，OPF的文件里面不会同步更改。
```

**Comment by dougmassay** [comment] 2024-07-11 11:12
Looks like another report complaining about idrefs not matching file
names?  I've not had much luck with getting a good translation.

If that's it, Sigil has no plans to make id/idref match the filename. It's
not required. It's only required that they be unique.

**Comment by kevinhendricks** [comment] 2024-07-11 12:47
Yes, not a bug.  Closing.

**Closed by kevinhendricks** 2024-07-11 12:47 UTC
Labels: bug

**Comment by kevinhendricks** [comment] 2024-07-18 17:28
The next release of Sigil will include a new epub tool:  Rebase OPF Manifest IDs on Current Filenames
You can use that new tool when released to address your concerns.
