### ISSUE TITLE
Stopping Sigil from adding style

### ISSUE THREAD

**Issue by tilmanj** [Sigil-Ebook/Sigil#306] opened 2017-07-16 12:10 UTC
Is there any way to prevent that sigil adds style to my text when I change tags etc.? I don't know even know why sigil adds style at all. It has been recommended to use classes instead of style since html4 (that is more than 15 years ago). This editor drives me into madness. It would be way nicer if one could add classes without the need to go into the editor.

**Comment by kevinhendricks** [comment] 2017-07-16 13:22
If you care about the exact code generated use CodeView and nit BookView.  BookView generates unline styles fir underlines, bold, etc.  According to the epub soec this is 100% allowed and correct for xhtml.

Closing as not a bug.  You should ask questions like this on our Mobileread User support forum.

**Closed by kevinhendricks** 2017-07-16 13:22 UTC
