### ISSUE TITLE
Crash after pasting in Book View

### ISSUE THREAD

**Issue by larrykollar** [Sigil-Ebook/Sigil#300] opened 2017-06-19 13:32 UTC
MacOSX 10.11.6, Sigil 0.9.8.

Steps to reproduce (I can make this happen pretty reliably):

1.  Open Sigil.
2.  Add an HTML text file to a blank book.
3.  Apply bold or italic to two separate strings.
4.  Select enough text to contain both the highlighted strings and copy.
5.  Paste *within* a paragraph (doesn't work if you paste at the *end* of a paragraph. Respond **No** to the "paste as plain text" dialog.
6.  Switch to Code View. CRASH.

I'm guessing it's not something that will bite people often, given the specific conditions required to trigger the crash, but it's certainly possible.

**Comment by kevinhendricks** [comment] 2017-06-19 14:05
Sorry,

I did exactly this on Mac OSX with stock Sigil 0.9.8 with OSX 10.12.5 (the machine I develop Sigil with) and have absolutely no crash or problems.  I tried it 3 times with 3 different substrings changed.

Sigil should never crash from something so simple.  Not sure why you are having this issue.  Does this crash happen every time?  How reproducible is it?

If you can reproduce it please save an testcase epub and provide ***exact*** instructions about exactly which text you make bold, which text you make italic, exactly which text to select and copy, and exactly where in the destination paragraph you want me to paste it.

As it stands, given just the information you have provided above, I can not get anything to crash and it seems to work just fine and does what I expected given the limitations of BookView editing and positioning.

**Comment by kevinhendricks** [comment] 2017-06-19 14:55
Hi,

If you can not get it to crash in a reproducible manner, please capture one of the OSX Crash Logs when prompted by OSX (and copy and paste it into a text document and post it here) so that we can at least give us a backtrace that might hint at what is actually causing the crash.

**Comment by kevinhendricks** [comment] 2017-07-01 00:42
Please provide the additional information necessary to recreate this bug.   On my Mac OSX machine, all seems to work just fine.  Otherwise, will close this bug report as "works for me".

**Closed** 2017-07-02 13:50 UTC
