### ISSUE TITLE
PVS-Studio: An unconditional 'break' within a loop.

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [Sigil-Ebook/Sigil#290] opened 2017-04-28 08:05 UTC
We have found a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

We suggests having a look at the emails, sent from @pvs-studio.com.

- V612 An unconditional 'break' within a loop. NavProcessor.cpp 185
**src/ResourceObjects/NavProcessor.cpp:**
```
QList<NavTOCEntry> NavProcessor::GetTOC()
{
  ....
  for (int j = 0; j < ol_nodes.length(); ++j) {
    GumboNode * olnode = ol_nodes.at(j);
    toclist.append(GetNodeTOC(gi, olnode, 1));
    break;
  }
  ....
}
```

- V612 An unconditional 'break' within a loop. ImportEPUB.cpp 496
**src/Importers/ImportEPUB.cpp:**

```
void ImportEPUB::LocateOPF()
{
  ....
  while (files.hasNext()) {
    OPFfile = QDir(m_ExtractedFolderPath).relativeFilePath(files.next());
    break;
  }
  ....
}
```

**Comment by kevinhendricks** [comment] 2017-04-28 14:22
Unless there is something insecure in some way from breaking a loop, in both cases we only want to process the first element of potentially a list.

So please explain the issue?

**Comment by SvyatoslavRazmyslov** [comment] 2017-04-28 14:33
@kevinhendricks 

> we only want to process the first element

This code doesn't make sense, use the "if" operator:
```
if (files.hasNext()) {
    OPFfile = QDir(....);
}
```

**Comment by kevinhendricks** [comment] 2017-04-28 14:50
I admit, it is not what I would have written but it is the now the remains of some larger block that functioned to test the contents of the (*.opf) file made sense.  As such is it not a bug.  I may not like it, and you may not like it but it functions perfectly well to find the first *.opf file if one exists.

**Comment by kevinhendricks** [comment] 2017-04-28 20:35
Closing this issue.  This is not a bug afaict.  This "error" should have been termed a "warning" as the code does seem strange at best.  If you disagree, please re-open this and explain why you still feel this is truly a bug.

**Closed by kevinhendricks** 2017-04-28 20:35 UTC
