### ISSUE TITLE
Find & Replace - direction selection

### ISSUE THREAD

**Issue by kpk-in** [Sigil-Ebook/Sigil#481] opened 2019-12-24 13:40 UTC
The direction to search in Find & Replace is selected through a dropdown (Up or Down).
Wouldn't it be convenient to use a radio button to select the Direction of Search?
(Another alternative is to have separate 'Search Up' and 'Search Down' buttons.)
![image](https://user-images.githubusercontent.com/5056431/71415294-ff5a5180-2680-11ea-93cf-0494ec6d0d76.png)
[enhancement] request

**Comment by kevinhendricks** [comment] 2019-12-24 13:43
Sorry, not going to be changed to to potentially tight realestate in the Find and Replace Widget.

Closing as not a bug and not a feature request we are going to implement

**Closed by kevinhendricks** 2019-12-24 13:43 UTC

**Comment by kpk-in** [comment] 2019-12-24 13:50
OK and thanks for the quick response. Hope you would keep in mind if there is any possibility of implementing.
