### ISSUE TITLE
Strange font issue with specific font.

### ISSUE THREAD

**Issue by ZacWolf** [Sigil-Ebook/Sigil#384] opened 2018-10-25 19:55 UTC
I'm using a google font:
**Mali**
I've loaded four styles: Regular, Bold, Italic, BoldItalic
When I preview the fonts via windows everything looks great. But when I add them to my epub via Sigel all of them are slanted. The Regular and Bold are actually MORE slanted than the Italic and BoldItalic.

When I go into preview mode, Resources tab, and select the fonts, I can see the slant. For example:

This is regular:
![image](https://user-images.githubusercontent.com/3706742/47526310-74f44300-d86d-11e8-8ace-72d73bf64d79.png)

This is italic:
![image](https://user-images.githubusercontent.com/3706742/47526368-8b020380-d86d-11e8-98a6-a8858d86ed2d.png)

It only happens with this font (I've tried others).

Attached is my epub (renamed as .zip for upload, just change back to .epub)
[Chances are, if you're reading this I probably hate you.zip](https://github.com/Sigil-Ebook/Sigil/files/2516500/Chances.are.if.you.re.reading.this.I.probably.hate.you.zip)
 for reference to see if you're seeing the same behavior.

Since it's specific to this font, I'm guessing there's something about this font file, but just incase it was a Sigil issue, I thought I'd document it, since it's just a weird one.

THANKS!

**Comment by BeckyDTP** [comment] 2018-10-25 20:12
I think that this is a issue similar to that described here:
https://www.mobileread.com/forums/showthread.php?t=300179

**Comment by ZacWolf** [comment] 2018-10-28 14:41
I can confirm that the issue is specific to Sigil, as once loaded on an ePub reader the fonts rendered correctly. THANKS!

**Comment by dougmassay** [comment] 2018-10-28 14:45
That's still doesn't mean it's "specific" to Sigil. It just means that the epub reader you tested it on uses a different rendering engine than Sigil. The problem could, in fact, manifest in any Windows situation where Qt is being used to render content.

**Comment by kevinhendricks** [comment] 2018-10-29 19:00
FWIW:  After dumping to xml both the Ubuntu Regular and Italic and the Mali Regular and Italic, I think the problem is in the OS_2 table in the panose definition which is used by Windows to match and choose appropriate fonts.  These OS_2 tables are only used by Windows and not Linux or Mac OS X.

The Mali-Regular and Mali-Italic have almost identical panose defintitions, specifically the bLetterform values, whereas the Ubuntu fonts differ in this value:

Mali-Regular
	<panose>
      <bFamilyType value="0"/>
      <bSerifStyle value="0"/>
      <bWeight value="5"/>
      <bProportion value="0"/>
      <bContrast value="0"/>
      <bStrokeVariation value="0"/>
      <bArmStyle value="0"/>
      <bLetterForm value="0"/>
      <bMidline value="0"/>
      <bXHeight value="0"/>
    </panose>

Mali-Italic
    <panose>
      <bFamilyType value="0"/>
      <bSerifStyle value="0"/>
      <bWeight value="5"/>
      <bProportion value="0"/>
      <bContrast value="0"/>
      <bStrokeVariation value="0"/>
      <bArmStyle value="0"/>
      <bLetterForm value="0"/>
      <bMidline value="0"/>
      <bXHeight value="0"/>
    </panose>


Ubuntu-Regular
<panose>
      <bFamilyType value="2"/>
      <bSerifStyle value="11"/>
      <bWeight value="5"/>
      <bProportion value="4"/>
      <bContrast value="3"/>
      <bStrokeVariation value="6"/>
      <bArmStyle value="2"/>
      <bLetterForm value="3"/>
      <bMidline value="2"/>
      <bXHeight value="4"/>
    </panose>

Ubuntu-Italic
<panose>
      <bFamilyType value="2"/>
      <bSerifStyle value="11"/>
      <bWeight value="5"/>
      <bProportion value="4"/>
      <bContrast value="3"/>
      <bStrokeVariation value="6"/>
      <bArmStyle value="2"/>
      <bLetterForm value="10"/>
      <bMidline value="2"/>
      <bXHeight value="4"/>
    </panose>
 
As far as I can tell the bLetterForm values are defined as follows:

Table 68 : bLetterform

Bit	Meaning
0	Any
1	No Fit
2	Normal/Contact
3	Normal/Weighted
4	Normal/Boxed
5	Normal/Flattened
6	Normal/Rounded
7	Normal/Off Center
8	Normal/Square
9	Oblique/Contact
10	Oblique/Weighted
11	Oblique/Boxed
12	Oblique/Flattened
13	Oblique/Rounded
14	Oblique/Off Center
15	Oblique/Square


So 
The Ubuntu Regular says it has bLetterForm value of 3 which is Normal/Weighted
The Ubuntu Italic says it has bLetterForm value of 10 which is Oblique/Weighted

The values for the Malic  Regular and Italic bLetterForm are identical and 0 which makes no sense to me and I think are confusing the Webkit font selection mechanism on Windows.  On Linux and Mac the entire OS_2 table and panose are basically ignored.

BTW:  I am no font expert so all of this is just a guess.  I could not see anything else that would indicate a problem to me.

So you may want to file a bug report with the Google font people and show them this to see what they say.

**Comment by dougmassay** [comment] 2018-10-29 19:10
Sounds probable. I know there's an OS/2 version property for fonts that can prevent them from working _at all_ (when embedded) in RMSDK-based engines when the value is too low.

**Comment by kevinhendricks** [comment] 2018-10-29 19:16
The python3 fonttools module comes with a command line program ttx that can dump a ttf file to an xml file.  It can then be edited to change those values and I think compiled back to a ttf file.  If that is done, it would b interesting to see if the trouble goes away completely on Windows.

**Comment by dougmassay** [comment] 2018-10-29 19:21
I can take a peek at it later. I've got Fontforge on a Windows machine which will let me modify most font properties.

**Comment by kevinhendricks** [comment] 2018-12-03 19:46
If you get a free moment and can confirm this as being a flaw in the panose font description of this specific font family under Qt/Webkit/Windows, then please close this issue.

Thanks

**Comment by dougmassay** [comment] 2018-12-03 19:49
Sorry. I checked this out a while ago and forgot about it. It's definitely an issue with that particular font. I tried to correct it by editing the font properties in Fontforge, but was unsuccessful.

Closing: as this is a bad font issue.

**Closed by dougmassay** 2018-12-03 19:49 UTC
