### ISSUE TITLE
can't open again after click"close"(x) icon on left-top / mac-osx-10.10.5/sigil-0.9.5

### ISSUE THREAD

**Issue by gituser9527** [Sigil-Ebook/Sigil#200] opened 2016-03-27 01:24 UTC
it occurs in mac-osx-10.10.5 today by these simple steps:
1. install sigil 0.9.5(download Sigil-0.9.5-Mac-Package.dmg, open the dmg, copy sigil.app to 'Applications' folder), and drag the icon to dock from launchpad;
2. "close" the software by clicking the "x" button on the left-top of SIGIL, there would be a "DOT" under the icon in DOCK, which shows that the software is "hiden" not "closed"?
3.  click the icon on the dock, it can not open and reappeared.
4. right-click on the icon and select, "quit', then clikc the icon to open, it is then able to oepn again.or, you can find a epub file and right click on it and select 'open with sigil' to open the sigil.
in one word, it can't open with a blank file after clicking "x" button.

**Comment by kevinhendricks** [comment] 2016-03-27 04:42
That is not a bug.  Closing the MainWindow does NOT exit the Sigil application, and Mac OSX does not allow the same app to be launched  twice.
If you go to the menubar you can actually exit the app or simply open a new window.  That is how it is designed and how Sigil always worked on Mac OSX. 
Closing this since not a bug.

**Closed by kevinhendricks** 2016-03-27 04:42 UTC

**Comment by gituser9527** [comment] 2016-03-27 04:46
but in the former versions of sigil and other softwares(e.g., firefox, itunes, and any other softs, after clicking "x", it still can re-appear the main windows, please notice this.

**Comment by gituser9527** [comment] 2016-03-27 05:13
i insist it's still a problem, big or small, which'd be solved.

**Comment by gituser9527** [comment] 2016-03-27 05:17
i know the window-frame is 'hiden' background to the memory, not 'closed'or'minimized', but even it's clicked'x' button, it should be still [re-opened by clicking the icon on DOCK or Launchpad.
but neither operation is available.

**Comment by gituser9527** [comment] 2016-03-27 05:23
i've using this soft for years, never thought the problem like this occurs^-^.
EVERY SOFTWARE CAN BE RE-OPENED by CLICKING the ICON on DOCK even if they are CLOSED!
Please check whether it's the problem with my computer or the soft(can you re-open any other soft by clicking the icon on the dock after clicking 'x'? what about the sigil 0.9.5.0?)
wish you a good day.
