### ISSUE TITLE
Language setting in a fresh installed Sigil is wrong

### ISSUE THREAD

**Issue by taikuli** [Sigil-Ebook/Sigil#145] opened 2015-10-25 20:35 UTC
In my environment (German Windows 7 or Windows 10) Sigil shows a German UI.
When I go to Edit / Settings / Language the selected language for UI and Metadata is "English".
If I click ok and restart, both are English.
The selected languages should reflect the language Sigil uses.

**Comment by kevinhendricks** [comment] 2015-10-26 02:22
Translation settings are determined from your locale at program launch.  The Sigil.ini defaults to English.  It is not set from your locale.

**Comment by kevinhendricks** [comment] 2015-10-26 02:42
So as far as I am concerned, this is expected behaviour.  You can and should be able to use those Preference setting to override your locale setting.   It was designed that way.

Closing this as not a bug.

**Closed by kevinhendricks** 2015-10-26 02:42 UTC
