### ISSUE TITLE
[Bug]: Sigil from repos problem with video card

### ISSUE THREAD

**Issue by colibris79** [Sigil-Ebook/Sigil#727] opened 2023-09-14 01:57 UTC
### Bug Description

Hi, I am using the repos Sigil version, 1.9.2 and it was working fine till I started getting this error

```
$ sigil
libGL error: DRI driver not from this Mesa build ('23.2.0-devel' vs '23.0.4-0ubuntu1~22.04.1')
libGL error: failed to load driver: radeonsi
libGL error: DRI driver not from this Mesa build ('23.2.0-devel' vs '23.0.4-0ubuntu1~22.04.1')
libGL error: failed to load driver: radeonsi
libGL error: DRI driver not from this Mesa build ('23.2.0-devel' vs '23.0.4-0ubuntu1~22.04.1')
libGL error: failed to load driver: swrast
Warning: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Warning: QGLXContext: Failed to create dummy context
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 

```

It has to be related with my video card (AMD Radeon) and the amdgpu-driver and all the drivers that come with it. In other 2 machines with Mint 21, Sigil works great as usual. I've tried updating de video card drivers to its last version but I still get the same message. 
Thought about installing flatpak's last version but it would install a lot of files from the org.kde.Platform   packages (700Mb). Similar case if I follow the manual installation steps.

I know this is not a problem directly related to Sigil but I would like to keep using the repos version in order not to mess up too much with my system. Is there any chance that you could direct me in any direction in order to solve this incompatibility between Sigil 1.9.2 and my video card?

Thanks

### Platform (OS)

Linux

### OS Version / Specifics

Mint 21

### What version of Sigil are you using?

1.9.2

**Comment by kevinhendricks** [comment] 2023-09-14 02:36
This is not a Sigil bug so I will remove the bug label.  The output means libGL being used is from a different ubuntu release than what Qt was compiled with.

No ideas how that happens.

You might try updating whatever ubuntu packages that provide libGL and Qt so they are properly synced.

Another possible solution is to build a fresh copy of Sigil from source on your machine.  If you ask for help in the Sigil forum on www.mobileread.com on the steps to do that, I am sure someone there will help you.

Closing this since not a bug.

**Closed by kevinhendricks** 2023-09-14 02:36 UTC
Labels: info

**Comment by colibris79** [comment] 2023-09-14 02:38
Thanks for the help @kevinhendricks , I'll give that a try
