### ISSUE TITLE
Unwanted space after paragraphs

### ISSUE THREAD

**Issue by spajdy** [Sigil-Ebook/Sigil#345] opened 2018-03-27 09:17 UTC
I've upgraded to 0.9.9 and it started ignoring not to correct code. In my language, we do not use spacing after paragraph, so it is bit annoying. It even destroys ePUB created from other sources that are good and only need to change a little bit. 

I think Sigil has potential to be a great program for creating and editing ePUBs, but please, get rid of this issue. I would be okay even if you put formatting option for paragraph spacing. It would be cool. 

You are cool! :) (I am not a programmer myself, but I adore everyone who puts effort into creating this program. Thank you very much.) 

Author.

**Comment by ferr1n** [comment] 2018-03-27 09:46
Hi spajdy! 

I'm not one of the developers of SIGIL but I'm following closely its development. I love this program. 

Sigil IS an amazing program to create-edit EPUBS! :)

I'm not sure if I've understood exactly what you mean, but if so the solution is to add some CSS rules to your book, basically on the P element. 

Something like that: 

```
p {
    margin-bottom: 0; 
    margin-top: 0;
    padding-bottom: 0;
    padding-top: 0;
}
```

An alternative is: 

p {
margin: 0;
padding: 0;
}

But in this case you won't have any margin or padding on the left-right. 

Hope this helps!

**Comment by dougmassay** [comment] 2018-03-27 10:08
Sigil has not changed in this regard. It has always left the styling of paragraphs up to the user.

As far as the other goes, Sigil should not be "destroying" compliant epubs. If you have an example of such you can share,  it would help us determine if Sigil is actually the problem.

**Comment by spajdy** [comment] 2018-03-27 10:52
@ferr1n if I am creating entire ePUB in Sigil that is alright because I know where did I put what - HTML / CSS. But I can do this only with my own code, not with the editor and for some reason, Sigil is putting my paragraphs into **div** tags, so it is obeying **p** attribute. So bit annoying. 

This is document I've created in Word and then Converted via Apple Pages. 
![convert from apple pages](https://user-images.githubusercontent.com/37831489/37962895-ef642c2a-31bc-11e8-9e4f-a2bb4c379f16.png)

I have just opened it in Sigil. 
![opened in sigil](https://user-images.githubusercontent.com/37831489/37962898-f3bbec2c-31bc-11e8-9030-0ffd42d7494d.png)

And then I have saved and opened it for reading. 
![saved in sigil and opened in app](https://user-images.githubusercontent.com/37831489/37962941-0e8d0fc2-31bd-11e8-907b-106bdaf0e1c8.png)


That is my problem. In CSS there is **p** attribute margin: 0 but Sigil started ignoring it. 

It would be cool if Sigil itself have in GUI buttons for deleting spacing after paragraphs and button for the first-line indent. 

I can manage this with short documents, but when there is like 300 pages it is a bit of annoying. 

@dougmassay I hope I showed you the issue. I would put it back, but Sigil creates for each paragraph div and ignores whole original CSS formatting.

**Comment by dougmassay** [comment] 2018-03-27 11:20
I can assure you that Sigil does not ignore valid css, nor does it randomly change p tags to div tags. Something must be happening pre-sigil that Sigil does not know how to handle. 

And no ... the screen shots aren't really helpful at all. I'd need an actual epub to inspect to be of any help. Using a browser to show how content is rendering is unacceptable as well. It could very-well be your epub browser reading add in that's at fault. We'd need to see the issue being reproduced in industry-standard epub reading software like ADE.

Apple Pages also tends to include a lot of pre-wrap css nonsense that fouls up paragraph spacing.

Before opening/editing the epub with Sigil, use an epub validator to ensure the epub has no errors. The fact that it renders as you'd like it to (in a browser) is no guarantee that your epub isn't already broken before Sigil goes to work on it.

**Comment by spajdy** [comment] 2018-03-27 11:49
@dougmassay Well, it is doing the same thing on every ePUB reader app I have. Apple iBooks, Google Books, Edge (yeah it can open ePUB on its own), Lithium. 
It actually shows perfectly with Pages conversion, only Sigil has some trouble with it. 

I would love to put both ePUBs here, but it is not supported the format. So I am adding ZIP file. 

[Anzelmov príbeh 2017 Sigil.zip](https://github.com/Sigil-Ebook/Sigil/files/1851784/Anzelmov.pribeh.2017.Sigil.zip)

Since I do not know much about programming it can happen there is some bullshit, but only trouble I have is after Sigil. And I did notice that when I create my own docs, it does this DIV thing too if I don't use HTML/CSS of my own. I can manage that, but I know a lot of people who can write and they do not know a thing about HTML/CSS.

**Comment by spajdy** [comment] 2018-03-27 11:59
@dougmassay I did as you said and I have put it to the validator. Various. Pages version returned without a single problem.

**Comment by dougmassay** [comment] 2018-03-27 12:44
> but I know a lot of people who can write and they do not know a thing about HTML/CSS.
Sigil is not the best ebook editing software for people who do not know a thing about htmls/css. A basic knowledge of such is assumed.

I will take a look at your epub, though. If it validates with no errors, then merely opening and saving with Sigil should not break things. We'll certainly fix it if we can.

**Comment by dougmassay** [comment] 2018-03-27 13:26
I'm not seeing any evidence of Sigil actually altering any code whatsoever. Certainly no divs are being added, and no css is being ignored. So if merely saving with Sigil is changing how it renders, then it must have something to do with the restructuring of the archive.

I DO know that if you want your epub to render the same on the widest variety of platforms/apps possible, you're definitely going to want to get rid of the 'style="white-space:pre-wrap; line-break:strict;"' bit of styling that's being applied to the divs that encapsulate the entire body content of your epub's xhtml files. That's the Pages nonsense I was talking about that adds all kinds of extraneous spacing in various rendering systems.

There _must_ be a setting in Pages to suppress it. That kind of css just doesn't make sense in a reflowable document. But I also don't understand why merely saving with Sigil would change how your EPub displays. I can't figure out what Sigil is altering when saving that makes the rendering change. I'll need to investigate more.

**Comment by spajdy** [comment] 2018-03-27 13:39
@dougmassay I am not sure what it is causing either. I think Apple made this with iBooks in mind (but I do now know how this actually works exactly - it's apple after all.) The best solution for me would be if Word could generate ePUBs itself - third party AddOns mess my language and there are missing characters after export. 

Well. I will be very thankful if you would happen the help me with this little issue. 

And there is the thing: is it possible to add to next version of Sigil buttons for "deleting" spacing after paragraph and button for creating first line indent? That would be lovely!

Thank you. 

Keep rock 'n' rolling :)

**Comment by dougmassay** [comment] 2018-03-27 13:43
Ahh ... I see now. It's the line endings. Pages output doesn't have any. All html pages are one long continuous line of code with no breaks. That's why the 'style="white-space:pre-wrap; line-break:strict;"' bit "works" when viewing it after immediately creating it with Pages; and that's why saving it with Sigil is changing how it renders: because Sigil adds reasonable line breaks to the html code.

Unfortunately, we won't be fixing this. Either find a way to suppress the 'style="white-space:pre-wrap; line-break:strict;"' bit in Pages, or remove it with Search & Replace after. We're not going to preserve monolithic one-line xhtml pages (which slows Sigil down terribly) just to make sure that css which never should have been added to a reflowable document in the first place displays properly. Sorry.

**Comment by dougmassay** [comment] 2018-03-27 13:46
> And there is the thing: is it possible to add to next version of Sigil buttons for "deleting" spacing after paragraph and button for creating first line indent? That would be lovely!

That's not likely to happen. As far as the spacing goes, there is no magic "why is there spacing here and how do I remove it" code. There are numerous ways that spacing between paras can be being applied; so there's no magic bullet for removing it.

**Closed** 2018-03-27 14:50 UTC

**Comment by Mazarin07** [comment] 2025-04-01 16:08
The main reason I hate Sigil is exactly this issue: adding an extra space after each paragraph. Or maybe that is done by the plugin that imports my docx. Anyway, I want to keep the formatting defined in MS Word, all these converters must not arbitrarily change my documents.

**Comment by dougmassay** [comment] 2025-04-01 16:25
Guess what I hate...

**Comment by kevinhendricks** [comment] 2025-04-01 16:36
As was explained earlier.  There is no Sigil bug.  The css generated by Pages is broken for reflowable epubs.  

Use Sigil to remove the following from the css:

'style="white-space:pre-wrap; line-break:strict;'

And then use css to set proper margins for p tags and div tags.

And adding comments to a long dead non-bug is clearly not a good thing either.  As our ReadMe clearly states, use our User Forum on Mobileread to get help.  Not for bumping non-bugs because you do not understand css and xhtml.
