### ISSUE TITLE
Trouble with the regex mode in Find/Replace

### ISSUE THREAD

**Issue by etienne-ch** [Sigil-Ebook/Sigil#291] opened 2017-05-05 15:54 UTC
Hi,

Regex mode ain't working for me as expected

For instance when I type : 
\1 something
in the Replace field, it will replace the searched string by : 
\1 something
instead of : 
searchedstring something

Is it a bug or have I missed something ?

I'm using what seems to be the latest available Sigil version on Ubuntu 14.04 which is version 0.8.6

Thx for the great app by the way.

**Comment by kevinhendricks** [comment] 2017-05-05 16:31
Did you check the box that says you are using regex in the Search dialog?

**Comment by kevinhendricks** [comment] 2017-05-05 16:35
Also, Sigil is now at 0.9.8 with lots of bug fixes and improvements.  It is buildable in Umbuntu and there is now an unofficial Linux binary that runs on many Linux systems available from one of Sigil's developers here:

https://www.mobileread.com/forums/showthread.php?t=284892

**Comment by dougmassay** [comment] 2017-05-05 21:15
The behavior you describe will also happen if you never actually _capture_ anything in your search expression. So if there is nothing being captured (in parentheses), the \1 will be treated as a literal string in your replace expression.

Every replace (\1, \2, \3) must have a corresponding capture in the search expression. In other words: if you only have two captures in your search expression, a \3 in your replace expression will be treated literally.

**Comment by etienne-ch** [comment] 2017-05-06 13:40
Thanks for your help 

Yes I've got the regex mode checked and I get some string captured before I try to replace it.
I think I'm gonna try to install that unofficial version, it's always better to have the latest build for sure.
I'll let you know how things are going when I'm done...
I have to add that I'm not using Ubuntu 14.04 precisely but Trisquel 7 which is a very similar system.

**Comment by kevinhendricks** [comment] 2017-05-06 14:18
It would help to see exactly what your regular expression and replace looks like as well as a copy and pasted snippet from CodeView showing a spot that you think the replacement should happen but doesn't (before the replace).

As Sigil uses PCRE for its regular expressions, please make sure the pcre library is installed as well on you Ubuntu variant.

**Comment by etienne-ch** [comment] 2017-05-06 14:29
Yes I've got libpcre3 and libpcre3-dev installed.
I don't have time for more by now, not before tuesday actually
see you

**Comment by etienne-ch** [comment] 2017-05-09 12:53
OK so here's an example : 

Code view : 
`<?xml version="1.0" encoding="utf-8"?>`
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"`
`"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">`

`<html xmlns="http://www.w3.org/1999/xhtml">`
`<head>`
`<title></title>`
`</head>`

`<body>`
`<p>juste une image</p>`

`<p><img alt="angry_bomb" src="../Images/angry_bomb.gif" /><br /></p>`
`</body>`
`</html>`

Find : 
`image`

Replace : 
`petite \1`

Result : 
`<?xml version="1.0" encoding="utf-8"?>`
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"`
  `"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">`

`<html xmlns="http://www.w3.org/1999/xhtml">`
`<head>`
`<title></title>`
`</head>`

`<body>`
`<p>juste une petite \1</p>`

`<p><img alt="angry_bomb" src="../Images/angry_bomb.gif" /><br /></p>`
`</body>`
`</html>`

**Comment by kevinhendricks** [comment] 2017-05-09 13:05
You have not used any capture groups in your regex.

After specifying regex mode in the pulldown, replace:

image

with

(image)

and then try your replacement.

Under regex the () indicate you want to capture this part of the regular expression to use later in replacements.  There are many good references to using regular expressions available on the web.  The best place to ask questions and get help is our user's forum here:

http://www.mobileread.com/forums/

Then look under Sigil.  There are many experienced regex users and ebook authors that are more than willing to help.

Closing as this is not a bug, it is standard use of regular expressions.

**Closed by kevinhendricks** 2017-05-09 13:05 UTC
