### ISSUE TITLE
[Bug]:  When going to save, if there's a html issue, it gives a warning about fixing or not fixing, but there should be a cancel option too.

### ISSUE THREAD

**Issue by phazei** [Sigil-Ebook/Sigil#739] opened 2024-02-18 04:24 UTC
### Bug Description

When saving, if there's a problem with the html in some file, it will ask if you want to auto fix it.  If you want to do it manually, it doesn't give you a chance before saving.  If you have a large ebook, this can make you wait up to a minute wasting time saving before you can go correct.  Instead of the choices of "yes" "no" there should be a "cancel" choice that aborts the save.  This is also a problem because one you save, you lose your undo history, so you can't see what the last edit you made was.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Win 11 Pro

### What version of Sigil are you using?

2.0.2

**Comment by kevinhendricks** [comment] 2024-02-18 13:39
There is no auto save.  You control when to save and abort the save.  Just make a checkpoint before trying to save (in general checkpoints are a really good idea  before and after any major changes,  Also if html file loading is taking a full minute or more, you should probably be splitting that file down into chapters.

**Comment by kevinhendricks** [comment] 2024-02-18 22:29
Closing as not a bug, since a simple work process change avoids any reload.

**Comment by phazei** [comment] 2024-02-19 01:44
I'm not talking about any autosave, I'm saying when I manually hit save, if there's an error, it asks if it should fix it or not, but there's no choice to cancel to let me manually fix it, I just have to wait for it to save. I'll look into checkpoints though.

The book is split in chapters, 1800 chapters, it's about 10mb.

**Comment by kevinhendricks** [comment] 2024-02-19 14:12
1800 Chapters!  Is this a fixed layout epub with each chapter a page?

**Comment by kevinhendricks** [comment] 2024-02-19 14:13
There is a "Sanity Check" that you can run before starting a save.  But I will look into adding a way to escape the save if mend on save is enabled.

**Comment by phazei** [comment] 2024-02-19 22:17
Each chapter is a single html file.  It's a compilation of a long running web novel series.  Each html file is about 10k, I think 7-8 pages per chapter I guess.

**Comment by kevinhendricks** [comment] 2024-02-22 15:18
Sigil will now allow you to Cancel the save if broken files exist and mend is offered.  This change has been pushed to Sigil master and will appear in the next release.

**Closed** 2024-02-22 15:18 UTC
Labels: bug
