### ISSUE TITLE
problem pasting a rich text

### ISSUE THREAD

**Issue by DoctorSubtilis** [Sigil-Ebook/Sigil#544] opened 2020-08-18 07:44 UTC
While when there was a _book view_ I was able to paste a rich text (with _paragraphs_, italic, bold and so on), now, in the new, only textual, view a text is pasted as text, without any formattation.  
This is a big problem for me.  
I guess you will answer that there is now the PageEdit (not yet tried), but its installation is not easy: why don't you provide an installation of PageEdit **with** Sigil (if the user wants), or at least a compiled release (deb or rpm, e.g.)?  
Thanks

**Comment by dougmassay** [comment] 2020-08-18 10:23
We don't provide Linux binary releases of Sigil, either. If your distro doesn't have PageEdit in its repos, complain to them that you want it to be provided. Many of the Arch-based distros have it (as well as PCLOS), but that's not us. We don't do Linux packaging.

Sigil and PageEdit are two separate programs. Their installations are not going to be combined.

Your distro's maintainers could always make PageEdit a recommended package whenever Sigil is installed. But again, that's on them. We're not Involved in packaging Sigil or PageEdit for Linux.

Closing this since it's not a bug.

**Comment by DoctorSubtilis** [comment] 2020-08-18 13:53
I see. And there is a way to downgrade sigil to a previous release?

**Comment by dougmassay** [comment] 2020-08-18 14:08
Again: if you installed Sigil through your distro's software management/package system, that's not us. We don't control that, nor do we participate in preparing Sigil for binary distribution for all of the various flavors of Linux. 

How to install/uninstall/downgrade binary repository software packages in general are questions for your particular Linux distro's help/support system.

**Closed** 2020-08-18 17:41 UTC
