### ISSUE TITLE
The software interface needs to be improved.

### ISSUE THREAD

**Issue by zl791450** [Sigil-Ebook/Sigil#413] opened 2019-04-24 02:00 UTC
<img width="1136" alt="2019-04-24 09 55 55" src="https://user-images.githubusercontent.com/16183227/56627292-c09a7480-6677-11e9-938b-20085e69603d.png">

**Comment by eli-schwartz** [comment] 2019-04-24 02:20
Needs to be improved how? And what is the connection between that and this screenshot you are posting?

**Comment by kevinhendricks** [comment] 2019-04-24 02:26
This is not a bug report.  It contains no information.  It tells us nothing.  I am closing this as not a bug report

**Closed by kevinhendricks** 2019-04-24 02:26 UTC

**Comment by BeckyDTP** [comment] 2019-04-24 08:01
This is similar to #399

**Comment by kevinhendricks** [comment] 2019-04-24 14:03
It may well be but who can tell.  This is not a bug report.  It has no platform info, no version info, no description of what they think is wrong, etc. That is why it is closed and will remain closed until some sort of actual information is provided.
