### ISSUE TITLE
[Bug]: Sigil 2.0.2 crashes when embedding fonts

### ISSUE THREAD

**Issue by Harvey-McArthur** [Sigil-Ebook/Sigil#733] opened 2023-10-31 21:34 UTC
### Bug Description

I use Sigil to embed fonts in EPUBs. When I updated to 2.0.2, Sigil crashed every time I tried to embed a font. I right-click on the Font folder, click on Add Existing Files, browse for the font files I need, select them, click Open, and after a second or two Sigil closes without doing anyithig with the fonts.

Harvey McArthur

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Windows 10

### What version of Sigil are you using?

2.0.2

**Comment by kevinhendricks** [comment] 2023-10-31 22:16
I can not recreate this at all. My guess is your font file has not been properly deobfuscated or is corrupted. 

Have you tried with a different set of fonts?  

Where did you get these fonts from?  If from another epub, they may have been either subsetted or obfuscated rendering them unfit for re-use.

**Comment by kevinhendricks** [comment] 2023-10-31 22:20
If you can provide a link to where we can download these exact fonts, we can test with them to see what the issue is?

**Comment by dougmassay** [comment] 2023-10-31 22:45
just added the first two ttf fonts I came across to an epub with 2.0.2 on Windows 10 with no problems.

**Comment by kevinhendricks** [comment] 2023-11-01 01:30
So we are going to need more information about the font files so that we can try to recreate this.

**Comment by dougmassay** [comment] 2023-11-01 01:38
We're definitely missing some piece of the puzzle. I've tried adding bunch of different font files using both epub2 and epub3, while having different resource types (html, css, opf, image) open in CV.

With nothing else to go on; eliminating third-party antivirus interference would be my first suggestion.

**Comment by kevinhendricks** [comment] 2023-11-01 22:59
@dougmassay,
Perhaps given neither of us can recreate this issue, we should close this issue until the asked for information on the fonts is provided?  Or we could leave it open and wait a bit longer.  It is your call.

**Comment by dougmassay** [comment] 2023-11-02 00:27
I'll wait a bit longer, but I agree. If there's no further info soon, I'll close the issue until more IS provided.

**Comment by dougmassay** [comment] 2023-11-02 23:48
Feel free to reopen this issue when, or if, any more info is provided to help us recreate the issue.

**Comment by Harvey-McArthur** [comment] 2023-11-06 23:49
Dear Doug,

My apologies, I have only just seen your emails about the font issue with Sigil. We are using  Atkinson Hyperlegible, and have been embedding it in our EPUB3 files using Sigil for two years with no problem. This is a set of fonts the Braille Institute has developed. Now every one of our volunteers who has upgraded to the new Sigil versions has had this problem.

Harvey McArthur
________________________________

**Comment by kevinhendricks** [comment] 2023-11-07 02:22
So this issue is tied to a specific font. 

 Is it freely available?  Can you provide a link where we can download the font?

Are you absolutely sure that font file has not been corrupted?

**Comment by dougmassay** [comment] 2023-11-07 02:30
You mention the upgrade to Sigil  v2.0.2 as when the problem began, but what version of Sigil was everyone upgrading _from_? 2.0.1? 2.0.0? 1.9.30?

**Comment by kevinhendricks** [comment] 2023-11-07 02:37
A Google search provided a link to those fonts and I downloaded them.  I was able to easily use Add Existing by right clicking on the Font folder and navigating and selecting those .otf files.  I was also able to double click on each of them in BookBrowser and see a sample of each of the fonts.  All with no issues at all.  But this was with macOS.

I will try withy Linux next just in case the issue happens there.

So whatever the issue is, it does not happen on macOS.

**Comment by kevinhendricks** [comment] 2023-11-07 02:46
Tried with Manjaro Linux and those fonts and all worked just fine.  So whatever the issue is, it seems to be specific to Windows unfortunately.

**Comment by kevinhendricks** [comment] 2023-11-07 03:04
What is funny is that you said it crashed after selecting them with Add Existing .. and hitting Open.  All that happens after that is the font files are copied to the default folder for Fonts.  No font data is actually loaded into memory and used at that point.

I can understand crashes that happen when the embedded font is actually used in a BookBrowser Tab or when the proper css is added and Prdview tries to load and use the font data.  It does not make much sense when just copying the file and setting up a Resource to point to it.

Very strange.

Are you sure you do not have third party antivirus software running that is causing the problem?

**Comment by dougmassay** [comment] 2023-11-07 03:07
No crashes importing them (from the link Kevin provided for Atkinson Hyperlegible)  on Windows 10 with Sigil v2.02. I tried the .otf, the .ttf, the .woff and .woff2 versions. Preview works for them all.

I'm right-clicking on the font folder and selecting Add Existing, as mentioned in the original report.

**Comment by dougmassay** [comment] 2023-11-07 03:11
Are they being added from a network drive/share by chance?

**Comment by kevinhendricks** [comment] 2023-11-07 16:46
I have now tested the google font versions and the jacobperez pro font versions with Sigil on macOS with no problems.

This sounds more and more like the problem is caused by:

- a specifc font file shared across multiple users that may have been corrupted
- a shared configuration of third party antivirus program that is interfering in some way
- a shared network drive (or cloud drive) with driver issues

@Harvey-McArthur 
We really need you to answer our remaining questions so we have some chance of tracking this one down.

Thanks

**Comment by kevinhendricks** [comment] 2023-11-08 19:04
Here we go again.  This is still an incomplete report of a "bug" that nether one of us can recreate.

So feel free to close this again anytime you want and we can reopen this if and when the bug reporter actually provides more information and sticks around long enough to actually answer our questions.

**Comment by kevinhendricks** [comment] 2023-11-11 13:34
Closing this as not a Sigil bug until the bug reporter actually sticks around long enough to answer questions to prove otherwise and help.

**Closed by kevinhendricks** 2023-11-11 13:34 UTC
Labels: info
