### ISSUE TITLE
[Bug]: Saved Searches only work once-

### ISSUE THREAD

**Issue by WS64** [Sigil-Ebook/Sigil#708] opened 2023-02-09 10:42 UTC
### Bug Description

I just updated from Sigil 1.4x to the latest version 1.9.20.
I have many Saved Searches, and they are all grouped.
I select one group (just clicking on the headline, not marking all the single members), and do a "replace all". It goes through all the memebers of the group and replaces everything, all fine so far.
But when I try to do the same again I only get the message "No searches selected". Some of my replaces have to be repeated, and now I have to close the Saved Searches, reopen them again and start all over. With 1.4 that was different, I could "replace all" as often as I wanted. Clicking on "restart" (the green circle) does not help either, with 1.9.20. I have not find a way yet to do a second search and replace.

### Platform (OS)

Windows (Default)

### OS Version / Specifics

Win 10

### What version of Sigil are you using?

1.9.20

**Comment by kevinhendricks** [comment] 2023-02-09 13:48
Saved searches were completelyredesigned.  Running Saved searches never remembered their progress and the next press would revisit any replacements that were skipped previously.  This actually prevented the entire set of searches being done properly and automatically as expected by Saved Search when searching groups.

Now when running a saved search group, each search is done once and not wrapped around to revisit something already skipped when the "replace or not" part of the search is done.

This change requires a pre built list of all search groups to be made and progress through the group to be properly remembered.  This list is built once a group is first selected.

To reselect a group you could easily click on any other search in the saved search box and go back to the one you want or just click the provided Load Search button.

Note there are new Saved Searches Controls columns that may be off the right of the Saved Search dialog and so growing that dialog horizontally may be needed.  There allow you to select specific search targets, and search flags to any member of a saved search group including new targets like text only, and all css files, etc.

These changes have been documented in the Saved Searches part of the updated Sigil User Guide.

**Comment by dougmassay** [comment] 2023-02-09 13:57
Even with all the new changes, I'm not experiencing the need to "close the Saved Searches, reopen them again and start all over." As Kevin mentioned, simply selecting another search and going back to the one you want will work.

A link to the latest Sigil User Guide can always be found at the top of the following page: https://sigil-ebook.com/sigil/guide/

**Comment by WS64** [comment] 2023-02-09 15:09
Ok, just tried, select another search, than the one I want again, this works. It is a drawback to the old behaviour, though. And if you don't feel the need to call it a bug, maybe explain the message "No searches selected". It is still the same search selected as the first time, when the search worked.

**Comment by kevinhendricks** [comment] 2023-02-09 15:51
Or as I said, hit the LoadSearch button in the SavedSearch dialog.

There are also two new Find Replace tools that can be used in place of manually skipping replacements.  See the new Users Guide for details:

1. Add a Dry Run Replace dialog to act as "Replace All" what if. (Shift + Count All)
 2. Add a Replacement filter dialog to allow users to delete unwanted replacements before applying Replace All (Shift + Replace All)

Closing this since it is expected behaviour and has been for a year or two.

**Closed by kevinhendricks** 2023-02-09 15:51 UTC
Labels: bug

**Comment by WS64** [comment] 2023-02-10 21:11
One last question, is 1.4.3 the latest version with the old behaviour? I will switch back, I need these repeatd serches way too often, I don't want to have to click on the "Load Search" button

**Comment by kevinhendricks** [comment] 2023-02-10 21:39
My guess is Sigil 1.7 or Sigil 1.8 was the last before the Find Replace redesin.

The funny thing is the redesign of Saved Searches was a feature requested by heavy Saved Search users because it allowed them to process the entire set of html files in one pass through a search group, skipping those replacements they did not want, all while allowing each group member to have its own search flags (controls) and set of target files.

Perhaps you should give that a try as the you should no longer need to constantly reload a Search Group as it will hit each search match only once allowing you to skip unwanted replacements as desired.

But do what you like.

**Comment by dougmassay** [comment] 2023-02-10 23:53
The control parameters were added to Saved Searches in v1.6, but I don't think the big overhaul happened until v1.9.0/1/2.
