### ISSUE TITLE
Adding existing files no longer replaces images

### ISSUE THREAD

**Issue by terabyte-gc** [Sigil-Ebook/Sigil#473] opened 2019-12-19 22:21 UTC
Adding an existing Text file used to replace the image links in it with a link to the local image included in the epub if one matching the name was present. This is not longer the case in 1.0.0.

For example let's say I have this HTML element in a xhtml file I am importing:
```
<p>Some text here</p>
<img src="https://sub.domain.tld/imageXYZ.jpg">
<p><em>Some other text here</em></p>
```

Until 0.9.18 the import function replaced `<img src="https://sub.domain.tld/imageXYZ.jpg">` with `<img src="../Images/imageXYZ.jpg"/>`. This is not longer the case in 1.0.0 though. Unless I've overlooked some new setting?

**Comment by dougmassay** [comment] 2019-12-19 23:25
It was never our intention that fully-qualified external images urls would be matched up with pre-existing images file of the same name upon adding existing xhtml files. The idea was that local images (or css files) that were properly linked to the external xhtml files would be also be brought along for the ride when adding the file to Sigil (which still works).

That what you describe ever worked is news to me, actually.

And did you mean to say "Until 0.9.8" or did you mean 0.9.18?

**Comment by kevinhendricks** [comment] 2019-12-19 23:31
Yes and now given alternate epub layoutsare allowed, file names may no longer be unique, only file bookpaths need be unique.  So just having a matching name is no longer enough to trigger replacement.

**Comment by terabyte-gc** [comment] 2019-12-19 23:57
@dougmassay Yes, sorry. I meant 0.9.18. Edited my post above.

**Comment by kevinhendricks** [comment] 2019-12-20 00:21
So this is not actually a bug.  A simple filename without path info is no longer enough information to determine if a file should be overwritten or not.   All valid local images referenced in the html page are imported.  So I am closing this as not a bug.

**Closed by kevinhendricks** 2019-12-20 00:21 UTC

**Comment by terabyte-gc** [comment] 2019-12-20 00:53
Guess I'll keep using 0.9.18 for now then. Based on my use of Sigil I won't need to update anytime  soon. Thanks for taking the time to look into this.

**Comment by dougmassay** [comment] 2019-12-20 01:17
Could you explain what sort of workflow your using, that something like this would even be handy? Perhaps there's alternatives we could come up with if I understood it. But I'm drawing a blank as to 1) why files with fully qualified image urls would need to be imported in the first place, and 2) why being able to repeatedly import said xhtml files into an epub with pre-populated matching image files would be at all useful.

It seems to me that the time spent ensuring that the properly named image files are already present in the epub would be better spent adjusting the external files' img src attributes to point to valid local images instead.

But to each their own. I don't know your process.

**Comment by terabyte-gc** [comment] 2019-12-20 02:58
I'm building some epubs for my own use for original novels I read off the internet. And every time a few new chapters are out I save the text/images locally in a folder. I then edit the current epub with Sigil and import both new images and text files.

Importing both images and text currently works (well, worked) only if the images come first in alphabetical order in the imported files list. For example, importing such list of files works right away and replaces the image links with the images imported in version 0.9.18:
```
image1.jpg
image2.jpg
image3.jpg
text1.xhtml
text2.xhtml
text3.xhtml
text4.xhtml
```

----

If the images come afterward though:
```
chapter1.xhtml
chapter2.xhtml
chapter3.xhtml
chapter4.xhtml
newimage1.jpg
newimage2.jpg
newimage3.jpg
```
With this kind of file list the image links are NOT replaced and I have to import first the JPG files and then the XHTML files.
