### ISSUE TITLE
Line break is automatically inserted when opening an ebook.

### ISSUE THREAD

**Issue by Wandmalfarbe** [Sigil-Ebook/Sigil#420] opened 2019-05-04 18:29 UTC
I have an EPUB with the following content:

```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="generator" content="pandoc" />
  <title>Column Test</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <link rel="stylesheet" type="text/css" href="../styles/stylesheet1.css" />
</head>
<body>
<div id="column-test" class="section level1 unnumbered">
<h1>Column Test</h1>
<div id="columns-50-50" class="section level2">
<h2>Columns 50 50</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>left column content</p>
</div><div class="column" style="width:50%;">
<p>right column content</p>
</div>
</div>
</div>
</div>
</body>
</html>
```

When opening the EPUB with Sigil, a line break is automatically inserted between the closing and opening `div` here `</div><div class="column" style="width:50%;">` [breaking the columns](https://codepen.io/anon/pen/bybmLP). The settings for automatic cleanups are disabled. 

I would like to open the EPUB without modification.

**Comment by kevinhendricks** [comment] 2019-05-04 20:19
Not a bug.  That is as designed.  Many of the poorly designed epub's out there are one giant run-on html files.  As CodeView is a line/block editor, it can not easily deal with them and therefore line breaks are are automatically inserted after block level tags.  Change your css to prevent the line break from impacting your layout, or choose to use another editor.

Sorry.

**Comment by kevinhendricks** [comment] 2019-05-04 21:22
This "feature" actually helps in 99% of the cases in the wild.  So if you can build from source and can live with an unresponsive editor from long run-on lines you can remove the insertion of new lines here:

Sigil/src/Misc/GumboInterface.cpp in the routine serialize_contents in lines 1068 through 1071, and the other places in the same routine which change things based on the inject_newline flag.

But in general using pre-wrap in any epub meant to reflow with readers that can have hugely different screen sizes is not a good idea.  A better idea is to properly use css code without the need for pre-wrap.

**Comment by kevinhendricks** [comment] 2019-05-04 21:22
Closing this as works designed.

**Closed by kevinhendricks** 2019-05-04 21:22 UTC

**Comment by Wandmalfarbe** [comment] 2019-05-04 22:32
Thank you for the quick response.
