### ISSUE TITLE
Program freeze because of warning window hidden at save time

### ISSUE THREAD

**Issue by fxpar** [Sigil-Ebook/Sigil#269] opened 2017-01-05 08:38 UTC
Hi,

**Issue:** 
when saving a file for the first time, the program is waiting for a warning window to be closed by user, but the window is hidden.

**File opened:**
Epub created by calibre editor by conversion of a docx file.
https://drive.google.com/open?id=0B4RzO1PGYCQiOFUtWVhEWWdkWjg

**Environment**
windows 10 with sigil portable 0.9.7 (via portable apps)

**WorkAround**
Have another instance of Sigil opened so that the warning window stays visible

![screen_20170105_081722](https://cloud.githubusercontent.com/assets/11584406/21673273/572bb250-d328-11e6-9dcb-94ff597976fb.png)
![screen_20170105_081705](https://cloud.githubusercontent.com/assets/11584406/21673272/572b98d8-d328-11e6-8bf3-b07def818175.png)

**Comment by fxpar** [comment] 2017-01-05 10:29
ISSUE SOLVED: Calibre doesn't include the version attribute in the epub package tag of metadata. This causes Sigil to believe it has to change package during the file saving.

**Comment by dougmassay** [comment] 2017-01-05 18:40
We don't create/support the Portable apps version of Sigil.

But what's more concerning to me, however, is the claim that "Calibre doesn't include the version attribute in the epub package tag of metadata". An Epub without a version attribute in the OPF package tag is simply not an Epub. It's not optional. If you run "Check book" from the calibre editor's tools menu, you'll see the lack of a version attribute is indeed recognized as a problem that's begging to be fixed. So saving the epub in that state is, in essence, saving an epub that Sigil **HAS** to fix  upon opening (it's not as tolerant of structural issues as calibre is).

In my experience, though, the pop-up you're referring to is never hidden behind the main window. It shows up front and center every time.

**Comment by dougmassay** [comment] 2017-01-05 18:46
Closing this, as I can't reproduce it. The situation that triggers the reported issue is, in fact, self-inflicted. And Sigil takes the invalid epub and make it valid (as it's supposed to).

**Closed by dougmassay** 2017-01-05 18:46 UTC

**Comment by fxpar** [comment] 2017-01-10 11:18
Hi Doug,

Thank you for looking it up. 

Indeed I had to put the version manually in Calibre editor. And no pb with Sigil anymore.

(Still, I don't understand why the warning window always disappeared... )

Regards
François
CLOSED.

**Comment by eli-schwartz** [comment] 2017-01-15 04:26
FWIW, calibre had a bug that opening a DOCX in the editor as a new book failed to set the version attribute, this is now fixed.
