### ISSUE TITLE
Double-click highlighting errors

### ISSUE THREAD

**Issue by mrprobert** [Sigil-Ebook/Sigil#598] opened 2021-03-19 07:55 UTC
Hi,

Double-clicking seems to sometimes produce inconsistent highlighting.

![tag1](https://user-images.githubusercontent.com/13193709/111745734-41ede800-884a-11eb-9798-ab68450c7ef3.jpg)

1. Shift double-clicking on the first `<p>` tag results in apparently extraneous highlighting on the adjacent `<a>` tag. 

![tag2](https://user-images.githubusercontent.com/13193709/111746463-5088cf00-884b-11eb-98ee-21c5ccc3e077.jpg)

2. Double-clicking on "three" should probably not be highlighting the enclosing tags. Adding punctuation changes this behavior (Double-click on "five".)

![tag3](https://user-images.githubusercontent.com/13193709/111747146-33a0cb80-884c-11eb-9e54-f11bbd95e9ca.jpg)

3. The highlighting produces by double-clicking between "e" and the period seems goofy as well.

Windows 10, Sigil-1.5.0  Beta

**Comment by kevinhendricks** [comment] 2021-03-19 13:42
1. That is not extraneous selection that is open close syntax highlighting . The only thing selected for editing is the p tag and its contents.  If you do not want open close tag syntax highlighting you can disable it in Preferences.  Any time a selection occurs in a tag or immediately before it, the open close syntax highlighting will be triggered.  That way by moving the cursor over a tag, you can see its matching closing tag even if nested.

2. Again you are confusing open close tag syntax highlighting with selection.  The only thing selected is the word three here.  If you do not like open close tag pair syntax highlighting you can disable it in Preferences.  The selection of three ends immediately before the closing p tag which is what triggers that.

3. In CV, Double clicking always tries to select the next word (it has always worked this way in all earlier Sigil releases) and your cursor is *after* the word.  It found the next "group" of characters.  So if you double-click where there is no next word, Qt tries to find something.  Again, this has long been true in CV and exactly what it selects depends on your Qt version.  So double clicking in or just before a word will highlight it.  Double-clicking after a word will try to find the next "word".


Thanks for you feedback and testing, but these are all expected behaviour given the newly open/close tag pair syntax highlighting, which you can turn off if you do not like.

**Closed by kevinhendricks** 2021-03-19 13:42 UTC

**Comment by mrprobert** [comment] 2021-03-19 14:15
Hi,

I like the new feature very much, I just thought it was a more binary
thing. I'll adjust to it. Thank you for the work you put into it.

  - Mark

**Comment by kevinhendricks** [comment] 2021-03-19 14:49
Yes the open close tag pair highlighting is triggered by both cursor (no selection just insertion point, and by a selection where the cursor is moved to be either at the start or the end of the selection.

Also since cursor insertion points are technically between characters, the convention is that the character "under the cursor" is considered to be the character to the immediate right of the insertion point.  When block cursors are used these characters would be flashing.

So for a cursor to be "in"  a tag it can be any of the following places (think of the "|" char as the cursor:

|<tag>   as the character under the cursor is the "<"
<|tag>   as the character under the cursor is the "t"
<t|ag>   as the character under the cursor is the "a"
<ta|g>   as the character under the cursor is the "g"
<tag|>   as the character under the cursor is the ">"

but not

<tag>|  as it is after the tag.

**Comment by kevinhendricks** [comment] 2021-03-19 16:10
After some thought, I think your case 1 and case 2 above can be prevented which will make for a less "busy" screen and help to lower confusion.   Every selection has an anchor position and a cursor position.  Typically the anchor comes first and the selection is from the anchor position to the cursor position.  But if you were to click and drag from right to left the anchor position would be on the right and the cursor position would be before it on the left.

With no selection the anchor position always equals the cursor position.

So to decide when to do open/close tag syntax highlighting, I could always just look at the minimum of the anchor position and the cursor position to determine the left side of the selection instead of where the right or left side edge happens to be depending on selection direction.

This will eliminate case 1 and case 2 as the selection anchor in both cases was on the left edge of the selection while the cursor was on the right edge of the selection making it in a tag (the first "<" was under the cursor position), which triggers the open/close syntax highlighting.

I will change this for the next release to always use the left edge of any selection to determine if open/close syntax highlighting should be enabled or not.  Without a selection this will always just use the cursor position.

There is just not much I can do about case 3 as that "select word under cursor" by double-clicking feature of Qt is not under our control and what happens when no "word" is under the cursor  really depends on Qt version.  According to the Qt docs, if there is no "word" under the cursor, it should just not highlight anything but ascii code that represents a tag appears to look like a "word" to some Qt versions as it is not entirely punctuation.
