### ISSUE TITLE
[Bug]: How to installation sigil for mac

### ISSUE THREAD

**Issue by ioudove** [Sigil-Ebook/Sigil#695] opened 2022-08-20 14:46 UTC
### Bug Description

Hello, I am a person who does not know anything about computers. When I run the code "codesign -dvvv Sigil.app" in the terminal, the result is "Sigil.app: No such file or directory"
I don't know what to do anymore. When I download Sigil.app-1.9.10-Mac.txz, should I extract it and drag the extracted file into the application on my mac as a first step?
Can you please answer my question? The more detailed explanation of the installation steps, the better. Thank you so much!

Translated with www.DeepL.com/Translator (free version)

### Platform (OS)

macOS

### OS Version / Specifics

12.5.1 (21G83)

### What version of Sigil are you using?

1.9.10

### Any backtraces or crash reports

```shell
Last login: Thu Aug 18 12:03:16 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
MacBook-Air:~ xiaolang$ codesign -dvvv Sigil.app
Sigil.app: No such file or directory
MacBook-Air:~ xiaolang$ dove
-bash: dove: command not found
MacBook-Air:~ xiaolang$ codesign -dvvv Sigil.app
Sigil.app: No such file or directory
MacBook-Air:~ xiaolang$
```

**Comment by kevinhendricks** [comment] 2022-08-20 18:14
This os not a bug report. bUser support happens on our Mobileread User forum as listed in our Readme.

**Comment by kevinhendricks** [comment] 2022-08-20 18:20
Are you building mac OS from source?  Apple verifies the code signing signature.
After downloading the .txz file move it out of Downloads onto your Desktop.
Then double-click it on newer macOS systems to unpack it. On older macOS systems you will need a free UnArchiver program.

All of this is documented on our website:
https://sigil-ebook.com/sigil/tips/#how-to-uncompress-tarxz-or-txz-files

Closing this since not a bug.  Join our Sigil forum in Mobileread to get more help.  There are lots of mac users in our forum that can help.

**Closed by kevinhendricks** 2022-08-20 18:20 UTC
Labels: invalid
