### ISSUE TITLE
Saved Search Character Encoding Issue When Loaded

### ISSUE THREAD

**Issue by valdearg** [Sigil-Ebook/Sigil#307] opened 2017-07-18 18:55 UTC
Hello All,

This is probably one of the most minor bug reports ever provided, but if you have a '>' in the name of a Saved Search entry, it displays correctly in the Saved Searches dialogue box, but when loaded it shows as``` &gt;```instead.

For example, the name is: Test 1 > Test 2. The > will show as ```&gt;``` instead.

Most likely some character encoding issue. Nothing even close to being serious but thought I might as well report it just in case this happens elsewhere.

Image attached to show.

![strokesplus_2017-07-18_19-55-04](https://user-images.githubusercontent.com/2789033/28334432-0c633cfc-6bf3-11e7-9527-64ce415bab10.png)

**Comment by kevinhendricks** [comment] 2017-07-19 02:29
It is not a character encoding issue.  The issue is the > symbol is one of the reserved characters in xml and xhtml.  It is always used to end an element.  To prevent that issue any non-xml non-xhtml element use of the > is replaced by its xml entity ```&gt;```

The search names are stored/saved in xml based setting files which are xml escaped.  The safest way to deal with this is to not use xml reserved characters to name a search.

**Comment by kevinhendricks** [comment] 2018-04-02 14:43
Closing as nothing further need be done.

**Closed by kevinhendricks** 2018-04-02 14:43 UTC
