### ISSUE TITLE
Sigil starts with default window size/position when it prompts something during startup

### ISSUE THREAD

**Issue by sh2sg** [Sigil-Ebook/Sigil#662] opened 2021-12-30 09:27 UTC
Sigil 1.8.0
macOS Big Sur 11.6.2

A sample prompt screenshot is attached.

As long as the prompt appears, regardless of "Yes" or "No" button clicked, Sigil will start with default window size and position.

![sample](https://user-images.githubusercontent.com/3245152/147738984-1b5f3fdf-b487-46df-ba09-b01fb9684ec4.jpg)

**Comment by kevinhendricks** [comment] 2021-12-30 13:03
Yes, it is not until first save and exit that Sigil will store its Window geometry in its Settings file.  That prompt indicates your files are most probably missing their Doctype.

**Comment by sh2sg** [comment] 2021-12-30 16:35
> Yes, it is not until first save or normal exit that Sigil will store its Window geometry in its Settings file. That prompt indicates your files are most probably missing their Doctype.
> 
> Saying Yes or No here only impacts running the Gumbo parser to mend missing items such as the DOCTYPE.

I meant, previous exit (with a good pub file) is fine, but as long as next opened epub has some issues, Sigil will ignore previous saved size/position.

**Comment by kevinhendricks** [comment] 2021-12-30 18:34
Yes, on macOS that is true as Qt has a bug when trying to restore the geometry of QDockWidgets tied to a QMainWindow.  That bug in Qt forces a workaround for sizing the first window shown .  I can disable that workaround but Qt's bug in restoring geometry of QDockWidgets just makes things worse.

So this is not something I can fix as the problem is a very longstanding bug in Qt that still hasn't been fixed in Qt 6.2.2.

Sorry ... closing this as it is out of Sigil's scope.

**Closed by kevinhendricks** 2021-12-30 18:34 UTC
