### ISSUE TITLE
Solution to annoying mac python /Applications overwrite

### ISSUE THREAD

**Issue by gwk** [Sigil-Ebook/Sigil#273] opened 2017-01-25 03:40 UTC
I just came across Building_A_Relocatable_Python_Framework_on_MacOSX.txt which looks very helpful - thank you for the clear writeup!

Incidentally, I came across a solution to the following noted problem today:

> Before building remember to rename any /Applications/Python 3.5.app to save it and replace it afterwards as the damn python installation from source always overwrites it no matter the configure prefix used

When running `configure`, pass `--enable-frameworks=somewhere/Library/Frameworks` where `somewhere` is non-empty, and the mac apps will get installed in `somewhere/Applications`.

The logic for this is at CPython's config.ac:306. Hope that helps!

**Comment by kevinhendricks** [comment] 2017-01-25 15:01
Thanks.  The problem is we are building a relocatable Python framework to be embedded into Sigil and not one to be installed in /System/Library/Frameworks or /Library/Frameworks or even to a local user's ~/Library/Frameworks/ and so the next case matches farther down in that switch and they hard code it to /Applications instead of prefix/Applications.

That is why we tell people to rename it to save any previous Python3.5.app in /Applications if the want to keep it.  It is safe no matter where they want to build their relocable Python framework.

Thanks for the tip.  Closing this issue.

**Closed by kevinhendricks** 2017-01-25 15:01 UTC

**Comment by gwk** [comment] 2017-01-25 15:26
Sorry if I wasn't clear. I mean that you can build in an arbitrary build directory, and as long as the framework dir ends with `*/Library/Frameworks` then you won't clobber `/Applications`.

Here is what I used:
```
prefix=$PWD/built
frameworkprefix=$prefix/Library/Frameworks
../configure --prefix=$prefix --enable-frameworks=$frameworkprefix
```

This matches line 306: `*/Library/Frameworks)` and thus the build is entirely contained. Nothing gets installed to system directories. 

In any case, thanks again for the writeup.

**Comment by kevinhendricks** [comment] 2017-01-25 15:55
I did understand and you were quite clear.

When you build for embedded you typically are installing into any local directory for eventual move to Sigil.app/Contents/Frameworks/  during the Sigil build process.  Notice that "Library" need not be in the path of where are building to.  Thus the bug that python will still ignore the prefix when setting its /Applications.  It does this because most people install into one of 3 locations:

/System/Library/Frameworks
/Library/Frameworks
~/Library/Framework

But building this relocatable Python 3.5 is meant for embedding and can be built with any location for "Frameworks" as it will be relocated to be inside a relocatable Sigil.app.

Hope this explains things of why I said, it would be safer in general to rename the Python3.5.2.app
