### ISSUE TITLE
Embedded Python Error running Sigil in Linux from a 1.3.0 build: Module Error: xmlprocessor repairXML

### ISSUE THREAD

**Issue by tkoop** [Sigil-Ebook/Sigil#539] opened 2020-07-29 19:17 UTC
I followed instructions on this page to build Sigil for Linux: 
https://github.com/Sigil-Ebook/Sigil/blob/master/docs/Building_on_Linux.md

I downloaded the 1.3.0 release and it built successfully, but when I ran the ./sigil command, I got a window saying "Embedded Python Error" Module Error: xmlprocessor repairXML

When I close that window, another one comes up saying "error in xmlprocessor repairXML:-2"  Module Error: xmlprocessor repairXML

I get both those two windows a few times, then everything goes away.  This is what the terminal says:

Debug: using qt5ct plugin
Debug: D-Bus global menu: no
Debug: palette support is disabled
setext parseropf error -2 traceback Module Error: opf_newparser parseopf
Segmentation fault (core dumped)

I don't know if this is a bug with Sigil, or if I'm just building it wrong.

**Comment by kevinhendricks** [comment] 2020-07-29 19:40
Did you use the Sigil-1.3.0 release tar.gz or pull from master itself?

**Comment by kevinhendricks** [comment] 2020-07-29 19:42
Use the official release tar ball and remember to follow the Linux build instructions and make sure you install the required python3 modules as directed in thebuild docs.

**Comment by kevinhendricks** [comment] 2020-07-29 19:46
Also have you installed it and run sigil via the script the sets up the env vars and things.

**Comment by dougmassay** [comment] 2020-07-29 19:51
You have actually tried installing Sigil, right? Trying to run Sigil from within the build folder MAY work in certain instances (depending on build options and system configuration), but it's not really supported. We only support running Sigil via the sigil bash script that gets installed to /usr/local/bin (if the default install prefix is used).after "make install" is run.

**Comment by eli-schwartz** [comment] 2020-07-29 19:54
I'm rather positive it won't work for the build tree, due to needing to find support files for the plugin runner and python routines, which are being looked at in `/usr`.

The build tree *might* contain sufficient RPATH entries to start the executable without library resolution issues, but that's only part of the story.

**Comment by dougmassay** [comment] 2020-07-29 19:55
Either that, or you don't have lxml installed (or it's installed in a version of Python that sigil wasn't built against).

**Comment by tkoop** [comment] 2020-07-29 21:38
OK, it was my fault.  I made two mistakes.

First, without thinking, I ran this command verbatim:
`cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/a/different/install/prefix -DCMAKE_BUILD_TYPE=Release ../sigil-src`
(Yes, it made a very nice executable in /a/different/install/prefix/bin)

Second, I thought I was done when I read "Common compilation failures/Errors".  I didn't run _sudo make install_ at all.

When I did it right, it all worked perfect.  Thank-you all very much for the good advice!

Some notes:
- _xdg-desktop-menu forceupdate_ ran without complaining, but Sigil didn't show up in the menu.  (I'm running Mint 20.)  I had to log out and log in, then the menu showed it.
- I had to run cmake again, explicitly setting the CMAKE_INSTALL_PREFIX to the default of /usr/local in order for it to work correctly `cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release ../sigil-src` 

And also, I want to say this: I posted this issue, and within _minutes_, three people replied!  That's awesome!  You guys rock!!!!

**Comment by eli-schwartz** [comment] 2020-07-29 21:59
> _xdg-desktop-menu forceupdate_ ran without complaining, but Sigil didn't show up in the menu. (I'm running Mint 20.) I had to log out and log in, then the menu showed it.

This is going to be due to your Desktop Environment, which may not be scanning for new items and regenerating menus.

Rerunning cmake with a proper prefix is probably not strictly needed, if you installed it with the first one, then executed `/a/different/install/prefix/bin/sigil` I'd expect it to detect the right paths. But then you don't get `sigil` to work as detected from `$PATH`, and the *.desktop menu file depends on this. (Also the menu entry would be installed to `/a/different/install/prefix/share/applications/` which doesn't get scanned *ever*.)

**Comment by kevinhendricks** [comment] 2020-07-31 12:21
Closing this as not a bug.

**Closed** 2020-07-31 12:23 UTC
