### ISSUE TITLE
Avoid anchor href tranform to absolute path 

### ISSUE THREAD

**Issue by wlkz** [Sigil-Ebook/Sigil#522] opened 2020-04-16 18:32 UTC
I make a anchor href in a xhtml file like this

```xhtml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
</head>

<body>
  <a href="#anchor">jump to anchor.</a>
  <p id="anchor">This is an anchor.</p>
</body>
</html>
```

But when I try to import ths xhtml to my epub project, `href="#anchor"` would  automatically tranform to absolute path like `href="../C%3A/Users/wlkz/test.xhtml#anchor"`, which will mess up the anchor link. Is it a feature? Is any workaround exist to avoid this transformation?

**Comment by kevinhendricks** [comment] 2020-04-16 19:28
What version of Sigil?

**Comment by kevinhendricks** [comment] 2020-04-16 19:29
Are you using "Add Existing..." to add the file?

**Comment by kevinhendricks** [comment] 2020-04-16 19:37
I can recreate this with Sigil from master.  It is definitely a bug. It appears to be a side-effect of a recent bug-fix to leave untouched invalid links (but this one was valid).

I will look into fixing it.  Right now, all you can do is use Find and Replace to fix these immediately after importing the html.

Sorry about that.

**Comment by kevinhendricks** [comment] 2020-04-16 20:09
Found the bug and it is now fixed in master.
This bug fix will be included in the next release of Sigil.

Thank you for your bug report!  It has helped improve Sigil.

**Comment by wlkz** [comment] 2020-04-17 16:56
Thank you for replying. I have tested some attribute url as below.

```html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
  <title></title>
  <script src="../Misc/script.js"></script>
  <style src="../Styles/style.css"></style>
  <style src="../Styles/style-not-exist.css"></style>
</head>

<body>
  <a href="#">test sharp mark href</a>
  <a href="Section0001.xhtml">test internal href</a>
  <a href="test-html-does-not-exist.xhtml">test-html-does-not-exist</a>
  <img src="../Images/image.jpg"/>
  <img src="../Images/img-does-not-exist.jpg"/>
  <audio src="../Audio/audio.mp3"></audio>
</body>

</html>
```

Result

```html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <script src="../../C%3A/Users/wlkz/Desktop/Misc/script.js"></script>
  <style src="../Styles/style.css"></style>
  <style src="../Styles/style-not-exist.css"></style>
</head>

<body>
  <a href="../../C%3A/Users/wlkz/Desktop/test/test.xhtml#">test anchor href</a>
  <a href="../../C%3A/Users/wlkz/Desktop/test/Section0001.xhtml">test internal href</a>
  <a href="../../C%3A/Users/wlkz/Desktop/test/test-html-does-not-exist.xhtml">test-html-does-not-exist</a>
  <img src="../Images/image.jpg"/>
  <img src="../Images/img-does-not-exist.jpg"/>
  <audio src="../Audio/audio.mp3"></audio>
</body>
</html>
```

It seems that some reachable links are transformed, but just `a` and `script` tags are affected.

**Comment by kevinhendricks** [comment] 2020-04-17 17:21
Interesting... 

External scripts will *not* be pulled in when importing html.  Only media and style links are currently looked for.

We could add that but even the epub3 spec does not *require* e-readers to support scripting.  Not sure how that should be handled.

Using the file name only in an href is an external link, not an internal link.  Will see what can be done about that.

Will fix it to properly handle to "#" to link to top of file.

**Comment by kevinhendricks** [comment] 2020-04-17 19:39
Okay completely reworked the ImportHTML link handling used by Add Existing ... and now your test case comes out like the following:

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title></title>
  <script src="../Misc/script.js"></script>
  <style src="../Styles/style.css"></style>
  <style src="../Styles/style-not-exist.css"></style>
</head>

<body>
  <a href="#">test sharp mark href</a>
  <a href="test.xhtml">test internal href</a>
  <a href="test-html-does-not-exist.xhtml">test-html-does-not-exist</a>
  <img src="../Images/image.jpg"/>
  <img src="../Images/img-does-not-exist.png"/>
  <audio src="../Audio/audio.mp3"></audio>
</body>
</html>
```

Please NOTE:  No links to non-existent files/resources will be modified.

Please NOTE: No javascripts will be imported along with the html.  Only style and media resources will be imported.  This is by design.  You can of course manually add existing javascript files after the fact. and Of course once, added, Sigil handles them properly.

Closing this a now fixed in master.  The fixes will appear in our next release.

**Closed** 2020-04-17 19:40 UTC

**Comment by wlkz** [comment] 2020-04-17 19:53
Yes, in my memory, most of Epub Readers do not support scripting except iBook. I found someone want to change some style dynamically using jQuery on iBook reader, it would be so crazy. Actually, adding script is not my intention. I found the url was changed when I tired to delete it.

So I wonder how sigil handle urls when importing html , and I make a test.  

Thank you for fixing the problem.
