### ISSUE TITLE
Space at line-end added in specific circumstances

### ISSUE THREAD

**Issue by jcsalomon** [Sigil-Ebook/Sigil#228] opened 2016-06-24 20:08 UTC
I’m pretty sure this was not an issue in Sigil 0.9.5.

The pretty-printer adds a space to the end of the line with an <img> tag, but only if it’s within a <div>, and only if there’s content following it:

```
<div>
  <img src="../Images/Voyager_1_-_view_of_Saturn%27s_moon_Mimas.jpg"/> 

  <p>foo</p>
</div>
```

The attached [JPG_Problem.epub](https://github.com/Sigil-Ebook/Sigil/files/332506/JPG_Problem.zip) illustrates this.

**Comment by kevinhendricks** [comment] 2016-06-24 21:28
The prettprint code was untouched since 0.9.5.  And exactly how is this a bug? The carriage return is interpreted as whitespace too and p starts a new paragraph.  How does this create an error in layout?

**Comment by kevinhendricks** [comment] 2016-06-24 21:33
What does it do for:
```
<div>
  <img src="blah"/>text with no whitespace after image tag.
</div>
```

If it introduces whitespace before the text, then that is a layout bug.

**Comment by jcsalomon** [comment] 2016-06-26 05:47
Not a layout bug, merely an annoyance when using source-code revision control—one more bit of HTML code changing for no apparent reason, making merges hard.

Your example,

    <div>
      <img src="blah"/>text with no whitespace after image tag.
    </div>

is left as-is; but

    <div>
      <img src="blah"/><p>foo</p>
    </div>

is first pretty-printed to

    <div>
      <img src="blah"/>

      <p>foo</p>
    </div>

and then to

    <div>
      <img src="blah"/> 

      <p>foo</p>
    </div>

with the extra space at the line end. I.e., pretty-print is not idempotent.

But no, it’s not a regression; testing back to 0.9.3 reveals the same (admittedly minor) issue.

**Comment by kevinhendricks** [comment] 2016-06-26 15:20
Given that pretty printings indents and adds blank  lines, it will introduce many many whitespace changes thus creating a problem for any revision system.  And rerunning prettyprint may change things again but should never introduce a layout issue.  And eventually it should stabilize and no further changes will be made.  If you rerun prettyprint again, it should not add additional spaces *after* the first one. 

So I really don't think this is a bug.    Please realize that pretty printing is not perfect and never can be as it can and will introduce bugs if you include css that changes a block level tag to inline and visa-versa.  But if someone is using that level they need to check each instance after using prettyprint.   This was true under the old tidy way of prettyprinting too.  That is why it is not the default anymore and why we made invoking it a conscious act. 

Typically prettyprinting was designed to be used as the first step to clean up only horribly formatted html code before detailed editing is done.  It should always be used with caution as it can never guarantee to understand exactly what the original author had exactly in mind so tries its best to never introduce layout bugs.

**Comment by kevinhendricks** [comment] 2018-08-12 23:46
Closing this issue as not a bug.

**Closed by kevinhendricks** 2018-08-12 23:46 UTC
