### ISSUE TITLE
no TOC in epub files

### ISSUE THREAD

**Issue by DoctorSubtilis** [Sigil-Ebook/Sigil#338] opened 2018-03-02 08:30 UTC
It's a news: no TOC (TOC.ncx with only "start" entry)!
Release 0.9.9 
QT 5.9.1
Build time 2018.01.14
SO Kubuntu 17.10

**Comment by kevinhendricks** [comment] 2018-03-02 13:16
Closing as this is NOT a bug report.  There is no information on the error.  No information on how to reproduce the problem if one even exists.  No test case.

**Closed by kevinhendricks** 2018-03-02 13:16 UTC

**Comment by DoctorSubtilis** [comment] 2018-03-02 14:32
What I should tell?
This bug is reproducible _always_ on my Sigil release 0.9.9, QT 5.9.1, Build time 2018.01.14, Kubuntu 17.10. 
Info: when I do "Generate table of contents" (From menu tools -> Table of contents) all seems OK, but in effect there is _no modification of the file toc.ncx_ in root folder of epub file, even I see at right panel all the titles of the TOC. 
In effect with e-book reader that epub is _without_ table of contents.
This information is not enough? Tell me, please what else I have to tell.
Thank you

**Comment by dougmassay** [comment] 2018-03-02 14:49
Then you are working with an epub3. The NCX is optional in epub3. When editing epub3s, Generate ToC (and other toc editing features) updates the epub3-mandatory NAV document. NOT the NCX. If you want to keep a backward-compatible NCX in your epub3, then you need to use Tools->Epub3 Tools->Generate NCX from Nav.I

To repeat:

With EPUB2: Tools->Table of Contents->Generate Table of Contents updates the NCX
With EPUB3: Tools->Table of Contents->Generate Table of Contents updates the NAV

This is not a bug, it is by design.

**Comment by DoctorSubtilis** [comment] 2018-03-02 14:50
Thank you!
