### ISSUE TITLE
[Bug]: Segfault after opened Epub file

### ISSUE THREAD

**Issue by l0ddej0kk0** [Sigil-Ebook/Sigil#770] opened 2024-09-01 11:42 UTC
### Bug Description

A few seconds after opening and weirdly displaying KE3.epub,
[KE3.epub.zip](https://github.com/user-attachments/files/16828742/KE3.epub.zip) (just rename KE3.epub.zip to KE3.epub, as this was already zip-ed), 
 Segmentation fault (core dumped)
occurs.
Other .epub's work just fine.

Sigil 2.3.0 is newly built today, build-sigil.sh also attached.
[build_sigil.sh.zip](https://github.com/user-attachments/files/16828747/build_sigil.sh.zip)

Found the 14MB coredump, tell me if /how you want it.

### Platform (OS)

Linux

### OS Version / Specifics

LinuxMint 22 Virginia (Ubuntu 24 Noble)

### What version of Sigil are you using?

2.3.0

### Any backtraces or crash reports

```shell
2024-09-01T13:18:02.897896+02:00 lapframe kernel: traps: sigil[30550] general protection fault ip:717b625eee32 sp:7ffcb6d6f770 error:0 in libQt6Core.so.6.4.2[717b624a6000+2e8000]
2024-09-01T13:18:05.770230+02:00 lapframe systemd-coredump[30664]: Process 30550 (sigil) of user 1000 dumped core.#012#012Module libudev.so.1 from deb systemd-255.4-1ubuntu8.4.amd64#012Module libsystemd.so.0 from deb systemd-255.4-1ubuntu8.4.amd64#012Module libzstd.so.1 from deb libzstd-1.5.5+dfsg2-2build1.1.amd64#012Stack trace of thread 30550:#012#0  0x0000717b625eee32 _ZN7QStringaSERKS_ (libQt6Core.so.6 + 0x1eee32)#012#1  0x0000619229afe7cf _ZN10MainWindow24ShowLastOpenFileWarningsEv (sigil + 0x5287cf)#012#2  0x0000717b62576683 _ZN7QObject5eventEP6QEvent (libQt6Core.so.6 + 0x176683)#012#3  0x0000717b6338b3b0 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt6Widgets.so.6 + 0x18b3b0)#012#4  0x0000717b62538448 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt6Core.so.6 + 0x138448)#012#5  0x0000717b62538635 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt6Core.so.6 + 0x138635)#012#6  0x0000717b62733a8f n/a (libQt6Core.so.6 + 0x333a8f)#012#7  0x0000717b5fcf55b5 n/a (libglib-2.0.so.0 + 0x5d5b5)#012#8  0x0000717b5fd54717 n/a (libglib-2.0.so.0 + 0xbc717)#012#9  0x0000717b5fcf4a53 g_main_context_iteration (libglib-2.0.so.0 + 0x5ca53)#012#10 0x0000717b627315ef _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x3315ef)#012#11 0x0000717b625429a3 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1429a3)#012#12 0x0000717b6253b35e _ZN16QCoreApplication4execEv (libQt6Core.so.6 + 0x13b35e)#012#13 0x00006192296cd782 main (sigil + 0xf7782)#012#14 0x0000717b61c2a1ca __libc_start_call_main (libc.so.6 + 0x2a1ca)#012#15 0x0000717b61c2a28b __libc_start_main_impl (libc.so.6 + 0x2a28b)#012#16 0x00006192296e6ff5 _start (sigil + 0x110ff5)#012#012Stack trace of thread 30551:#012#0  0x0000717b61d1b4cd __GI___poll (libc.so.6 + 0x11b4cd)#012#1  0x0000717b613e38ca n/a (libxcb.so.1 + 0xc8ca)#012#2  0x0000717b613e528c xcb_wait_for_event (libxcb.so.1 + 0xe28c)#012#3  0x0000717b5c2d27c0 n/a (libQt6XcbQpa.so.6 + 0x557c0)#012#4  0x0000717b6267c48d n/a (libQt6Core.so.6 + 0x27c48d)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30559:#012#0  0x0000717b61c98d61 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d61)#012#1  0x0000717b61c9b7dd __pthread_cond_wait_common (libc.so.6 + 0x9b7dd)#012#2  0x0000717b51f1d7ad n/a (radeonsi_dri.so + 0x11d7ad)#012#3  0x0000717b51efca8b n/a (radeonsi_dri.so + 0xfca8b)#012#4  0x0000717b51f1d6dc n/a (radeonsi_dri.so + 0x11d6dc)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30563:#012#0  0x0000717b61c98d61 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d61)#012#1  0x0000717b61c9b7dd __pthread_cond_wait_common (libc.so.6 + 0x9b7dd)#012#2  0x0000717b51f1d7ad n/a (radeonsi_dri.so + 0x11d7ad)#012#3  0x0000717b51efca8b n/a (radeonsi_dri.so + 0xfca8b)#012#4  0x0000717b51f1d6dc n/a (radeonsi_dri.so + 0x11d6dc)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30564:#012#0  0x0000717b61c98d61 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d61)#012#1  0x0000717b61c9bc7e __pthread_cond_wait_common (libc.so.6 + 0x9bc7e)#012#2  0x0000717b62676b93 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x276b93)#012#3  0x0000717b6267cad2 n/a (libQt6Core.so.6 + 0x27cad2)#012#4  0x0000717b6267c48d n/a (libQt6Core.so.6 + 0x27c48d)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30553:#012#0  0x0000717b61d1b4cd __GI___poll (libc.so.6 + 0x11b4cd)#012#1  0x0000717b5fd5466e n/a (libglib-2.0.so.0 + 0xbc66e)#012#2  0x0000717b5fcf4a53 g_main_context_iteration (libglib-2.0.so.0 + 0x5ca53)#012#3  0x0000717b5fcf4aa9 n/a (libglib-2.0.so.0 + 0x5caa9)#012#4  0x0000717b5fd23c82 n/a (libglib-2.0.so.0 + 0x8bc82)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30558:#012#0  0x0000717b61c98d61 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d61)#012#1  0x0000717b61c9b7dd __pthread_cond_wait_common (libc.so.6 + 0x9b7dd)#012#2  0x0000717b51f1d7ad n/a (radeonsi_dri.so + 0x11d7ad)#012#3  0x0000717b51efca8b n/a (radeonsi_dri.so + 0xfca8b)#012#4  0x0000717b51f1d6dc n/a (radeonsi_dri.so + 0x11d6dc)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30561:#012#0  0x0000717b61c98d61 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d61)#012#1  0x0000717b61c9b7dd __pthread_cond_wait_common (libc.so.6 + 0x9b7dd)#012#2  0x0000717b51f1d7ad n/a (radeonsi_dri.so + 0x11d7ad)#012#3  0x0000717b51efca8b n/a (radeonsi_dri.so + 0xfca8b)#012#4  0x0000717b51f1d6dc n/a (radeonsi_dri.so + 0x11d6dc)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30567:#012#0  0x0000717b61c98d61 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d61)#012#1  0x0000717b61c9bc7e __pthread_cond_wait_common (libc.so.6 + 0x9bc7e)#012#2  0x0000717b62676b93 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x276b93)#012#3  0x0000717b6267cad2 n/a (libQt6Core.so.6 + 0x27cad2)#012#4  0x0000717b6267c48d n/a (libQt6Core.so.6 + 0x27c48d)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30560:#012#0  0x0000717b61c98d61 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d61)#012#1  0x0000717b61c9b7dd __pthread_cond_wait_common (libc.so.6 + 0x9b7dd)#012#2  0x0000717b51f1d7ad n/a (radeonsi_dri.so + 0x11d7ad)#012#3  0x0000717b51efca8b n/a (radeonsi_dri.so + 0xfca8b)#012#4  0x0000717b51f1d6dc n/a (radeonsi_dri.so + 0x11d6dc)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30552:#012#0  0x0000717b61d2725d syscall (libc.so.6 + 0x12725d)#012#1  0x0000717b5fd4e40d g_cond_wait (libglib-2.0.so.0 + 0xb640d)#012#2  0x0000717b5fcbf52b n/a (libglib-2.0.so.0 + 0x2752b)#012#3  0x0000717b5fd27043 n/a (libglib-2.0.so.0 + 0x8f043)#012#4  0x0000717b5fd23c82 n/a (libglib-2.0.so.0 + 0x8bc82)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30554:#012#0  0x0000717b61d1b4cd __GI___poll (libc.so.6 + 0x11b4cd)#012#1  0x0000717b5fd5466e n/a (libglib-2.0.so.0 + 0xbc66e)#012#2  0x0000717b5fcf5f77 g_main_loop_run (libglib-2.0.so.0 + 0x5df77)#012#3  0x0000717b5d378422 n/a (libgio-2.0.so.0 + 0x11a422)#012#4  0x0000717b5fd23c82 n/a (libglib-2.0.so.0 + 0x8bc82)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30557:#012#0  0x0000717b61c98d61 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d61)#012#1  0x0000717b61c9b7dd __pthread_cond_wait_common (libc.so.6 + 0x9b7dd)#012#2  0x0000717b51f1d7ad n/a (radeonsi_dri.so + 0x11d7ad)#012#3  0x0000717b51efca8b n/a (radeonsi_dri.so + 0xfca8b)#012#4  0x0000717b51f1d6dc n/a (radeonsi_dri.so + 0x11d6dc)#012#5  0x0000717b61c9ca94 start_thread (libc.so.6 + 0x9ca94)#012#6  0x0000717b61d29c3c __clone3 (libc.so.6 + 0x129c3c)#012#012Stack trace of thread 30582:#012#0  0x0000717b61c98d61 __futex_abstimed_wait_common64 (libc.so.6 + 0x98d61)#012#1  0x0000717b61c9bc7e __pthread_cond_wait_common (libc.so.6 + 0x9bc7e)#012#2  0x0000717b67c63a34 n/a (libQt6WebEngineCore.so.6 + 0x4263a34)#012#3  0x0000717b67c6450a n/a (libQt6WebEngineCore.so.6 + 0x426450a)#012#4  0x0000717b67c35335 n/a (libQt6WebEngineCore.so.6 + 0x4235335)#012#5  0x0000717b67c3f41b n/a (libQt6WebEngineCore.so.6 + 0x423f41b)#012#6  0x0000717b67c3fa01 n/a (libQt6WebEngine
# probably cut off
```

**Comment by l0ddej0kk0** [comment] 2024-09-01 11:46
![sigil_weird](https://github.com/user-attachments/assets/df52b160-f9b8-48e5-a04a-50c0f1a639d2)

Sigil window after opening KE3.epub

**Comment by l0ddej0kk0** [comment] 2024-09-01 11:48
Please just rename KE3.epub.zip to KE3.epub, as this was already zip-ed. I'm sorry.

**Comment by dougmassay** [comment] 2024-09-01 12:45
Can confirm ke3.epub crashes Sigil on Arch Linux with Qt6.7.2. I've not delved into it at all, but the epub is a flat structure (which always worked with Sigil in the past ). Perhaps it's an artifact of our Qt6-only restructuring? Will have more time later to investigate.

**Comment by dougmassay** [comment] 2024-09-01 12:46
I don't see any visual  weirdness when the epub opens, however.

**Comment by kevinhendricks** [comment] 2024-09-01 12:50
The error seems to come in:

MainWindow.cpp - ShowLastOpenFileWarning

which means your epub's xhtml file is probably missing its DOCTYPE.

There was a recent fix in that routine that prevents re-entry that was pushed to master.

If your build was built from official Sigil-2.3.0 sources, please try a new build but from Sigil master today and test if your crash still happens.

**Comment by dougmassay** [comment] 2024-09-01 12:57
Is URI a valid opf indentifier scheme?

`<dc:identifier id="BookId" opf:scheme="URI">G1o8wG284</dc:identifier>`

**Comment by kevinhendricks** [comment] 2024-09-01 13:02
That epub has 2 problems:

1. It is an epub2 but has not NCX, Sigil has to create one
2. It is missing DOCTYPE on its xhtml files.

After opening, you should be seeing these two error messages:
<img width="466" alt="Screenshot 2024-09-01 at 9 00 02 AM" src="https://github.com/user-attachments/assets/8d5e8305-bfa8-432e-ba75-28633dc0c396">
<img width="466" alt="Screenshot 2024-09-01 at 9 00 02 AM" src="https://github.com/user-attachments/assets/28e847ae-400e-4848-8011-ee3b86fec2fa">

**Comment by kevinhendricks** [comment] 2024-09-01 13:05
I do not think a URI scheme is allowed there but backtrace is showing the issues in in the warning dialogs that pop up after initial opening.

This all works on macOS.

I will test it on my Manjaro VM

**Comment by kevinhendricks** [comment] 2024-09-01 13:28
I can confirm the segfault happens even with the updated code in Sigil master on my Qt 6.7.2 Manjaro box.

I should be able to get a good backtrace.  

My *complete guess* is the problem is that some of the warning messages are being generated in a different thread than the main GUI one.

This one might be tricky to fix given ImportEPUB is multithreaded on purspose for loading speed.

**Comment by kevinhendricks** [comment] 2024-09-01 13:31
Here is the complete backtrace.  The problem is happening in QString assignment inside the ShowLastLoadWarnings routine in MainWindow.cpp.
```
Thread 1 "sigil" received signal SIGSEGV, Segmentation fault.
0x00007fffeb00e522 in QString::operator=(QString const&) () from /usr/lib/libQt6Core.so.6
(gdb) bt
#0  0x00007fffeb00e522 in QString::operator=(QString const&) () from /usr/lib/libQt6Core.so.6
#1  0x0000555555ae6a47 in MainWindow::ShowLastOpenFileWarnings() ()
#2  0x0000555555b00f48 in MainWindow::LoadFile(QString const&, bool) ()
#3  0x0000555555b0340c in MainWindow::Open() ()
#4  0x00007fffeaf9e94a in ?? () from /usr/lib/libQt6Core.so.6
#5  0x00007fffeb91a264 in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt6Gui.so.6
#6  0x00007fffebf1e4f9 in ?? () from /usr/lib/libQt6Widgets.so.6
#7  0x00007fffebf203f3 in ?? () from /usr/lib/libQt6Widgets.so.6
#8  0x00007fffebd9c15e in QWidget::event(QEvent*) () from /usr/lib/libQt6Widgets.so.6
#9  0x00007fffebd4c51c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#10 0x00007fffebd519c1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#11 0x00007fffeaf41d28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#12 0x00007fffebd43e2d in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt6Widgets.so.6
#13 0x00007fffebdb2530 in ?? () from /usr/lib/libQt6Widgets.so.6
#14 0x00007fffebdb35f0 in ?? () from /usr/lib/libQt6Widgets.so.6
#15 0x00007fffebd4c51c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt6Widgets.so.6
#16 0x00007fffeaf41d28 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt6Core.so.6
#17 0x00007fffeb575df0 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /usr/lib/libQt6Gui.so.6
#18 0x00007fffeb5e4d64 in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt6Gui.so.6
#19 0x00007fffd69f5637 in ?? () from /usr/lib/qt6/plugins/platforms/../../../libQt6XcbQpa.so.6
#20 0x00007fffe9f9aab9 in ?? () from /usr/lib/libglib-2.0.so.0
#21 0x00007fffe9ffc9e7 in ?? () from /usr/lib/libglib-2.0.so.0
#22 0x00007fffe9f99fc5 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#23 0x00007fffeb19fcbd in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt6Core.so.6
#24 0x00007fffeaf4c01e in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt6Core.so.6
#25 0x00007fffeaf4634d in QCoreApplication::exec() () from /usr/lib/libQt6Core.so.6
#26 0x000055555567fc09 in main ()
```

**Comment by kevinhendricks** [comment] 2024-09-01 14:03
Okay, found the bug.  Missed a test to handle warnings with no details info.  The NCX one is that type of warning.

I will push a fix for this to master.

**Comment by kevinhendricks** [comment] 2024-09-01 14:17
This is now fixed in master.
Since master has a few other useful fixes, you may way to build from Sigil master from today.  If not, you will need to hand apply this change.

```
diff --git a/src/MainUI/MainWindow.cpp b/src/MainUI/MainWindow.cpp
index a9904137c..d0430e0fd 100644
--- a/src/MainUI/MainWindow.cpp
+++ b/src/MainUI/MainWindow.cpp
@@ -1644,9 +1644,14 @@ void MainWindow::ShowLastOpenFileWarnings()
             QString msg;
             QString details;
             if (!info.isEmpty()) {
-                QStringList warning = info.split(QChar(31));
-                msg = warning[0];
-                details = warning[1];
+                if (info.contains(QChar(31))) {
+                    QStringList warning = info.split(QChar(31), Qt::KeepEmptyParts);
+                    msg = warning[0];
+                    details = warning[1];
+                } else {
+                    msg = info;
+                    details = "";
+                }
                 Utility::DisplayStdWarningDialog( 
                 "<p><b>" %
                 tr("Warning: ") % msg %
```

Having an epub2 with no NCX is very very rare as it is a required component of epub2, so whatever code built this epub is broken .   So we had no test case for this particular type of epub.  We do now.

**Comment by kevinhendricks** [comment] 2024-09-01 14:27
Thank you for your bug report!   The fix is in master and will appear in the next release.

**Closed by kevinhendricks** 2024-09-01 14:27 UTC
Labels: bug

**Comment by dougmassay** [comment] 2024-09-01 14:29
Good work! An ncx-less epub2 should be pretty rare, no?

**Comment by l0ddej0kk0** [comment] 2024-09-02 10:03
> ![sigil_weird](https://private-user-images.githubusercontent.com/7169162/363488823-df52b160-f9b8-48e5-a04a-50c0f1a639d2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzA5NTcsIm5iZiI6MTcyNTI3MDY1NywicGF0aCI6Ii83MTY5MTYyLzM2MzQ4ODgyMy1kZjUyYjE2MC1mOWI4LTQ4ZTUtYTA0YS01MGMwZjFhNjM5ZDIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMDk1MDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM0MDQ2YzI0NDliYWI4YjFhZjU3NjA2MWJiMWUwODU4OTIzZWZlMjE1NWUzZmZlYzdlNTQyZjIyNmEzNzc5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xy6GjfFSeSwS8A2zv3GhyNFnN1bE4ignYbD8DIXGIsU)
> 
> Sigil window after opening KE3.epub

I tried several other EPUBs now, and every time Sigil's window comes up like this, it will crash. Example:
[Clarkesworld #216 - Neil Clarke (ed.).epub.zip](https://github.com/user-attachments/files/16835805/Clarkesworld.216.-.Neil.Clarke.ed.epub.zip)
Again, don't unzip, merely remove the ".zip".

The EPUB creation is using https://chromewebstore.google.com/detail/epubpress-read-the-web-of/pnhdnpnnffpijjbnhnipkehhibchdeok which seems deprecated, though, so i'll probably switch to some other.

Usually, i look for a suitable cover image and metadata, then tell Calibre to polish the EPUB, which creates cover.xhtml, among other things.

The missing DOCTYPE stems probably from these 2 tools.

regards, l0ddej0kk0

**Comment by BeckyDTP** [comment] 2024-09-02 10:52
>     It does have a navigation.ncx, look in the KE3epub attached earlier.

The existence of a navigation.ncx file is not enough.
The name of the NCX file identifier must match the entry in the SPINE section.

Look here:

![sigil-opf-ncx-id](https://github.com/user-attachments/assets/205dfa27-3829-428c-b100-01e6dae33bbf)

**Comment by l0ddej0kk0** [comment] 2024-09-02 11:01
Hi,

just rebuilt from https://github.com/Sigil-Ebook/Sigil/archive/refs/heads/master.zip, but the version stays at 2.3.0. Though i did see in the make install output, that all files were indeed "installed", i.e. older ones overwritten.

Now, the coredump after opening certain EPUBs with the weird window placements seems gone, yay!

Fast work indeed, sir!

As to the two usual warnings on new EPUBs that Sigil has not yet seen before, thats:
![sigilwarn1](https://github.com/user-attachments/assets/e0f3dedf-c752-40fb-ac96-eab27d66a19c)
and
![sigilwarn2](https://github.com/user-attachments/assets/93a83aae-998a-4a7f-895e-235ad75f8a08)

regards, l0ddej0kk0

**Comment by dougmassay** [comment] 2024-09-02 11:07
Now that Sigil won't crash, you can easily eliminate the auto-generated ncx by correcting the spine to point to the id of your navigation ncx (as BeckyDTP described). Then save and reopen.

**Comment by kevinhendricks** [comment] 2024-09-02 13:46
Those Sigil warnings are correct.  As BeckyDTP said, your spine toc attribute does not match the id of the ncx file, it in fact specifies a manifest entry that does *not* exist in the manifest.  Again whatever software generated that epub2 is broken and should not be used.

And as for missing DOCTYPEs, that is a  common issue in epub2 epubs generated by Calibre.  Kovid is aware of this and decided not to include DOCTYPE even though it is part of the epub specification.  That is why Sigil checks and can auto fix those issues (but Sigil will still alert you).

**Comment by l0ddej0kk0** [comment] 2024-09-02 17:31
Hi,

for completeness i maybe should include what Sigil says at a console start:
```
$ sigil 
Info: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name sigil 
  *  browser-subprocess-path /usr/lib/qt6/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-threaded-compositing  
  *  in-process-gpu  
  *  use-gl desktop 

```

regards, l0ddej0kk0

**Comment by dougmassay** [comment] 2024-09-02 18:07
That's pretty typical output for a repo supplied Qt/WebEngineProcess.
