### ISSUE TITLE
Embedded Python Error

### ISSUE THREAD

**Issue by marwalk** [Sigil-Ebook/Sigil#665] opened 2022-01-08 16:37 UTC
When opening an ebook, Sigil displays several error pop-ups as follows on Fedora Linux:

- Embedded Python Error
Details: Traceback (most recent call last):

  File "/usr/share/sigil/python3lib/xmlprocessor.py", line 237, in performNCXSourceUpdates
    soup = BeautifulSoup(data, features=None, from_encoding="utf-8", builder=xmlbuilder)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/__init__.py", line 239, in __init__
    self._feed()

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/__init__.py", line 263, in _feed
    self.builder.feed(self.markup)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 151, in feed
    self.parser = self.parser_for(self.soup.original_encoding)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 86, in parser_for
    if isinstance(parser, collections.Callable):

AttributeError: module 'collections' has no attribute 'Callable'

- error in xmlprocessor performNCXSourceUpdates: -5
Traceback (most recent call last):

  File "/usr/share/sigil/python3lib/xmlprocessor.py", line 237, in performNCXSourceUpdates
    soup = BeautifulSoup(data, features=None, from_encoding="utf-8", builder=xmlbuilder)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/__init__.py", line 239, in __init__
    self._feed()

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/__init__.py", line 263, in _feed
    self.builder.feed(self.markup)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 151, in feed
    self.parser = self.parser_for(self.soup.original_encoding)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 86, in parser_for
    if isinstance(parser, collections.Callable):

AttributeError: module 'collections' has no attribute 'Callable'

- Embedded Python Error
Traceback (most recent call last):

  File "/usr/share/sigil/python3lib/xmlprocessor.py", line 269, in performOPFSourceUpdates
    soup = BeautifulSoup(data, features=None, from_encoding="utf-8", builder=xmlbuilder)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/__init__.py", line 239, in __init__
    self._feed()

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/__init__.py", line 263, in _feed
    self.builder.feed(self.markup)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 151, in feed
    self.parser = self.parser_for(self.soup.original_encoding)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 86, in parser_for
    if isinstance(parser, collections.Callable):

AttributeError: module 'collections' has no attribute 'Callable'

- error in xmlprocessor performOPFSourceUpdates: -5
Traceback (most recent call last):

  File "/usr/share/sigil/python3lib/xmlprocessor.py", line 269, in performOPFSourceUpdates
    soup = BeautifulSoup(data, features=None, from_encoding="utf-8", builder=xmlbuilder)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/__init__.py", line 239, in __init__
    self._feed()

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/__init__.py", line 263, in _feed
    self.builder.feed(self.markup)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 151, in feed
    self.parser = self.parser_for(self.soup.original_encoding)

  File "/usr/share/sigil/plugin_launchers/python/sigil_bs4/builder/_lxml.py", line 86, in parser_for
    if isinstance(parser, collections.Callable):

AttributeError: module 'collections' has no attribute 'Callable'

After that the ebook opens and all functions appear to operate correctly. I'd read this might be related to a file path breakage to a libxml2.so file, but the solution stated using a symbolic link to that executable had no effect on this problem in my installation. I also confirmed I have python3-lxml installed on my system.

**Comment by kevinhendricks** [comment] 2022-01-08 18:15
What exact version of python 3 are you using?  What exact version of Sigil?  

Will you please unzip a copy of your epub and look for the .ncx file, exteact it, zip it up and paste it here so that I can test it for parse errors or unexpected xml code.

**Comment by kevinhendricks** [comment] 2022-01-08 18:35
The traceback shows python code that no longer exists in master.  My guess is you are using a very very old version of Sigil that did not change to import Callable from either collections.abc or collections depending on try else clause.  Current python code in Sigil changed from collections.Callable to just Callable long ago.

You might want to place a bug report with the Fedora project to actually bring its Sigil version up to date.  It builds quite easily on most Linux distributionsout ofthe box.

So closing this as not a bug in master.  Just upgrade to a more recent version of Sigil or at least grab sigil_bs4 from master to replace the same in the older version.

**Closed by kevinhendricks** 2022-01-08 18:35 UTC
