### ISSUE TITLE
Sigil doesn't know about Dark Mode on MacOS

### ISSUE THREAD

**Issue by ZIwxBHld** [Sigil-Ebook/Sigil#442] opened 2019-07-19 21:01 UTC
In MacOS when Dark Mode is active, Sigil uses a dark background, but text is still coloured as specified by the stylesheet.

The easiest solution would be that Sigil doesn't use the system-suggested background but you guys would know more about where the background colour of the window comes from than me.

**Comment by dougmassay** [comment] 2019-07-19 21:20
Why would we want to prevent people from being able to use the system-suggested background? I'm afraid there is no one-size-fits-all solution here. So we honor the system suggestions and give users the ability to override where the system suggestions fail them.

**Comment by eli-schwartz** [comment] 2019-07-19 21:20
https://www.mobileread.com/forums/showthread.php?t=316213&highlight=sigil+macos+dark+mode

The UI toolkit that Sigil uses, Qt, does not support macOS Mojave Dark Mode. In a future release of Sigil, the version of Qt which Sigil is compiled against will be to a recent version that does support Dark Mode.

In the meantime there are other suggestions there.

**Comment by dougmassay** [comment] 2019-07-19 21:41
Actually, Qt5.12 (that we use with Sigil 0.9.15+) does support MacOS Darkmode. The problem is that we have font-defaults and user configurable font colors that may conflict with the system-suggested background. Code View is easily configurable by changing the font colors to work with DarkMode, but Preview is Web browser that's naturally only configurable with css (either the epub's or the user's custom overrides. 

The short answer is that even supporting DarkMode (which Sigil 0.9.15+ now does) does not make all issues magically go away.

**Comment by eli-schwartz** [comment] 2019-07-19 22:03
I figured the default colors in code view would follow the theme defaults and work out of the box -- obviously user overrides need to be carefully selected.

Does the webview preview actually respect the theme? Websites don't do that... unless a website offers variant site themes, in which case Safari has a media query which can request that the website provide a dark theme (and if I understand correctly, the theme is responsible for defining the background and foreground colors)

**Comment by dougmassay** [comment] 2019-07-19 22:11
I wouldn't expect Webview to respect the theme either. I can't swear that MacOS DarkMode overrides the WebView background, but I thought I heard reports that it does. I could be wrong about that.

We definitely have some work to do to get Sigil into a more theming-friendly state (via QPalette and such), but in the meantime, we give the user the ability to override pretty-much anything (qt stylesheets for most of Sigil, and custom css overrides for QWebEngineView). As outlined in the MobileRead thread you linked to.

**Comment by kevinhendricks** [comment] 2020-01-01 03:22
Preliminary support for DarkMode on macOS has now been committed to master.  It allows switching on the fly.  So closing this issue as fixed in master.  DarkMode macOS support will be in the next release of Sigil.

**Closed by kevinhendricks** 2020-01-01 03:22 UTC
